### ISSUE TITLE
想问一下，这个支持LDAP认证吗？

### ISSUE THREAD

**Issue by binghun0518** [running-elephant/datart#1005]
**你的功能要求与某个问题相关吗？**
清晰简洁地描述这个问题

**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
暂未支持
