### ISSUE TITLE
在分享出去的dashboard上支持url query参数绑定全局变量

### ISSUE THREAD

**Issue by kengle** [running-elephant/datart#1012]
如分享的url为 http://xxx.com/share?token=xxx ,  在embedded 到iframe中时, 
我们可以加上query param变成如下形式:
http://xxx.com/share?token=xxx&dept=xxx. 
然后dashboard在渲染时, 就会把dept的值绑定到全局变量$dept$中去, 视图的也随这个值去取数据.

这个用法, 我们主要是用来在客户系统中展示报表, 但是又不想跟datart在用户系统上做深度的集成.

**Comment by scottsut** [comment]
现在支持通过query param给仪表板控制器传值，如果控制板关联到变量，继而可以给变量复制

**Comment by kengle** [comment]
这个有具体的文档吗?

**Comment by kengle** [comment]
可以了, 原来是用  控制器标题=xxx的格式

**Comment by scottsut** [comment]
文档还没有，会尽快补上

**Comment by kengle** [comment]
很好的产品,  我们综合比较了redash, metabase 还有同样是国产的dataease, 觉得datart最符合我们的需求.
一来有完整的机制来开发图表插件.二来后台是用java的, 也方便我们去改造. 
文档真的简单了点, 希望能尽快完善.

**Comment by gaofei8704** [comment]
题主好，我现在用最新的release，在嵌入iframe的时候，报Refused to display  in a frame because it set 'X-Frame-Options' to 'deny'. 这个有没有开关打开？我在Nginx里设了没用
