### ISSUE TITLE
数据库编码的问题

### ISSUE THREAD

**Issue by freewind1977** [running-elephant/datart#1015]
版本：master
数据库版本：mysql 8.0
问题描述：
1.由于从beta.2版开始使用flyway来进行数据库结构变化的调整，目前大部分都在使用的是mysql5.7+以上的版本，由于现在的脚本使用的是utf8，执行脚本时会提示警告，建议调整为UTF8MB4的编码。
2.在datart.sql、V2022.02.18__baseline.sql中使用了utf8_unicode_ci，但在V2022.02.19__1.0.0.beta.2.sql中使用了utf8_general_ci两种，在执行时会有警告；

![image](https://user-images.githubusercontent.com/26646785/158533128-b6d84ebd-5b79-4f53-bf61-91c4ee48e7b1.png)

个人建议：在支持中文和英文两种环境下，建议使用UTF8MB4、utf8_general_ci，或者保持统一

**Comment by Cuiyansong** [comment]
link commit https://github.com/running-elephant/datart/pull/1801/commits/a827ffb694f4d6f3ec917616b437cc935186d3ea
