### ISSUE TITLE
建议在可视化板块中拆分 【仪表板 & 数据图表】，将【仪表板】从【目录】中取出与【演示】平级或置入【演示】中

### ISSUE THREAD

**Issue by guo81** [running-elephant/datart#1021]
【可视化】板块的【目录】中，同时存在【仪表板】和【数据图表】。从逻辑上讲，【仪表板】为【数据图表】组件的后置对象，这两者理应分开放置。
而当前将两者放在同一个【目录】板块下，存在逻辑混乱的问题。若编辑者偷懒未对目录和图表命名进行精细管理，当图表众多时，极易导致对各类图表的混淆。建议将【仪表板】从【目录】中取出，与【演示】平级，或者类比davinci置入【演示】中作为可视化的展示形式之一。
这样的操作还能带来另外的好处：能在大屏展示形式外，提供另一种针对仪表板的菜单式的数据呈现方式，满足自助数据服务的需求。——并非所有图表都需要通过大屏展示实现可视化，实际还存在这样的自助分析的需求。

**Comment by scottsut** [comment]
感谢建议！

在 datart 中，「仪表板做为图表组件的后置对象」这个条件并不成立。编辑者可以在仪表板中直接创建图表，直接创建的图表仅从属于仪表板，而无需在目录中占据一个位置。所以，从交互逻辑上，编辑者可以在编写完SQL之后直接创建仪表板，不必像 davinci 一样需要经过”独立保存图表“这样一个阶段。

之所以决定这样做，是基于现有经验的驱使。从之前 davinci 的使用情况来看，90%以上的图表仅被一个仪表板引用，复用度很低；并且在图表数量膨胀（超过1000个）的情况下，与仪表板之间的关系难以维护与管理。因此我们在 datart 中改变了图表与仪表板的引用关系，让图表既可以直接从属于某个仪表板，也可以独立保存在目录中。

为什么不彻底让图表从属于仪表板，还允许它独立保存？有以下无法忽视的场景存在：
1. 图表有被独立分享、或嵌入到第三方应用的需求。如果图表从属于仪表板，对被分享资源的访问权限、数据权限控制会不太好实现。
2. 在多个仪表板中被重复引用的需求。有、但较少。
3. 作为探索分析的中间结果保存的需求。
4. 复杂图表也有独立预览的需求。

基于以上原因，我们让仪表板和图表展示在一个目录中。我们对常规使用情况的预期是：目录中大部分为仪表板、并包含少量独立图表；这个预期和你所描述的”能在大屏展示形式外，提供另一种针对仪表板的菜单式的数据呈现方式“是基本吻合的。

你的观点有道理，但我觉得可能还不够充分，欢迎探讨🤝

**Comment by snycc15** [comment]
我也建议将仪表盘和图表分开，图表类似一个个指标可视化数据，而仪表盘作为大屏或驾驶舱来组合这些一个个图表，我现在是通过定义主题目录、图表目录、大屏目录、驾驶盘目录，将图表与仪表盘目录分开了。

**Comment by scottsut** [comment]
> 我也建议将仪表盘和图表分开，图表类似一个个指标可视化数据，而仪表盘作为大屏或驾驶舱来组合这些一个个图表，我现在是通过定义主题目录、图表目录、大屏目录、驾驶盘目录，将图表与仪表盘目录分开了。

可以说说为什么要建立图表目录，而不选择在仪表板里直接创建图表吗？你们的复用图表很多吗？

**Comment by snycc15** [comment]
我们的应用结构是：主题->数据模型->指标->驾驶舱/大屏，本身这四个就是独立的资源，可被单独共享可复用，所以我们才认为有必要进行分门别类。

**Comment by scottsut** [comment]
> 我们的应用结构是：主题->数据模型->指标->驾驶舱/大屏，本身这四个就是独立的资源，可被单独共享可复用，所以我们才认为有必要进行分门别类。

你们的指标平均复用率有多少？也就是说一个指标会在几个大屏中出现？

**Comment by snycc15** [comment]
在同一个主题下指标复用率是比较高，我个人认为并不是复用率高低的问题，而是更有利于管理分类，结构层次也更清楚等。

**Comment by scottsut** [comment]
> 在同一个主题下指标复用率是比较高，我个人认为并不是复用率高低的问题，而是更有利于管理分类，结构层次也更清楚等。

单就你们的场景来说，最理想的情况是：应用以”主题“作为基本分类和入口，进入”主题“页后，可以按照”数据模型 -> 指标图表 -> 驾驶舱/大屏“的流程来进行加工制作。

如果我们在 datart 中将仪表板和图表分开，你依然面临着要在仪表板和图表中分别创建主题目录来管理维护。这么看来，按照现在的方式，在主题目录下维护”驾驶舱/大屏“和”指标图表“两个子目录也未尝不可，甚至更好管理。所以你的观点”更有利于管理分类，结构层次也更清楚“有待商榷。

**Comment by snycc15** [comment]
我们理解：图表实际上是指标化数据，所以归到数据视图下与数据模型一同管理，而仪表板是而向应用，只是引用指标数据，指标可以被不同的仪表盘调用。最根本的思路是：主题下有数据模型和指标，仪表盘会有单主题或多(跨)主题。
