### ISSUE TITLE
关于第三方登陆的问题

### ISSUE THREAD

**Issue by freewind1977** [running-elephant/datart#1022]
版本：master
问题：打开登陆界面，就会默认发送：/datart/api/v1/tpa/oauth2login请求第三方登陆，此时没有做使用第三方登陆话，会有返回失败
![image](https://user-images.githubusercontent.com/26646785/158722742-f1fca78d-0ad3-4bc5-8e9e-71687ef1fa3e.png)

**Comment by scottsut** [comment]
beta.3 版本已优化
