### ISSUE TITLE
仪表板数据下载问题

### ISSUE THREAD

**Issue by ecit-zzh** [running-elephant/datart#1032]
**Datart版本号**
    beta2

**错误描述**
    从仪表板中下载数据到excel后，excle表格显示的数据有缺失

**截图**
![仪表板](https://user-images.githubusercontent.com/14269688/158795995-169d5ba6-3f58-42f4-be25-345f82547ba5.png)
![excel](https://user-images.githubusercontent.com/14269688/158796014-5435d79e-caf6-469f-81b5-d56ceaa9e741.png)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: centos7
- 数据源: impala3.2
- 浏览器: chrome

**Comment by scottsut** [comment]
请提供下服务器日志，这种情况应该有异常信息
