### ISSUE TITLE
【演示】中，各幻灯片的排序问题

### ISSUE THREAD

**Issue by q1139168548** [running-elephant/datart#1037]
**你的功能要求与某个问题相关吗？**
在创建演示的时候，左侧不能拖动各幻灯片进行重新排序

**形容一下你想要的解决方案**

**描述一下你考虑过的备选方案**

**其他内容**

**Comment by q1139168548** [comment]
刚刚看到代码里已经有相关方法了，但没有写具体逻辑，请问官方是已经有这个功能的开发想法了吗？

**Comment by scottsut** [comment]
应该是没来得及做的功能

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
