### ISSUE TITLE
是否支持行列汇总/占比/同比/环比

### ISSUE THREAD

**Issue by huzk8** [running-elephant/datart#1041]
**你的功能要求与某个问题相关吗？**
是否支持行列汇总/占比/同比/环比

**形容一下你想要的解决方案**
期望支持行列汇总/占比/同比/环比

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
表格支持了对数值列进行总计，其他的快速计算还没有支持，后续会陆续支持起来

**Comment by wangfan0840** [comment]
请问下预计什么时候会支持？

**Comment by scottsut** [comment]
Related to #1439
