### ISSUE TITLE
Pivot table total and subtotal is hardcoded to chinese

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1046]
**Datart Version**
The version of `datart` you using. 1.0.0b2

**Describe the bug**
The Pivot creation -> Analysis tab has hardcoded chinese characters for total and subtotal positioning options. Once enabled, the total and subtotal descriptions are also displayed in chinese in the pivot table.

**To Reproduce**
1. Go to 'Vizs'
2. Click on 'Pivot Table'
3. Drag fields to Rows and Metrics to create any pivot table
4. Click on Analysis tab
5. Enable Row total and subtotal
6. The dropdown options are in chinese. The pivot total and subtotal descriptions are also in chinese.

**Expected behavior**
The mentioned chinese texts should be displayed in english in English viewing browsers.

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10] Windows 10
 - Source Database: [e.g. MySQL 8.0.26] MySQL 8.0.25
 - Browser: [e.g. chrome 94, safari 15] Chrome 99

**Additional context**
![image](https://user-images.githubusercontent.com/100477931/158998234-8b390540-6b81-41dd-a7a9-2fd35dddf483.png)

**Comment by clementchong** [comment]
Prior posting this issue, I also spent some time trying to add i18n. Was able to do for the Analysis dropdown but could not locate the codes responsible for the total and subtotal descriptions in the pivot table. Any advice?

![image](https://user-images.githubusercontent.com/100477931/159000492-5bcd233d-be4c-468e-8a11-85edefe9c83f.png)

![image](https://user-images.githubusercontent.com/100477931/159000395-e07be39c-66ca-431c-b55c-980c14add4e6.png)

**Comment by clementchong** [comment]
Any hint where to find the codes that generated the chinese text in pivit subtotal and total?

![image](https://user-images.githubusercontent.com/100477931/159216742-78f05a60-732b-400f-9ea1-f00b3100e67d.png)

**Comment by scottsut** [comment]
> Any hint where to find the codes that generated the chinese text in pivot subtotal and total?
> 
> ![image](https://user-images.githubusercontent.com/100477931/159216742-78f05a60-732b-400f-9ea1-f00b3100e67d.png)

We have done this part in #1061 , but thanks anyway for your participation.

**Comment by clementchong** [comment]
Great! Looking forward to it. Thank you!
