### ISSUE TITLE
怎么实现发布后的报表跳转

### ISSUE THREAD

**Issue by caiiansheng** [running-elephant/datart#105]
设计完报表后，要把发布的报表链接嵌入到其他系统的菜单中，需要原报表中设置的跳转链接可以生效（目前只支持设计时候跳转），设计或管理报表只有几个管理人员才有权限，分享出去应该都能有跳转的权限

**形容一下你想要的解决方案**
希望可以通过设置权限或其他方式，只要有权限或是分享的链接，都可以实现跳转

**Comment by nnzh** [comment]
目前的跳转只在设计页面生效，如果通过分享链接页面，点击图表的跳转是不生效的，只有地址栏的参数会有变化

**Comment by scottsut** [comment]
基于报表权限控制的原因，不倾向于实现从分享页直接跳转至主应用且无需鉴权。感谢 @ParkerJX 贡献了可以跳转至指定url的功能，目前建议在源仪表板中配置url类型跳转到目标仪表板的分享页，这样在源仪表板的分享页中也可以生效。

**Comment by fujua08093206** [comment]
通过URL的形式可以实现两个看板之间打跳转或者是两个分享链接的跳转，但是URL的参数需要怎么设置，下钻的时候参数需要怎么设置，比如的场景是从全国总览的看板要跳转到具体的省份的看板，数据上要怎么去传参。目前的URL的形式可以带参数，但是参数要怎么设置才生效？

**Comment by will0815** [comment]
分享页限制登录且为分享者权限，这样也支持跳转图表或仪表盘么

**Comment by liuguoyu** [comment]
我强制只支持对话框模式，嵌入系统应用时，使用JumpToUrl会遇到权限问题。
