### ISSUE TITLE
数据视图从hive数据源中使用任何变量均报错

### ISSUE THREAD

**Issue by lqs300** [running-elephant/datart#1053]
**Datart版本号**
beta.1
beta.2

**错误描述**
数据源为hive 2.0，测试连接成功
建立数据视图从hive数据源查询，SQL中使用任何变量均报错 cannot set required property 'Quoting' to null

**截图**
![image](https://user-images.githubusercontent.com/43107248/159220969-2a75bee9-7faa-41ef-b78b-255160c4e0e9.png)

![6869890d58921e6a8c77f8a548f9972](https://user-images.githubusercontent.com/43107248/159219580-7af97510-d3c5-439a-930f-1066dabe1c60.png)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: CentOS 7
- 数据源: Hive 2.0
- 浏览器: Chrome 94

**Comment by lqs300** [comment]
请关注一下这个问题

**Comment by scottsut** [comment]
请补充一下前提条件：
1. 使用安装包还是二次开发？
2. datart 版本
3. `jdbc-driver-ext.yml` 中的配置信息

**Comment by lqs300** [comment]
> 

你好，报Quoting错误的问题已经解决了，由于Datart内置了HIVE类型选项，我以为没有必要在jdbc-driver-ext.yml配置，经你提醒，我在配置文件中增加了HIVE的相关参数，现在连接已经正常了

\#EXAPLE:
\#  db-type: "example"
\#  name: "example"
\#  driver-class: "com.example.jdbc.Driver"
\#  literal-quote: "'"
\#  identifier-quote: "`"
\#  url-prefix: jdbc:example://

IMPALA:
  db-type: "impala"
  name: "impala"
  driver-class: "com.cloudera.impala.jdbc41.Driver"
  literal-quote: "'"
  identifier-quote: "`"
  adapter-class: "datart.data.provider.jdbc.adapters.ImpalaDataProviderAdapter"
  url-prefix: "jdbc:impala://"
  sql-dialect: "datart.data.provider.calcite.dialect.ImpalaSqlDialectSupport"

HIVE2:
  db-type: "hive2"
  name: "hive2"
  driver-class: "com.cloudera.hive.jdbc41.HS2Driver"
  literal-quote: "'"
  identifier-quote: "`"
  url-prefix: "jdbc:hive2://"

ORACLE:
  quote-identifiers: false

DORIS:
  db-type: "doris"
  name: "doris"
  driver-class: "com.mysql.cj.jdbc.Driver"
  literal-quote: "'"
  identifier-quote: "`"
  adapter-class: "datart.data.provider.jdbc.adapters.DorisDataProviderAdapter"
  url-prefix: "jdbc:mysql://"
