### ISSUE TITLE
取消仪表板及图表打开时上方的标签或提供一键关闭多个功能

### ISSUE THREAD

**Issue by guo81** [running-elephant/datart#1058]
**你的功能要求与某个问题相关吗？**
在【目录】页面下打开先后打开多个仪表板或图表页面需要关闭时，需要挨个点击上方图表或仪表板标签右侧的关闭符号，体验极差

**形容一下你想要的解决方案**
直接取消上方标签显示的功能，这个功能使用体验很鸡肋。

**描述一下你考虑过的备选方案**
提供一键关闭全部图表或仪表板功能

**其他内容**
![图片](https://user-images.githubusercontent.com/40499469/159273049-affc9f9e-9e2c-4319-b4b9-71e176da5cae.png)

**Comment by scottsut** [comment]
#1432
