### ISSUE TITLE
Dashboard controller for date filter is not correct

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1059]
**Datart Version**
1.0.0b2

**Describe the bug**
The generated SQL uses BETWEEN but the end date/time is one second more than the date picker.

**To Reproduce**
1. Add any report with date column into a dashboard
2. Add controller with date range or date
3. Use exact or relative date
4. See SQL log

**Expected behavior**
The end date/time should be till 23:59:59 or 23:59:59.999

**Screenshots**

Exact date range:
![image](https://user-images.githubusercontent.com/100477931/159271129-937c30eb-04c2-4011-9ab7-0650b1f28553.png)
![image](https://user-images.githubusercontent.com/100477931/159270919-1c892fd1-6166-4ef8-9a7c-7634ee521a38.png)

Relative date range: 
![image](https://user-images.githubusercontent.com/100477931/159271576-f7e42c88-9182-4ea0-b724-c3226124da7a.png)
![image](https://user-images.githubusercontent.com/100477931/159271369-991759fa-39b8-4092-8aaf-2c8d92f8d760.png)

Current Month: Should the query filter for all transactions in current month and not just one day?
![image](https://user-images.githubusercontent.com/100477931/159272915-df1e388d-3148-4491-acc8-6752885ac73a.png)
![image](https://user-images.githubusercontent.com/100477931/159272777-d7580998-2685-48a2-bf41-1353e79fd60c.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10] Windows 10
 - Source Database: [e.g. MySQL 8.0.26] 8.0.25
 - Browser: [e.g. chrome 94, safari 15] Chrome 99

**Additional context**

**Comment by xieliuduo** [comment]
已修复  #1228

**Comment by clementchong** [comment]
> 已修复 #1228

Great news! Thank you!
