### ISSUE TITLE
希望在 保存到仪表板 对话框中提供新建仪表板功能

### ISSUE THREAD

**Issue by guo81** [running-elephant/datart#1060]
**你的功能要求与某个问题相关吗？**
开始分析-完成一个图表-保存到仪表板，然后发现忘了创建仪表盘，要想保证为私有图表，就只能先退出，新建仪表板后重新制图

**形容一下你想要的解决方案**
在保存到仪表板对话框中提供新建仪表板功能；同理还有添加到故事板对话框

**描述一下你考虑过的备选方案**

**其他内容**
![图片](https://user-images.githubusercontent.com/40499469/159275235-b577552f-8504-4ef3-adeb-5132430f6c7e.png)

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
