### ISSUE TITLE
数据分析中的图表缺少sum等聚合函数

### ISSUE THREAD

**Issue by freewind1977** [running-elephant/datart#1062]
版本：beta.2
问题描述：
数据分析中只有透视表分析时，指标可以进行sum、avg等聚合计算，图表等其他无法使用只有count;
![image](https://user-images.githubusercontent.com/26646785/159426876-51f09a81-0507-45a4-91af-e4b9c6722068.png)

**Comment by Cuiyansong** [comment]
在数据源视图中，将trade_fee设置为数字类型（Number），然后重新创建一个柱状图并拖拽如图所示的方式
