### ISSUE TITLE
容器组件 Tab 控件，每个标签页内仅能放一个图表，希望能拖放多个（文档上描述可以放多个）

### ISSUE THREAD

**Issue by 3woodpro** [running-elephant/datart#1070]
**你的功能要求与某个问题相关吗？**
容器组件 Tab 控件，标签页拖放问题

清晰简洁地描述你希望发生什么？

容器组件 Tab 控件，每个标签页内仅能放一个图表，希望能拖放多个

清晰简洁地描述任意你考虑过的备选方案和功能

有关这个功能要求的任意其他内容或截图

**Comment by clementchong** [comment]
I also think this feature would be very useful. Then it is possible to build a multi-tab dashboard where each tab can show a collection of viz like a dashboard itself. Right now, there is only functionality for one viz in each tab or we need to break into separate dashboards to do it. However, the presentation like this is not good and messy for end users

![image](https://user-images.githubusercontent.com/100477931/166890921-1aebe167-52a4-4d15-a3b6-8115225983d0.png)

**Comment by scottsut** [comment]
beta.4 版本支持仪表板组件“成组”，可以将“成组”后的多个组件放到 tab 页中，相当于用另一种方式满足了这个需求
