### ISSUE TITLE
希望增加报表页面类似文本变量绑定的功能

### ISSUE THREAD

**Issue by 3woodpro** [running-elephant/datart#1074]
清晰简洁地描述这个问题
有些报表页面中不全是图表，有可能是含有动态数据变量的文本

![image](https://user-images.githubusercontent.com/66361194/159652313-a8e3bc29-9e2c-4c63-ac50-809fc869d11f.png)

**Comment by scottsut** [comment]
可以考虑使用富文本组件来实现

**Comment by 3woodpro** [comment]
请教一下，文本内动态内容怎么替换呢？

**Comment by q1139168548** [comment]
![image](https://user-images.githubusercontent.com/48168645/159655087-4905fe2f-9206-4253-8ef4-b85c52549657.png)
点击图中这个按钮，就可以把字段插入到文本中
