### ISSUE TITLE
share page title shows dashboard name

### ISSUE THREAD

**Issue by JoshTseeee** [running-elephant/datart#1076]
**Describe the solution you'd like**

After opening the dashboard share link, the tab title shows the dashboard name
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/26848111/159659637-91f135cb-2545-474b-b7d7-322a1aa0d901.png">

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
