### ISSUE TITLE
关于仪表板和自助分析的一些建议（1）

### ISSUE THREAD

**Issue by ynzzxc** [running-elephant/datart#1077]
1、支持在新建数据图表页面修改数据图表名称
2、支持在仪表板编辑页面选择是否显示数据图表名称，显示的位置
3、数据视图默认以表格形式显示，而不是以sql形式显示
4、增加数据视图共享给角色/成员的功能，默认不授予编辑权限
5、增加自助分析目录，自助分析的数据图表、仪表板不能发布，但可以共享给其他成员
6、自助分析的数据视图、仪表板被分享后支持复制

**Comment by scottsut** [comment]
感谢建议！

1. 可以考虑优化交互
2. 当前的仪表板组件支持编辑标题；可以考虑与问题1一起优化
3. 数据视图未来会支持非SQL的创建方式，这部分会一起重构
4. 这个问题通过给角色/成员授予指定数据视图的使用权限不能满足吗？
5. 没理解这个目录的必要性；理论上你自己创建一个目录，在里边制作可视化作品，不发布、仅做分享，这些目前都是支持的
6. 这部分功能未来会以其他方式来支持

**Comment by ynzzxc** [comment]
> 感谢建议！
> 
>     1. 可以考虑优化交互
> 
>     2. 当前的仪表板组件支持编辑标题；可以考虑与问题1一起优化
> 
>     3. 数据视图未来会支持非SQL的创建方式，这部分会一起重构
> 
>     4. 这个问题通过给角色/成员授予指定数据视图的使用权限不能满足吗？
> 
>     5. 没理解这个目录的必要性；理论上你自己创建一个目录，在里边制作可视化作品，不发布、仅做分享，这些目前都是支持的
> 
>     6. 这部分功能未来会以其他方式来支持

非常感谢！
关于4和5的补充说明：可以将它理解为一个企业内部跨组织的数据分析社区。现阶段的自助分析产品的确降低了数据分析门槛，但仍然缺乏活力。

**Comment by scottsut** [comment]
> 非常感谢！ 关于4和5的补充说明：可以将它理解为一个企业内部跨组织的数据分析社区。现阶段的自助分析产品的确降低了数据分析门槛，但仍然缺乏活力。

社交功能在这类产品里不太好权衡，企业级数据产品安全需求大于社交，社交需要在满足权限控制的前提下去设计。首先普通角色之间共享数据视图有悖于资源权限及数据权限管理；可视化层相对来说社交需求更大、也相对好支持一些。目前仅支持以分享链接形式来满足社交需求，未来还会提供一些渠道，但也是在满足安全与隐私的前提下。
