### ISSUE TITLE
控制器不能读取数据视图信息

### ISSUE THREAD

**Issue by snycc15** [running-elephant/datart#1078]
**Datart版本号**
datart.beta.2
**错误描述**
创建下拉列表不能读取数据视图字段信息

**如何重现**
控制器-新建下拉列表-取值配置-选择数据视图-不能列出字段，数据视图通过数据模型修改过。
**期望结果**
清晰简洁地描述你期望的结果是什么

**截图**
如果方便的话，添加一个截图帮助解释你的问题
![image](https://user-images.githubusercontent.com/67908124/159671048-b4eb1338-ad3b-4b22-9101-435c09a355c1.png)

**运行环境详情：(可选，取决于错误发生的具体位置)**

**其他内容**
有关这个问题的任意其他内容

**Comment by scottsut** [comment]
#996
