### ISSUE TITLE
透视表在仪表盘中不能正常使用

### ISSUE THREAD

**Issue by snycc15** [running-elephant/datart#1079]
**Datart版本号**
datart.meta.2
**错误描述**
1、透视表在仪表盘中无法通过滚动条进行上下拉动；
2、鼠标位置不同步，例如当前鼠标位置放在第三行第四列，实际浮动显示值为第二行第三列。
**如何重现**
重现错误的步骤，例如：
1. 到...页面
2. 点击...
3. 滚动到...
4. 看到错误

**期望结果**
清晰简洁地描述你期望的结果是什么

**截图**
如果方便的话，添加一个截图帮助解释你的问题

**运行环境详情：(可选，取决于错误发生的具体位置)**
**其他内容**
有关这个问题的任意其他内容

**Comment by scottsut** [comment]
并未发现描述的问题，请提供问题相关的截图或视频

**Comment by snycc15** [comment]
通过访问分享链接，不存在这两个问题，但在本身仪表盘中确实有问题，不能上下拉动的问题应该是这个鼠标位置导致。
![image](https://user-images.githubusercontent.com/67908124/159686504-5e7f89e1-d576-4592-9f73-74c0c7135ae9.png)

**Comment by Cuiyansong** [comment]
目前在Demo环境是Beta2版本，没有复现滚动条无法滚动事件；图中数字`4,535`的样式是鼠标点击过单元格的样式，跟滚动行无关；

**Comment by snycc15** [comment]
我这边试过好几遍了，注意是透视表放入仪表盘后才会有问题，鼠标定位不准且滚动条无法上下拉动。

**Comment by snycc15** [comment]
经确认在自由布局下，会存在此类问题。

**Comment by Cuiyansong** [comment]
> 经确认在自由布局下，会存在此类问题。

如能复现，请`详细`描述复现步骤以更好的排查问题。另外一点是在编辑模式的Dashboard只有在双击图表之后才能滚动图表，请确认不是在这种情况下操作的。

**Comment by snycc15** [comment]
在自由布局下->添加透视图表->保存后->鼠标放在该图表位置不对，也不能上下拉动。编辑模式下经过双击也是一样的问题的，建议你们简单复现即可，注意要在自由布局下，立马就能发现问题。

**Comment by Cuiyansong** [comment]
windows和mac均可以手动拖动透视表在自由布局的Dashboard中。能否提供复现Demo环境的有问题的图表便于我们复现。

**Comment by Cuiyansong** [comment]
另外请描述下，您的操作系统版本，浏览器，浏览器版本，谢谢

**Comment by snycc15** [comment]
我真的无语了，我电脑win7,浏览器chrome 99和360都一样的问题，官方的演示地址：http://datart-demo.retech.cc/ 组织机构选ycc,仪表盘->透视表测试2
![image](https://user-images.githubusercontent.com/67908124/160098776-9ab60855-0562-4ca2-9e72-ef56a4c041fb.png)

**Comment by Cuiyansong** [comment]
方便提供账户名和密码？或者可以加我微信18611145648

**Comment by snycc15** [comment]
就是官方的缺省账号：demo/123456

**Comment by Cuiyansong** [comment]
![Screen Shot 2022-03-28 at 10 37 54 AM](https://user-images.githubusercontent.com/4497555/160317143-ab5206af-6d5b-47ac-958d-ff1eee50be95.png)

`透视表测试2`中只**7**行数据，当没有达到容器最大高度时，自然无法滚动。另外我调整了下`仪表盘`-`仪表盘测试`这个Dashboard中透视表整体的高度，我当前系统mac+chrome99是可以滚动的，你可以再测试一下，如果能滚动，这个Issue即将关闭。

**Comment by snycc15** [comment]
我是win7 chrome99,问题依旧，鼠标不同步，正下无法拉动。

https://user-images.githubusercontent.com/67908124/160319390-bdc1258d-df57-4180-9b95-51e9bee424d3.mp4

**Comment by Cuiyansong** [comment]
AntV/S2在win7下确实存在兼容性问题，可以尝试跑一下S2官方的用例：https://s2.antv.vision/en/examples/case/comparison#philosophers
如果依然存在问题，可以给S2提个ISSUE

**Comment by snycc15** [comment]
官方用例是正常的，这个问题主要是发生在自由布局下面。

**Comment by Cuiyansong** [comment]
十分感谢提供的问题线索，目前初步定位问题的原因是antv/s2在缩放的情况下存在鼠标事件不一致问题。
