### ISSUE TITLE
联动设置支持联动查询变量设置

### ISSUE THREAD

**Issue by heropoet** [running-elephant/datart#1083]
**你的功能要求与某个问题相关吗？**
希望在联动设置支持联动目标组件的查询变量，实现更丰富的联动效果

**形容一下你想要的解决方案**
![image](https://user-images.githubusercontent.com/41409482/159835169-c24448a1-b98d-4bc4-a3bb-f11b6e87a4eb.png)

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by Cuiyansong** [comment]
Beta4已经重写联动功能，关闭当前Issue。
