### ISSUE TITLE
表格组件设置联动时，源端的字段无法选入date类型的字段

### ISSUE THREAD

**Issue by heropoet** [running-elephant/datart#1084]
**Datart版本号**
声明一下你正在使用的 `datart` 版本号
Version: 1.0.0-beta.2

**错误描述**
清晰简洁地描述这个错误
表格组件设置联动时，源端的字段无法选入date类型的字段
![image](https://user-images.githubusercontent.com/41409482/159835632-26d2fb97-c845-4256-9371-922e464705a8.png)
见demo环境:
http://datart-demo.retech.cc/organizations/aaeecf65d4164950bf1469269a6aabbb/vizs/9178ca4cc0a746c49aa86d01fe03db61
**如何重现**
重现错误的步骤，例如：
1. 到...页面
2. 点击...
3. 滚动到...
4. 看到错误

**期望结果**
清晰简洁地描述你期望的结果是什么

**截图**
如果方便的话，添加一个截图帮助解释你的问题

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: [例如 Windows 10]
- 数据源: [例如  MySQL 8.0.26]
- 浏览器: [例如 chrome 94, safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by xieliuduo** [comment]
我们将在 下个版本 优化这个问题

**Comment by scottsut** [comment]
beta.4 版本联动设置已重构，关闭此 issue
