### ISSUE TITLE
能否增加OAuth2.0的支持？

### ISSUE THREAD

**Issue by seekeyl** [running-elephant/datart#109]
一般分析系统不会单独使用，如果要重新输入用户名密码会比较麻烦，因此建议增加基于OAuth2.0协议的单点登录支持。

**Comment by cc-fangli** [comment]
我们也是内嵌的系统里面使用，是否可以支持多种SSO和协议。
我们需要的是 JWT token。
其实访问第三方http数据源也需要把token传递，这样就能形成用不同的用户，看到不懂得数据。

**Comment by scottsut** [comment]
> 我们也是内嵌的系统里面使用，是否可以支持多种SSO和协议。 我们需要的是 JWT token。 其实访问第三方http数据源也需要把token传递，这样就能形成用不同的用户，看到不懂得数据。

datart 应用本身就是使用 jwt token 进行鉴权的
