### ISSUE TITLE
添加数据源失败

### ISSUE THREAD

**Issue by caiiansheng** [running-elephant/datart#1091]
**Datart Version**
1.0.0-beta.2

**Describe the bug**
新建数据源提示保存成功，但是报了写错误信息，数据源无法使用

**Screenshots**
![image](https://user-images.githubusercontent.com/26760483/159913384-46cefb87-096f-4812-9219-309f991a3c0d.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by scottsut** [comment]
像是自动升级sql脚本没有执行成功，导致表没有创建。你把服务启动日志发一下
