### ISSUE TITLE
数据视图数据模型字段别名支持

### ISSUE THREAD

**Issue by snycc15** [running-elephant/datart#1107]
**你的功能要求与某个问题相关吗？**
数据模型支持字段别名配置或重命名

**形容一下你想要的解决方案**
支持字段名的中文别名

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
Related to #1339
