### ISSUE TITLE
关于变量的bug

### ISSUE THREAD

**Issue by CoderGong** [running-elephant/datart#1113]
现象：两个筛选框均为多选下拉列表，且筛选框中的值均来自单图的视图；前一个筛选框的值，作为后一个筛选框视图中变量，当前一个筛选框中选中一条数据时，后一个筛选框能成功查询，但是当前一个筛选框选中两条数据时，后一个筛选框就会在前端页面报错。。。

原因：在代码中打印sql发现，当前一个筛选框中的选中两个选项时，后一个筛选框的视图中sql中的发<if>标签没有去掉，初步判断应该是FreemarkerContext类中的process方法有问题

**Comment by scottsut** [comment]
SELECT DISTINCT
 `DATART_VTABLE`.`product_name` AS `product_name` 
FROM
 (
 SELECT DISTINCT
  app_name AS product_name 
 FROM
  dim_ua.product_info 
 WHERE
 1 = 1 
 AND app_name IS NOT NULL
  < #if PRODUCT_TYPE != NULL>      
  AND category_cn_name IN ('扑克牌游戏','休闲')    
  </#if> )  AS `DATART_VTABLE`  LIMIT 99999999  OFFSET 0
