### ISSUE TITLE
Pivot with row header as metric name position shows chinese characters

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1114]
**Datart Version**
1.0.0b2

**Describe the bug**
Using pivot table on http://datart-demo.retech.cc/ and upon switching on row header, the metric column name shows chinese characters.

**To Reproduce**

**Expected behavior**
Column name should support i18n functionality

**Screenshots**
![image](https://user-images.githubusercontent.com/100477931/160854093-cea80db2-5759-4d11-b05e-659cc97055d8.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10] Windows 10
 - Source Database: [e.g. MySQL 8.0.26] 8.0.25
 - Browser: [e.g. chrome 94, safari 15] Chrome 99

**Additional context**

**Comment by Cuiyansong** [comment]
[Link S2 Issue](https://github.com/antvis/S2/issues/1212)

Will be upgrade to @Antv/S2 - v1.14

**Comment by scottsut** [comment]
Upgraded
