### ISSUE TITLE
dev impala连接不上. 

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#1122]
**Datart版本号**
dev

**错误描述**
<img width="926" alt="image" src="https://user-images.githubusercontent.com/83893570/160996187-9ef5f41b-eea6-4a6a-991a-be738f51645e.png">

imapala 连接不上了。 这块是不是重构过.  2月底的版本还能正常连接。

**相关配置**
<img width="672" alt="image" src="https://user-images.githubusercontent.com/83893570/160995987-8e2627fc-fea7-4585-9b1b-58c0401f1846.png">

<img width="852" alt="image" src="https://user-images.githubusercontent.com/83893570/160996039-0f38b171-5511-4cf7-b2fc-e7c6e5c82ae9.png">

**Comment by scottsut** [comment]
源码运行你得把驱动放到 classpath 路径底下啊

**Comment by Data-bytes305** [comment]
我打包放在服务器上运行的。

**Comment by scottsut** [comment]
这部分没有重构
