### ISSUE TITLE
Option to enable column total and subtotal

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1123]
**Is your feature request related to a problem? Please describe.**
Current build has option to show row total and subtotal values. In some cases, we may prefer to also have column totals and subtotals.

**Describe the solution you'd like**
Replicate the codes for row total and subtotal to add column total and subtotals for display.

![image](https://user-images.githubusercontent.com/100477931/161001943-7d0718f6-1056-49f0-8458-6e5b934196b9.png)

Good to have column total and subtotal options

![image](https://user-images.githubusercontent.com/100477931/161002700-6ed01579-d870-409a-bc48-8c84aebcc0cd.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by Cuiyansong** [comment]
- Add Column Total and Column Sub Total Configuration
- Add Row/Column Calculation Method, include SUM(Default), Min, Max, Avg.

**Comment by clementchong** [comment]
This is great! Can't wait for next release! Thank you!

**Comment by Cuiyansong** [comment]
{Marked S2 Fixed Issue](https://github.com/antvis/S2/pull/1282)
