### ISSUE TITLE
Any potential runtime issue to run multiple datart-server on same box?

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1126]
Any issue if we have multiple datart running on same server with different ports? Databases are on different schemas but same mysql instance and port. datart.conf would have a different database value, e.g

datasource.database=datart_1

datasource.database=datart_2

Do we have code, reference, token, etc conflict issue?

**Comment by scottsut** [comment]
It is possible to deploy multiple datart instances in one server, but now there are some issues with the startup script, so that only one instance can actually be started, you can do it by modifying the startup script logic.

**Comment by clementchong** [comment]
Ok, would try out and share script if successful

**Comment by clementchong** [comment]
I think you are referring to the linux shell script. The windows one runs fine and able to support multiple datart instances on same box.

**Comment by clementchong** [comment]
PR submitted

**Comment by clementchong** [comment]
Yay! PR approved and merged.
