### ISSUE TITLE
透视图下载

### ISSUE THREAD

**Issue by gavin199006** [running-elephant/datart#1127]
**你的功能要求与某个问题相关吗？**
清晰简洁地描述这个问题
运营部门或者财务部门需要下载聚合后的透视图表excel中以便于二次统计

**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么
要求下载的格式和页面呈现的格式是一致的

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图
![image](https://user-images.githubusercontent.com/18094640/161030028-e499d84f-b98f-4303-bc4c-daa95800c8bb.png)

**Comment by scottsut** [comment]
Duplicate of #818

**Comment by gavin199006** [comment]
![image](https://user-images.githubusercontent.com/18094640/161227707-ccd13506-7a3f-4409-8e43-8fa0f62b81fc.png)
显示格式和下载格式不一致
