### ISSUE TITLE
Schedule&Source 增加Folder

### ISSUE THREAD

**Issue by yqwoe** [running-elephant/datart#114]
**你的功能要求与某个问题相关吗？**
清晰简洁地描述这个问题

**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
> 我们分析是直接从业务只读库取数据的，业务部门和系统也比较多这样。

你的场景描述太少了，我是这么理解的：你们企业里直接授权业务部门自己来创建数据源，是吗？
