### ISSUE TITLE
普通表格可配置基础属性增强

### ISSUE THREAD

**Issue by snycc15** [running-elephant/datart#1147]
**你的功能要求与某个问题相关吗？**
清晰简洁地描述这个问题
例如表格无法设置列宽度、固定列后左右拉动会存在单元格内容重叠等
**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
1. 列宽设置 beta.3 版本已在条件样式中支持
2. 当固定列出现内容重叠时，设置表体背景色可以解决
