### ISSUE TITLE
仪表盘，通过控制器控制图表的显示和隐藏

### ISSUE THREAD

**Issue by dxdingdu** [running-elephant/datart#1154]
如题。
参考控制器的“是否显示”，在图表上增加类似的功能

**Comment by scottsut** [comment]
你的标题和正文描述是完全不同的两个需求，请确认到底想要哪个功能，最好能辅以业务场景描述。

**Comment by dxdingdu** [comment]
<img width="761" alt="WX20220411-131143@2x" src="https://user-images.githubusercontent.com/5936210/162669146-3d4186a0-38fa-4fed-85d1-8fc26bd2cb54.png">
如标题所说，以上面的报表为例，当控制器“是否赠送”选择“不含赠送”时，隐藏下方的列表；选择“含赠送”时，显示下方列表。

正文描述的是该需求期望的实现方式，如下图，控制器可以设置按其他控制器的取值来控制显示。
<img width="574" alt="image" src="https://user-images.githubusercontent.com/5936210/162669353-258f7192-38c2-4072-bd37-f7c4830c1f9f.png">

**Comment by scottsut** [comment]
这种通过控制器来显示/隐藏图表，对应的具体业务场景是什么样的？

**Comment by dxdingdu** [comment]
就是上面的示例，当控制器“是否赠送”选择“不含赠送”时，隐藏下方的列表；选择“含赠送”时，显示下方列表。

**Comment by dxdingdu** [comment]
还有一个需求是切换控制器选项，分别展示不同的列表和折线图

**Comment by scottsut** [comment]
> 就是上面的示例，当控制器“是否赠送”选择“不含赠送”时，隐藏下方的列表；选择“含赠送”时，显示下方列表。

你这是描述交互行为，不是说明业务场景。我想知道使用控制器显示/隐藏图表有什么具体意义？用户什么情况下会使用这个功能？

**Comment by xieliuduo** [comment]
的确是一种 场景。我们考虑未来每个组件 都有一个 visible 属性。这个属性可以依赖用户的配置，或者绑定和其他组件的交互逻辑。但这个还在 草案阶段。 如果针对这个 ，你们有很多的实践或者使用场景 可以在这里更多的讨论 或者给出建议，以帮助更好的推进这个 项目

**Comment by dxdingdu** [comment]
> 的确是一种 场景。我们考虑未来每个组件 都有一个 visible 属性。这个属性可以依赖用户的配置，或者绑定和其他组件的交互逻辑。但这个还在 草案阶段。 如果针对这个 ，你们有很多的实践或者使用场景 可以在这里更多的讨论 或者给出建议，以帮助更好的推进这个 项目 @dxdingdu

感谢！
