### ISSUE TITLE
希望容器中tab可以改变顺序、拖进容器的tab可以拖出。

### ISSUE THREAD

**Issue by guo81** [running-elephant/datart#1156]
设置好tab顺序后，当需要调整tab顺序时，希望能通过拖拽或其他方式调整tab顺序。当前拖进后未发现可以改变顺序的方式。
也希望当有需求时，可以将之前由私有图表拖进容器形成的tab拖出，恢复为私有图表。

**Comment by xieliuduo** [comment]
- 希望能通过拖拽或其他方式调整tab顺序 。这个后续会支持 不过优先级不高。
- 将之前由私有图表拖进容器形成的tab拖出，恢复为私有图表   。这个目前点击 x 号 是可以 将图表从tab容器移出来 恢复为 单个组件的 
- @guo81

**Comment by Cuiyansong** [comment]
当前PR将会关闭，如有问题请留言。
