### ISSUE TITLE
定时任务会残留很多Chrome进程

### ISSUE THREAD

**Issue by doublelongs** [running-elephant/datart#1157]
**Datart Version**
GitHub dev.

**Describe the bug**
定时任务会残留很多Chrome进程.

**To Reproduce**

**Expected behavior**

**Screenshots**
![00ac32267b564a475756c1650ea9f78](https://user-images.githubusercontent.com/97596716/162656315-94c7c986-db73-4298-9125-bad2e3c62c3e.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by tianlu-root** [comment]
#1160
