### ISSUE TITLE
Question: How to start datart with SSL?

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1172]
Can someone share how to run datart with SSL and access on browser using https protocol?

**Comment by clementchong** [comment]
I think Tomcat is embedded, where can I find tomcat server.xml? or possible to add configuration to datart.conf or application.yml for ssl to kick in?

**Comment by xiaohuangdou666** [comment]
You can try to configure the relevant parameters of ssl (sever.ssl.~) in datart.conf or profiles/application-config.yml. 
For springboot SSL configurations, you can query the official springboot documentation (https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.server)

**Comment by clementchong** [comment]
I managed to start in https mode. Would submit a pull request for review.

![image](https://user-images.githubusercontent.com/100477931/163351067-505eefda-0e3e-4153-9027-0864fe484bf9.png)

**Comment by clementchong** [comment]
Submitted PR

**Comment by clementchong** [comment]
PR approved and merged. Hence closing.
