### ISSUE TITLE
Question: Is chrome webdriver needed for normal use of datart?

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1175]
The datart.conf has setting for webdriver. What is the purpose if I only use datart for normal reporting/visualization. I read selenium is for automated browser testing, how is this required for normal use of datart?

**Comment by clementchong** [comment]
I see. if I only send by excel, then selenium is not needed?

**Comment by scottsut** [comment]
> I see. if I only send by excel, then selenium is not needed?

Yes.

**Comment by clementchong** [comment]
Thank you!
