### ISSUE TITLE
File data source is not working

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1177]
**Datart Version**
1.0b2 demo site

**Describe the bug**
Create new file source but no form is displayed. Click save and there is error.

**To Reproduce**
1. Go to 'Sources.'
2. Click on '+' and choose File.
3. Click Save

**Expected behavior**
There should be a form to specify the file details or upload a file.

**Screenshots**
![image](https://user-images.githubusercontent.com/100477931/163139464-601fa5bb-5176-41cb-8212-82a0488695d7.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by q1139168548** [comment]
Today, I also encountered this problem, which is the same when using HTTP data source. You can try to save first, so that there will be an edit button on the page.

**Comment by clementchong** [comment]
> Today, I also encountered this problem, which is the same when using HTTP data source. You can try to save first, so that there will be an edit button on the page.

Thank you for sharing. The behavior is different from JDBC, not sure if it is done intentionally. I recall it is not like this in 1.0.0b1
