### ISSUE TITLE
Performance lag rendering wide table

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1180]
**Datart Version**
1.0.0b2

**Describe the bug**
Testing with 1 big and 1 small tables. Both has same data in first column, total 200 rows. Big table has 150 columns, small table has 20 columns. All other columns no data.

Paging the data on dashboard shows much slower performance for big table. Understand more rendering work to be done but can performance be improved? In edit big table dashboard, the screen can freeze and no response.

This is unlikely a bug, maybe performance improvement. Let me know if there is any setting I can set. Aggregation is turned off when creating the visualization.

Queries generated:

SELECT `DATART_VTABLE`.`Col_1` AS `Col_1`, `DATART_VTABLE`.`Col_2` AS `Col_2`, `DATART_VTABLE`.`Col_3` AS `Col_3`, `DATART_VTABLE`.`Col_4` AS `Col_4`, `DATART_VTABLE`.`Col_5` AS `Col_5`, `DATART_VTABLE`.`Col_6` AS `Col_6`, `DATART_VTABLE`.`Col_7` AS `Col_7`, `DATART_VTABLE`.`Col_8` AS `Col_8`, `DATART_VTABLE`.`Col_9` AS `Col_9`, `DATART_VTABLE`.`Col_10` AS `Col_10`, `DATART_VTABLE`.`Col_11` AS `Col_11`, `DATART_VTABLE`.`Col_12` AS `Col_12`, `DATART_VTABLE`.`Col_13` AS `Col_13`, `DATART_VTABLE`.`Col_14` AS `Col_14`, `DATART_VTABLE`.`Col_15` AS `Col_15`, `DATART_VTABLE`.`Col_16` AS `Col_16`, `DATART_VTABLE`.`Col_17` AS `Col_17`, `DATART_VTABLE`.`Col_18` AS `Col_18`, `DATART_VTABLE`.`Col_19` AS `Col_19`, `DATART_VTABLE`.`Col_20` AS `Col_20` FROM ( select * from adm.T_SMALL ) AS `DATART_VTABLE` LIMIT 100 OFFSET 0

SELECT `DATART_VTABLE`.`Col_1` AS `Col_1`, `DATART_VTABLE`.`Col_2` AS `Col_2`, `DATART_VTABLE`.`Col_3` AS `Col_3`, `DATART_VTABLE`.`Col_4` AS `Col_4`, `DATART_VTABLE`.`Col_5` AS `Col_5`, `DATART_VTABLE`.`Col_6` AS `Col_6`, `DATART_VTABLE`.`Col_7` AS `Col_7`, `DATART_VTABLE`.`Col_8` AS `Col_8`, `DATART_VTABLE`.`Col_9` AS `Col_9`, `DATART_VTABLE`.`Col_10` AS `Col_10`, `DATART_VTABLE`.`Col_11` AS `Col_11`, `DATART_VTABLE`.`Col_12` AS `Col_12`, `DATART_VTABLE`.`Col_13` AS `Col_13`, `DATART_VTABLE`.`Col_14` AS `Col_14`, `DATART_VTABLE`.`Col_15` AS `Col_15`, `DATART_VTABLE`.`Col_16` AS `Col_16`, `DATART_VTABLE`.`Col_17` AS `Col_17`, `DATART_VTABLE`.`Col_18` AS `Col_18`, `DATART_VTABLE`.`Col_19` AS `Col_19`, `DATART_VTABLE`.`Col_20` AS `Col_20`, `DATART_VTABLE`.`Col_21` AS `Col_21`, `DATART_VTABLE`.`Col_22` AS `Col_22`, `DATART_VTABLE`.`Col_23` AS `Col_23`, `DATART_VTABLE`.`Col_24` AS `Col_24`, `DATART_VTABLE`.`Col_25` AS `Col_25`, `DATART_VTABLE`.`Col_26` AS `Col_26`, `DATART_VTABLE`.`Col_27` AS `Col_27`, `DATART_VTABLE`.`Col_28` AS `Col_28`, `DATART_VTABLE`.`Col_29` AS `Col_29`, `DATART_VTABLE`.`Col_30` AS `Col_30`, `DATART_VTABLE`.`Col_31` AS `Col_31`, `DATART_VTABLE`.`Col_32` AS `Col_32`, `DATART_VTABLE`.`Col_33` AS `Col_33`, `DATART_VTABLE`.`Col_34` AS `Col_34`, `DATART_VTABLE`.`Col_35` AS `Col_35`, `DATART_VTABLE`.`Col_36` AS `Col_36`, `DATART_VTABLE`.`Col_37` AS `Col_37`, `DATART_VTABLE`.`Col_38` AS `Col_38`, `DATART_VTABLE`.`Col_39` AS `Col_39`, `DATART_VTABLE`.`Col_40` AS `Col_40`, `DATART_VTABLE`.`Col_41` AS `Col_41`, `DATART_VTABLE`.`Col_42` AS `Col_42`, `DATART_VTABLE`.`Col_43` AS `Col_43`, `DATART_VTABLE`.`Col_44` AS `Col_44`, `DATART_VTABLE`.`Col_45` AS `Col_45`, `DATART_VTABLE`.`Col_46` AS `Col_46`, `DATART_VTABLE`.`Col_47` AS `Col_47`, `DATART_VTABLE`.`Col_48` AS `Col_48`, `DATART_VTABLE`.`Col_49` AS `Col_49`, `DATART_VTABLE`.`Col_50` AS `Col_50`, `DATART_VTABLE`.`Col_51` AS `Col_51`, `DATART_VTABLE`.`Col_52` AS `Col_52`, `DATART_VTABLE`.`Col_53` AS `Col_53`, `DATART_VTABLE`.`Col_54` AS `Col_54`, `DATART_VTABLE`.`Col_55` AS `Col_55`, `DATART_VTABLE`.`Col_56` AS `Col_56`, `DATART_VTABLE`.`Col_57` AS `Col_57`, `DATART_VTABLE`.`Col_58` AS `Col_58`, `DATART_VTABLE`.`Col_59` AS `Col_59`, `DATART_VTABLE`.`Col_60` AS `Col_60`, `DATART_VTABLE`.`Col_61` AS `Col_61`, `DATART_VTABLE`.`Col_62` AS `Col_62`, `DATART_VTABLE`.`Col_63` AS `Col_63`, `DATART_VTABLE`.`Col_64` AS `Col_64`, `DATART_VTABLE`.`Col_65` AS `Col_65`, `DATART_VTABLE`.`Col_66` AS `Col_66`, `DATART_VTABLE`.`Col_67` AS `Col_67`, `DATART_VTABLE`.`Col_68` AS `Col_68`, `DATART_VTABLE`.`Col_69` AS `Col_69`, `DATART_VTABLE`.`Col_70` AS `Col_70`, `DATART_VTABLE`.`Col_71` AS `Col_71`, `DATART_VTABLE`.`Col_72` AS `Col_72`, `DATART_VTABLE`.`Col_73` AS `Col_73`, `DATART_VTABLE`.`Col_74` AS `Col_74`, `DATART_VTABLE`.`Col_75` AS `Col_75`, `DATART_VTABLE`.`Col_76` AS `Col_76`, `DATART_VTABLE`.`Col_77` AS `Col_77`, `DATART_VTABLE`.`Col_78` AS `Col_78`, `DATART_VTABLE`.`Col_79` AS `Col_79`, `DATART_VTABLE`.`Col_80` AS `Col_80`, `DATART_VTABLE`.`Col_81` AS `Col_81`, `DATART_VTABLE`.`Col_82` AS `Col_82`, `DATART_VTABLE`.`Col_83` AS `Col_83`, `DATART_VTABLE`.`Col_84` AS `Col_84`, `DATART_VTABLE`.`Col_85` AS `Col_85`, `DATART_VTABLE`.`Col_86` AS `Col_86`, `DATART_VTABLE`.`Col_87` AS `Col_87`, `DATART_VTABLE`.`Col_88` AS `Col_88`, `DATART_VTABLE`.`Col_89` AS `Col_89`, `DATART_VTABLE`.`Col_90` AS `Col_90`, `DATART_VTABLE`.`Col_91` AS `Col_91`, `DATART_VTABLE`.`Col_92` AS `Col_92`, `DATART_VTABLE`.`Col_93` AS `Col_93`, `DATART_VTABLE`.`Col_94` AS `Col_94`, `DATART_VTABLE`.`Col_95` AS `Col_95`, `DATART_VTABLE`.`Col_96` AS `Col_96`, `DATART_VTABLE`.`Col_97` AS `Col_97`, `DATART_VTABLE`.`Col_98` AS `Col_98`, `DATART_VTABLE`.`Col_99` AS `Col_99`, `DATART_VTABLE`.`Col_100` AS `Col_100`, `DATART_VTABLE`.`Col_101` AS `Col_101`, `DATART_VTABLE`.`Col_102` AS `Col_102`, `DATART_VTABLE`.`Col_103` AS `Col_103`, `DATART_VTABLE`.`Col_104` AS `Col_104`, `DATART_VTABLE`.`Col_105` AS `Col_105`, `DATART_VTABLE`.`Col_106` AS `Col_106`, `DATART_VTABLE`.`Col_107` AS `Col_107`, `DATART_VTABLE`.`Col_108` AS `Col_108`, `DATART_VTABLE`.`Col_109` AS `Col_109`, `DATART_VTABLE`.`Col_110` AS `Col_110`, `DATART_VTABLE`.`Col_111` AS `Col_111`, `DATART_VTABLE`.`Col_112` AS `Col_112`, `DATART_VTABLE`.`Col_113` AS `Col_113`, `DATART_VTABLE`.`Col_114` AS `Col_114`, `DATART_VTABLE`.`Col_115` AS `Col_115`, `DATART_VTABLE`.`Col_116` AS `Col_116`, `DATART_VTABLE`.`Col_117` AS `Col_117`, `DATART_VTABLE`.`Col_118` AS `Col_118`, `DATART_VTABLE`.`Col_119` AS `Col_119`, `DATART_VTABLE`.`Col_120` AS `Col_120`, `DATART_VTABLE`.`Col_121` AS `Col_121`, `DATART_VTABLE`.`Col_122` AS `Col_122`, `DATART_VTABLE`.`Col_123` AS `Col_123`, `DATART_VTABLE`.`Col_124` AS `Col_124`, `DATART_VTABLE`.`Col_125` AS `Col_125`, `DATART_VTABLE`.`Col_126` AS `Col_126`, `DATART_VTABLE`.`Col_127` AS `Col_127`, `DATART_VTABLE`.`Col_128` AS `Col_128`, `DATART_VTABLE`.`Col_129` AS `Col_129`, `DATART_VTABLE`.`Col_130` AS `Col_130`, `DATART_VTABLE`.`Col_131` AS `Col_131`, `DATART_VTABLE`.`Col_132` AS `Col_132`, `DATART_VTABLE`.`Col_133` AS `Col_133`, `DATART_VTABLE`.`Col_134` AS `Col_134`, `DATART_VTABLE`.`Col_135` AS `Col_135`, `DATART_VTABLE`.`Col_136` AS `Col_136`, `DATART_VTABLE`.`Col_137` AS `Col_137`, `DATART_VTABLE`.`Col_138` AS `Col_138`, `DATART_VTABLE`.`Col_139` AS `Col_139`, `DATART_VTABLE`.`Col_140` AS `Col_140`, `DATART_VTABLE`.`Col_141` AS `Col_141`, `DATART_VTABLE`.`Col_142` AS `Col_142`, `DATART_VTABLE`.`Col_143` AS `Col_143`, `DATART_VTABLE`.`Col_144` AS `Col_144`, `DATART_VTABLE`.`Col_145` AS `Col_145`, `DATART_VTABLE`.`Col_146` AS `Col_146`, `DATART_VTABLE`.`Col_147` AS `Col_147`, `DATART_VTABLE`.`Col_148` AS `Col_148`, `DATART_VTABLE`.`Col_149` AS `Col_149`, `DATART_VTABLE`.`Col_150` AS `Col_150` FROM ( select * from adm.t_big ) AS `DATART_VTABLE` LIMIT 100 OFFSET 0

Attached is the big_small_tables.txt script I used to create test tables.

**To Reproduce**

**Expected behavior**
Paging of data should be smooth even for wide tables.

**Screenshots**

![image](https://user-images.githubusercontent.com/100477931/163156116-e9804b0e-51bc-47d6-bbd3-7300f8930d5c.png)

![image](https://user-images.githubusercontent.com/100477931/163156226-f4b21130-4cf4-4871-8315-8afff88a1fce.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10] Windows 10
 - Source Database: [e.g. MySQL 8.0.26] 8.0.25
 - Browser: [e.g. chrome 94, safari 15] Chrome 100
[big_small_tables.txt](https://github.com/running-elephant/datart/files/8480465/big_small_tables.txt)

**Additional context**

**Comment by Cuiyansong** [comment]
Have you try a Pivot table to see if it is better? Some details is `Fen Zu` table which is original `Ant Design` table component without vertical columns and wide table optimization. The Pivot table is Antv/S2 component based on canvas, so it should be more better than pure `DOM` render. Let me know if better or not, thanks.

**Comment by clementchong** [comment]
Pivot table needs a metric. For testing,  I altered COL_150 to decimal. The report layout would be different from normal table. The metrics are restricted to end of tables. The performance did not feel better. In dashboard design mode, my browser also frozen few times and it says page unresponsive.

![image](https://user-images.githubusercontent.com/100477931/163325075-c7c35c79-aeb9-409f-8719-e3db4198a82c.png)

![image](https://user-images.githubusercontent.com/100477931/163325227-2bd68e65-aeed-4ca6-8e56-df0aea18ad14.png)

**Comment by Cuiyansong** [comment]
Thanks! That's need more time to dig into the code in dashboard, but before we will make a large wide table in `Chart Editor` first. We will apply this question ASAP.

**Comment by clementchong** [comment]
Thank you! I just want to highlight issues as I encounter them. Long run should make this a better product. Can't expect immediate fix.

**Comment by Cuiyansong** [comment]
For this table performance issue, we have some work to do:
- Reduce frequency of table drawing in datart events(#1206) and board drawing events
- For Wide table bad performance issue, it is better to use Table based on canvas, such as `AntV/S2` lib, but now we have no resource on it to replace `FenZu` table for now. Maybe you can try to make a plugin chart to use it by introduce `S2` table.

More information about plugin chart, please see links below.
[Plugin_Chart_Document](https://running-elephant.github.io/datart-docs/docs/chart_plugin.html)
[Chart_Extension_Demo_Repository](https://github.com/running-elephant/datart-extension-charts)

**Comment by clementchong** [comment]
Thank you! I would try but it looks too difficult for me as I am not developer background.

**Comment by clementchong** [comment]
How can I tell which charts today in datart is using Ant lib? I can see PivotSheetChart has AntVS2Wrapper.tsx and BasicTableChart has AntdTableWrapper.tsx

**Comment by scottsut** [comment]
Yes, there are only `Table` and `PivotSheet` so far.

**Comment by Cuiyansong** [comment]
This issue will be closed, if there is any questions, pls let us know.
