### ISSUE TITLE
Question: Themes and styling

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1222]
There are some css and images in the source code. Is there a guide or some documentation to show where and what each css item is for? Thank you.

**Comment by clementchong** [comment]
Can possibly leverage material design?

https://material.io/design

**Comment by scottsut** [comment]
We didn't follow a specified design system, but we have our own design tokens. Refer to [StyleConstants](https://github.com/running-elephant/datart/blob/master/frontend/src/styles/StyleConstants.ts)

**Comment by clementchong** [comment]
> We didn't follow a specified design system, but we have our own design tokens. Refer to [StyleConstants](https://github.com/running-elephant/datart/blob/master/frontend/src/styles/StyleConstants.ts)

Thank you, would have a look!

**Comment by clementchong** [comment]
The StyleConstants list looks too short to cover all the styling. It is also not too clear where changes for each one of them would affect.

**Comment by scottsut** [comment]
In fact, because we use `ant-design` as the base component library, and antd has its own design system, it is difficult for us to manage all the styles with our own design rules. A lot of code needs to be compatible with `ant-design`'s style.

**Comment by clementchong** [comment]
ok noted. thank you!
