### ISSUE TITLE
Question: Disabling user registration

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1245]
Thank you for providing this option in 1.0.0b3. If we disable it, should the registration link on login page get hidden? The setting is hardcoded to true in application-config.yml. I tried setting to false but the link still appears.

How should it work?

![image](https://user-images.githubusercontent.com/100477931/164882720-a355561f-c860-4c65-b2a0-5e84a7c4b669.png)

**Comment by scottsut** [comment]
Set `datart.user.register` in `datart.conf` will works.

**Comment by clementchong** [comment]
> Set `datart.user.register` in `datart.conf` will works.

Yes, setting value to false in datart.conf works. Why is the datart.user.register hardcoded to true in application-config.yml and yet not used?

**Comment by scottsut** [comment]
> Yes, setting value to false in datart.conf works. Why is the datart.user.register hardcoded to true in application-config.yml and yet not used?

This property is indeed prone to ambiguity, we will optimize it later

**Comment by clementchong** [comment]
Thank you for clarification!
