### ISSUE TITLE
Question: Switching to team mode

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1246]
My environment from 1.0.0b2 has 2 users - 1 writer who creates reports and dashboard and 1 reader to only view reports and dashboard. Due to 1.0.0b2 design, each user has its organization. My reader account has nothing is its organization. Reader is invited into writer's organization to access the reports and dashboards.

1) If I want to switch to team mode without setup access control again, what is the recommend way to do it?

2) My writer account is already in datart database, do I still need to configure its username/password in datart.conf?

**Comment by scottsut** [comment]
We do not recommend that you forcefully switch to team mode in this situation. Forcibly deleting database data may cause irreversible problems, so my suggestion is: 

>Deploy a new datart instance, use team mode there, and migrate the visualization resources over there.

If you think this is cumbersome, that's okay, we will provide features to help migrate visualization resources in next release.

**Comment by clementchong** [comment]
ok thank you for the clarification!
