### ISSUE TITLE
Question: Dashboard zoom

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1248]
With reference to 1.0.0b3, may I know what is the condition for zoom function to appear in dasboard? The mouseover text is hardcoded to chinese as well in frontend/src/app/pages/DashboardPage/pages/Board/FreeDashboard/ZoomControl.tsx.

![image](https://user-images.githubusercontent.com/100477931/164968009-ea511d63-0a49-4d58-8fc2-6daf7a90b28f.png)

When adding i18n support, I think the Zoom In and Out mouseover label should be opposite from the onClick event. My understanding of Zoom In is the object would be bigger and Zoom Out means the object would be smaller.

![image](https://user-images.githubusercontent.com/100477931/164968057-53a0e3f6-2a3c-4cc6-8c9b-711fea834b31.png)

**Comment by xieliuduo** [comment]
Zoom In is the object would be bigger and Zoom Out means the object would be smaller.  
---

you  are right ,it is my mistake 😅

**Comment by clementchong** [comment]
The i18n support for this zoom mouseover label is addressed in https://github.com/running-elephant/datart/pull/1279
