### ISSUE TITLE
Question: Recommended way to connect to MongoDB

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1256]
Hello.. I tried connecting to MongoDB but not successful so far. I recall Davinci has MongoDB connectivity out-of-the-box. As I dont see specific guide here and online search, just want to ask if there is a recommended way to do it properly.

I also tried follow https://www.mongodb.com/docs/bi-connector/master/installation/ but unable to connect so far.

**Comment by clementchong** [comment]
Ok, would try it out. Thank you!

**Comment by clementchong** [comment]
Looks like it would work! I was able to establish connection to MongoDB and also query using SQL aginst sample DB from MongoDB https://www.mongodb.com/docs/atlas/sample-data/sample-analytics/#std-label-sample-analytics

From MongoDB Compass:

![Screenshot from 2022-04-29 20-24-13](https://user-images.githubusercontent.com/100477931/165944656-eb9ae4ac-3e41-402a-adca-320f653eba0b.png)

From Datart:

![image](https://user-images.githubusercontent.com/100477931/165944457-d79b4ad5-81ed-4df5-a5e4-d144f8fc519d.png)

![image](https://user-images.githubusercontent.com/100477931/165942172-53b4d66d-54e2-4377-ab03-b1c27db168e7.png)

Output of SELECT * shows empty page even filter for a single record. This is likely due to object or array data in MongoDB.

![image](https://user-images.githubusercontent.com/100477931/165942392-eb1e12f4-4af8-4fc4-bf30-5b7670b83414.png)

**Comment by clementchong** [comment]
> Um...just support array as query result.

Sorry, don't understand. Any example?

**Comment by scottsut** [comment]
You can open the browser console to see what error is causing the page to crash.

**Comment by clementchong** [comment]
ok, I have the below error in browser console.

![image](https://user-images.githubusercontent.com/100477931/166130832-3bb32c1d-6c69-4721-8169-17f24846f720.png)

The link from the message is https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7Bdate%2C%20timestamp%7D

![image](https://user-images.githubusercontent.com/100477931/166130859-7c36d920-fc89-44d6-9b54-4653b5e44e38.png)

**Comment by scottsut** [comment]
I guess this is because querying mongodb returns object data instead of array, resulting in an exception in preview table rendering.

**Comment by scottsut** [comment]
This is a difficult problem to solve, if the database stores data in a document object structure, datart will not be able to handle query results properly. Query result array with schema are suitable for analysis and mapping due to their flat structure, but object...there is no general way to deal with them.

**Comment by clementchong** [comment]
Yes understand. I didn't get chance to explore DaVinci mongodb connection. Do you know if it has same limitations? Else how it do differently?

**Comment by scottsut** [comment]
> Yes understand. I didn't get chance to explore DaVinci mongodb connection. Do you know if it has same limitations? Else how it do differently?

Yes, it's same.

**Comment by clementchong** [comment]
Ok noted, thank you!

**Comment by AndrewOYLK** [comment]
How can I connect MongoDB by data source? I have no idea to set it
