### ISSUE TITLE
Question: Dashboard needs explicit view permission to work?

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1262]
I have a dashboard with few vizs. These vizs are built on top of data views in datart. When I publish the dashboard and grant to a user role, the user see error message that view permission is not granted. I need to allow view permision on view for dashboard to use.

This way, the user has read access to the view and SQL in datart. Is it possible to only allow "use" view permission without exposing the view itself?

**Comment by scottsut** [comment]
We separate viz and view to manage permissions to ensure absolute data access security, but this also brings the tedious operation. We plan to add a shortcut action, which can also grant access permissions to its associated view when authorizing viz. The switch of this shortcut action may be in the organization settings, and the organization owner can choose whether to enable it or not.

**Comment by clementchong** [comment]
> We separate viz and view to manage permissions to ensure absolute data access security, but this also brings the tedious operation. We plan to add a shortcut action, which can also grant access permissions to its associated view when authorizing viz. The switch of this shortcut action may be in the organization settings, and the organization owner can choose whether to enable it or not.

Ok, sounds like it may be a single on/off master switch rather than at each view level. Still looking forward to try it out. Thank you!

**Comment by clementchong** [comment]
It looks like the current version can support this. I tested with below setting and found the users can access the vizs without exposing the views and data source.

![image](https://user-images.githubusercontent.com/100477931/167368704-5139002a-5ea5-499e-8a71-5816bfcd6e9d.png)

**Comment by clementchong** [comment]
If this understanding is as expected based on product design, then we can close this topic.

**Comment by scottsut** [comment]
> It looks like the current version can support this. I tested with below setting and found the users can access the vizs without exposing the views and data source.
> 
> ![image](https://user-images.githubusercontent.com/100477931/167368704-5139002a-5ea5-499e-8a71-5816bfcd6e9d.png)

Looks like I misunderstood your question. 😂

Yes, it works.

**Comment by clementchong** [comment]
👍 thank you!
