### ISSUE TITLE
查询结果中包含大点数字会默认将最后一位改成0

### ISSUE THREAD

**Issue by launch110** [running-elephant/datart#1266]
**Datart Version**
The version of `datart` you using.
1.0.0-beta.3

**Describe the bug**
存储数据库: mysql8 , 数据类型 bigint unsigned ,存储的值为16509424652025690001 
实际查询出来显示的是16509424652025690000 (末位由1变成0）

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by scottsut** [comment]
长整型在浏览器中会丢失精度，这个问题建议自行处理，如果要展示长整型数据，将其在 SQL 中转换为字符

https://blog.csdn.net/weixin_43883917/article/details/121581377
https://blog.csdn.net/qq_39195859/article/details/122543200

**Comment by launch110** [comment]
之前是用davinci的SQL如果要移到datart，还是全部改下SQL，类型这样转换cast(a.id as char) ,其它软件也没有发生这样问题(navicat),其它方面还未确定有无影响，希望团队后续优化下，增加工作量，谢谢。

**Comment by scottsut** [comment]
> 之前是用davinci的SQL如果要移到datart，还是全部改下SQL，类型这样转换cast(a.id as char) ,其它软件也没有发生这样问题(navicat),其它方面还未确定有无影响，希望团队后续优化下，增加工作量，谢谢。

你应该给 chrome 团队提 issue，让他们解决长整型丢失精度的问题

<img width="286" alt="image" src="https://user-images.githubusercontent.com/4098913/165439060-ae0eb925-e4b3-48e6-a47e-e3abf8c312c4.png">
