### ISSUE TITLE
关于仪表板的控制器及联动设置替换图表组件初始筛选条件特性

### ISSUE THREAD

**Issue by heropoet** [running-elephant/datart#1268]
**你的功能要求与某个问题相关吗？**
在beta.3之前的版本中，设置了初始筛选条件图表组件在引入仪表板后，若仪表板使用相同字段触发筛选及联动后，会覆盖掉图表内的筛选条件，但在beta.3中，这一特性修改为在初始条件的基础上再加一层仪表板的筛选或联动条件
在需要设置默认筛选，并且需要仪表盘的筛选及联动的场景中，带来一些不便，具体如下：
1）筛选器场景：需要删除图表原有的筛选条件，并设置仪表板筛选器的默认值来实现
2）联动设置场景：无法设置联动目标图表的默认筛选条件

**形容一下你想要的解决方案**
希望可以保留原有替换图表内筛选条件的特性，或增加自定义选项等其它方式来实现以上的应用需求

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by xieliuduo** [comment]
1. "在需要设置默认筛选，并且需要仪表盘的筛选及联动的场景中，带来一些不便"
 关于这一点 我认为是之前只用习惯造成的，对beta3新版本会有不适应的过程。如果你的图表需要默认筛选 并且需要在仪表盘展示 那么你应该在仪表板控制器里设置好默认值。

2.在新的设计理念里我们让一些概念更清晰了 。有一些其他BI 产品是没有独立图表的。都必须在仪表板上创建图表。 而我们设计里了 <dataChart> 这个独立可以分享，交互存在的这个概念。就是它本身是一个完整的个体可以独立出来。它可以单独独立出现。本身自己就是有它自己的业务意义。只不过同时它可以方便的被"引入"到一个仪表板上做二次创作。那么我认为 仪表板就不应该删掉图表本身的筛选提条件，只能在此基础上加筛选条件。从而在图表展现的业务意义和数据集上面只做收敛缩小 而不做外扩放大。

我举个例子 假设有一个 独立的dataChart 《河北地区2012年度降雨量》 图表 被设计出来 。他背后的数据集可能包含全国所有省份的 1999年到2020年所有的数据。而其他省份和其他时间的数据是这个图表不想展示的。
它是独立存在的。 而后他被引入一个 仪表板。仪表板控制器关联了这个图表。 这时候 控制器的的值 我选择的是 ‘上海’，如果按之前的方案。那么这个《河北地区2012年度降雨量》这个图表 显示为上海2012年的降雨量了。这显然不合理。这个数范围已经超出了原来的数据边界了。 所以我认为仪表板应该在**引入**的数据图表限制的数据范围内做探索分析和展示。

按新版本的逻辑 《河北地区2012年度降雨量》图表和一个【省份=上海】的条件做合并 那么理应 得不出数据。

**Comment by heropoet** [comment]
> 1. "在需要设置默认筛选，并且需要仪表盘的筛选及联动的场景中，带来一些不便"
>    关于这一点 我认为是之前只用习惯造成的，对beta3新版本会有不适应的过程。如果你的图表需要默认筛选 并且需要在仪表盘展示 那么你应该在仪表板控制器里设置好默认值。
> 
> 2.在新的设计理念里我们让一些概念更清晰了 。有一些其他BI 产品是没有独立图表的。都必须在仪表板上创建图表。 而我们设计里了 这个独立可以分享，交互存在的这个概念。就是它本身是一个完整的个体可以独立出来。它可以单独独立出现。本身自己就是有它自己的业务意义。只不过同时它可以方便的被"引入"到一个仪表板上做二次创作。那么我认为 仪表板就不应该删掉图表本身的筛选提条件，只能在此基础上加筛选条 件。从而在图表展现的业务意义和数据集上面只做收敛缩小 而不做外扩放大。
> 
> 我举个例子 假设有一个 独立的dataChart 《河北地区2012年度降雨量》 图表 被设计出来 。他背后的数据集可能包含全国所有省份的 1999年到2020年所有的数据。而其他省份和其他时间的数据是这个图表不想展示的。 它是独立存在的。 而后他被引入一个 仪表板。仪表板控制器关联了这个图表。 这时候 控制器的的值 我选择的是 ‘上海’，如果按之前的方案。那么这个《河北地区2012年度降雨量》这个图表 显示为上海2012年的降雨量了。这显然不合理。这个数范围已经超出了原来的数据边界了。 所以我认为仪表板应该在**引入**的数据图表限制的数据范围内做探索分析和展示。
> 
> 按新版本的逻辑 《河北地区2012年度降雨量》图表和一个【省份=上海】的条件做合并 那么理应 得不出数据。

dy

**Comment by xieliuduo** [comment]
>  2）联动设置场景：无法设置联动目标图表的默认筛选条件 

确实。关于这一点 我们有必要在去优化一下功能。非常感谢

**Comment by Cuiyansong** [comment]
@heropoet Beta4的联动重新设计了，当前这个issue关闭，如有问题请留言。

**Comment by heropoet** [comment]
@Cuiyansong 请问现在如何实现为图表联动的对象设置默认条件呢？目前从功能交互没有看到相关的选项
