### ISSUE TITLE
可视化-文本控制器组件-前端页面按钮重叠

### ISSUE THREAD

**Issue by stupidxian** [running-elephant/datart#1272]
**Datart版本号**
beta3

**错误描述**
可视化页面，文本控制器组件，清空输入的快捷按钮，和同步数据的快捷按钮重叠。

**截图**
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/35219069/165889626-eca69333-ca04-406a-b259-603398f096b7.png">

**Comment by scottsut** [comment]
release 包已更新，如有需要可以重新下载替换
