### ISSUE TITLE
分享链接添加角色权限参数

### ISSUE THREAD

**Issue by 13233444055** [running-elephant/datart#1273]
**你的功能要求与某个问题相关吗？**
我们希望在分享仪表板链接的时候可以添加上角色权限参数，
这样我们就可以把这个仪表板嵌入我们的部分模块中，使用我们统一的角色权限传参来把分享后的仪表板角色权限控制

**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
不考虑这么做，有安全风险。集成分享页如果有鉴权需求可以集成授权分享，使用登录来鉴权
