### ISSUE TITLE
开发环境部署起来运行SQL查询的时候报错，SqlParserImpl cannot be resolved to a variable

### ISSUE THREAD

**Issue by github512** [running-elephant/datart#1278]
datart 版本号---1.0.0-beta.3

创建视图运行SQL语句做基本查询的时候报错：
Handler dispatch failed; nested exception is java.lang.Error: Unresolved compilation problem: SqlParserImpl cannot be resolved to a variable

![erorr](https://user-images.githubusercontent.com/29230923/166193727-9597322c-2b64-4e3d-8c81-f39858ab8ae1.png)

**Comment by xiaohuangdou666** [comment]
开发环境 SqlParserImpl类 需执行maven编译后生成，检查一下源码是否有修改
