### ISSUE TITLE
widget style配置更新 视图无法即时反馈

### ISSUE THREAD

**Issue by TMBigGroup** [running-elephant/datart#1281]
**Datart Version**
beta3

**Describe the bug**
1.新建widget 进行条件格式
<img width="1060" alt="图片" src="https://user-images.githubusercontent.com/95753485/166422249-5d77255f-206a-448d-9cb6-582f596956a8.png">
界面此时展示正常
<img width="1108" alt="图片" src="https://user-images.githubusercontent.com/95753485/166422371-607c794e-b953-4189-a28a-84bac5518570.png">

2.进入编辑widget
先删除原有的”区域“维度，再拖拽”区域“进来
<img width="986" alt="图片" src="https://user-images.githubusercontent.com/95753485/166423340-2519b83f-199b-4f64-9a97-8687ea844454.png">
这次给”上海“配置为”红色“背景色，界面展示依旧正常
<img width="1435" alt="图片" src="https://user-images.githubusercontent.com/95753485/166423375-9ba87af5-5f43-4447-b912-3478972836c5.png">

3.进行保存，发现vizs页面 只有数据变化了，style配置并不会同步更新
<img width="1439" alt="图片" src="https://user-images.githubusercontent.com/95753485/166423465-573f493c-757d-459b-be7e-cbb0b703974d.png">

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
Fixed By #1294
