### ISSUE TITLE
Question: Source reference column list sorting

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1288]
While working with wide tables, it can be difficult to locate the column names. Would it be better if column list is sorted in alphabetic order by default?

![image](https://user-images.githubusercontent.com/100477931/166947666-da607e48-288b-4775-a0f4-f2393f61fd28.png)

**Comment by xieliuduo** [comment]
Is a useful suggestion

**Comment by clementchong** [comment]
The database and table listing in source reference has the same issue.
