### ISSUE TITLE
能否在公开分享链接中增加下载数据表为Excel功能？

### ISSUE THREAD

**Issue by 732570672** [running-elephant/datart#1298]
**你的功能要求与某个问题相关吗？**
我们是在集成datart到业务系统中，用于创建业务报表功能，经常性遇到用户需要在查看报表的同时，要求能同时下载数据表为Excel。

**形容一下你想要的解决方案**
目前datart在后台有下载Excel功能，但实际应用中，用户是只能访问到分享链接的，我们希望在分享的链接页面中，表格组件能有一个下载 Excel的按钮，用于下载表格数据为Excel文件

**描述一下你考虑过的备选方案**
目前没有考虑备选方案，作者开发的这个项目非常nice！

**其他内容**
有关这个功能要求的任意其他内容或截图
![image](https://user-images.githubusercontent.com/34471177/167246763-4f532e6d-7d1c-4bf6-97ec-10bf1866fb4d.png)

![image](https://user-images.githubusercontent.com/34471177/167246699-a4b07ae1-c243-4f9f-bbc2-82e8cc384d22.png)

**Comment by scottsut** [comment]
暂不考虑。首先下载权限在应用中是受控的，在公共分享页中无法控制，所以分享页不应该包含下载功能；另外我们后续会优化主应用的集成体验，方便用户直接将主应用嵌入到业务系统中。
