### ISSUE TITLE
能否增加 '数据视图' & 可视化 页面的 tag的右键关闭菜单

### ISSUE THREAD

**Issue by zhu-mingye** [running-elephant/datart#1299]
**你的功能要求与某个问题相关吗？**
当打开多个tag标签 需要关闭时 只能一个一个的点  

**形容一下你想要的解决方案**
增加 右键菜单 
  1. 关闭当前
  2. 关闭其他
  3. 关闭所有

**描述一下你考虑过的备选方案**

**其他内容**

**Comment by scottsut** [comment]
#1432
