### ISSUE TITLE
大屏开发

### ISSUE THREAD

**Issue by baymaxLove** [running-elephant/datart#1305]
在开发大屏或者是dashboard的时候希望有一个预览按钮 可以打开新页面预览当前开发所展示效果

**Comment by scottsut** [comment]
Related to #1138

**Comment by Cuiyansong** [comment]
设计模式下预览的方式是仪表板或者图表保存之后的展示页面（预览界面），如果预览界面宽度不够的话，会改进左侧面板的折叠功能，开发模式下的全屏预览会并不是完全需要，或者说在功能设计上有冲突而浪费时间；#1138分享页全屏预览也是伪需求，对于标题的隐藏和现实，可以在设计时增强即达到功能；
