### ISSUE TITLE
数据视图中数据源信息无法加载

### ISSUE THREAD

**Issue by RunningXuan** [running-elephant/datart#1316]
![image](https://user-images.githubusercontent.com/47099551/167773653-0458f0ac-ab06-4cad-a2db-8cd79c95a4b9.png)

**Comment by scottsut** [comment]
在数据源页面点击一下右上角的“同步数据库模式”按钮，成功后会显示最后同步时间，然后再刷新一下页面看看

**Comment by Cuiyansong** [comment]
感谢贡献，如有问题请留言。
