### ISSUE TITLE
堆叠柱状图，跳转传指标名称、维度值问题

### ISSUE THREAD

**Issue by ParkerJX** [running-elephant/datart#132]
**Describe the bug**

- 堆叠柱状图，设置跳转。预想是传纬度值过去，实际上是传指标名称过去了。是否考虑支持自定义传什么值到目标图表

**To Reproduce**
<img width="766" alt="image" src="https://user-images.githubusercontent.com/15976650/139370836-a382c2dc-15d7-4f0a-902e-09d5db67a510.png">
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/15976650/139370870-3d47e0fc-0532-4cf3-bf47-f4519845e14d.png">

> 实际上是想要下面这个效果
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/15976650/139370952-1d602a9b-3f8b-4ba6-ae5f-6850616a5579.png">

**Expected behavior**

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94,]

**Additional context**

**Comment by scottsut** [comment]
传递的不是指标名称，是颜色维度值

**Comment by ParkerJX** [comment]
> 传递的不是指标名称，是颜色维度值
实际上，我并不是想传颜色的维度值，其实是想传 X 轴的值。
比如我是想从 2019 年的沟通数据，下钻到 2019 年的月度数据报表

**Comment by scottsut** [comment]
> 实际上，我并不是想传颜色的维度值，其实是想传 X 轴的值。
> 比如我是想从 2019 年的沟通数据，下钻到 2019 年的月度数据报表

了解，这里问题我们会优化
