### ISSUE TITLE
希望能提供允许选择组织的图形化起始页

### ISSUE THREAD

**Issue by guo81** [running-elephant/datart#1324]
**你的功能要求与某个问题相关吗？**

在租户模式下，登录进入datart后，会直接进入某一固定组织，但实际组织可能有多个，因此难以快速定位并进入预期的组织
对不熟悉页面或新注册的人而言，问题尤为显著

**形容一下你想要的解决方案**

在租户模式下，希望能在登录后提供一个选择组织的界面，类似davinci那样的图形化的界面就很友好

**描述一下你考虑过的备选方案**

**其他内容**
![图片](https://user-images.githubusercontent.com/40499469/167868382-71e3b59f-da3d-4bf0-8916-e4f3900c89f2.png)

**Comment by scottsut** [comment]
如果没有多组织的使用需求，建议使用“团队模式”，可以避免组织切换带来的问题。在 beta.3 的 [release note](https://github.com/running-elephant/datart/releases/tag/1.0.0-beta.3) 页参考具体使用方式。

类似 davinci 的首页卡片视图不会回归，因为我们觉得对于关注报表的用户来说，登入进系统应该第一时间看到报表。而对于报表开发者，则不用过度担心，因为他们迟早需要对 datart 熟悉并掌握。
