### ISSUE TITLE
公共变量在SQL过滤时无效

### ISSUE THREAD

**Issue by ghostman-git** [running-elephant/datart#1331]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
![54d1fd1a078693c5a4e44098a9bcf69](https://user-images.githubusercontent.com/13376074/168010973-45bdd584-5e8e-43ad-82a2-42334215c058.png)
![5c4bcf89b97f2b84bc0fc0ebbd3e981](https://user-images.githubusercontent.com/13376074/168010999-c391cd75-c673-4faa-9a6f-da6525f8e0b6.png)
![image](https://user-images.githubusercontent.com/13376074/168011286-2110c2d0-0d7e-4c38-bfde-cab7e8f8795c.png)

$DATART_USER_USERNAME$ 在SQL where过滤不起作用

**Comment by scottsut** [comment]
先说明一下你截图中是组织拥有者，还是角色用户？

**Comment by ghostman-git** [comment]
> 先说明一下你截图中是组织拥有者，还是角色用户？

组织拥有者

图1、2是设计者。图3分享后设计者登录查看的。
我的理解，图1$DATART_USER_USERNAME$的值是"hxat"，图2应该只能查到LOGIN_NAME='hxat'的数据吧，然而查到的是所有的

**Comment by scottsut** [comment]
组织拥有者永远看到的是全量数据，权限变量只对普通角色用户生效，这个问题文档中有说明

<img width="783" alt="image" src="https://user-images.githubusercontent.com/4098913/168195150-6f7b7dc4-8a55-4cb1-bc6c-96aaa6273ce9.png">

**Comment by Cuiyansong** [comment]
感谢贡献，如有问题请留言。
