### ISSUE TITLE
控制器中多选下拉列表在仪表板中没有生效

### ISSUE THREAD

**Issue by yunfeng79** [running-elephant/datart#1334]
datart beta3版本
![image](https://user-images.githubusercontent.com/21050635/168037201-6af455ea-bea8-4228-87f9-c75da1bad149.png)

只加载初次的一列值，在改查询日期，重新查询，得到的多条数据。多选下拉列表中还是和第一次加载一样，没有加载最新的数据。

**Comment by scottsut** [comment]
使用方式不对，如果希望日期控制器改变多选下拉菜单的取值，请在日期控制器的配置界面关联多选下拉菜单、并指定关联字段/变量，来起到级联的作用。

**Comment by Cuiyansong** [comment]
感谢贡献，如有问题请留言。
