### ISSUE TITLE
非管理员账户新建计算字段出现validate function computed field failed

### ISSUE THREAD

**Issue by wbjsly** [running-elephant/datart#1346]
Dataer 版本： Beta3

操作步骤
1、非管理员点击开始分析，选择一个数据数据视图后，点击+号新增一个计算字段
2、按照规则设置好计算字段逻辑后出现validate function computed field failed
3、以上问题出现在非管理员账号，而管理员账号不会出现如上问题。

问题提示:
<img width="372" alt="image" src="https://user-images.githubusercontent.com/25900538/168560357-af27a74d-31b0-4981-b141-5cce12e1787c.png">

操作环境：MacOS Monterey V12.3.1
浏览器环境：Safari V15.4

@scottsut

**Comment by wbjsly** [comment]
> 没能成功复现这个情况，请提供更详细的内容，如计算字段语法、非管理员账户对可视化模块的具体资源权限，用来帮助还原场景

![image](https://user-images.githubusercontent.com/25900538/168706336-ffcd72d8-3d21-4bcb-8825-1d697a6826d7.png)
![image](https://user-images.githubusercontent.com/25900538/168706357-ba104183-d4ed-45b0-a1b5-c8ef6b367a9a.png)

**Comment by scottsut** [comment]
你打开浏览器控制台，把校验语法请求返回信息的 preview 界面截图一下。如果方便的话，还可以把所有返回的错误信息拷贝到一个文本文件里发出来

**Comment by wbjsly** [comment]
> 你打开浏览器控制台，把校验语法请求返回信息的 preview 界面截图一下。如果方便的话，还可以把所有返回的错误信息拷贝到一个文本文件里发出来

目前结论：已自行解决
解决方法：请管理员给非管理员用户开通对数据源的使用权限。

请关闭该Issue。

Thanks a lot!
