### ISSUE TITLE
故事板中有多个仪表盘时需要允许自定义仪表盘顺序，以方便大屏按照设置顺序展示。

### ISSUE THREAD

**Issue by wbjsly** [running-elephant/datart#1347]
Datart Version：Beta3

需求：
1、故事板中有多个仪表盘时需要允许自定义仪表盘顺序，以方便大屏按照设置顺序展示。
2、允许非管理员在故事板中增加仪表盘的权限。

<img width="164" alt="image" src="https://user-images.githubusercontent.com/25900538/168562197-2e9d6e72-5db0-486a-9cec-a684dc942efa.png">

**Comment by scottsut** [comment]
@tianlu-root 第二个问题是bug，普通账户拥有管理权限，但给故事版添加 page 时会报权限不足

**Comment by Plume3362** [comment]
@scottsut @xiaohuangdou666 这个问题并没有解决，当一个账号有多个角色时，必须所有角色都有创建权限才可以

**Comment by Plume3362** [comment]
![图片](https://user-images.githubusercontent.com/49897998/183879471-d00a3f30-e09f-4a07-9eb1-49144a87099a.png)
