### ISSUE TITLE
[控制器]-控制器内值样式无法控制

### ISSUE THREAD

**Issue by byc233518** [running-elephant/datart#1356]
**Datart版本号**
http://datart-demo.retech.cc/ 
Version: 1.0.0-beta.3

**错误描述**
目前控制器的样式设置只生效于 控制器的 label, 设置后值没有生效, 一直是黑色
例如: 文本输入框, 下拉选择框 如果背景是深色的, 就看不到输入或选择的内容了

**如何重现**
重现错误的步骤，例如：
1. 增加一个控制器;
2. 选择一个深色背景;
3. 调整控制器背景为透明;
4. 调整控制器字体颜色为白色;

**期望结果**
控制器中值的颜色也跟随设置改变成白色

**截图**
<img width="702" alt="image" src="https://user-images.githubusercontent.com/13425815/169179909-4aa78675-3f80-43e7-bc41-569e303a16a2.png">

**运行环境详情：(可选，取决于错误发生的具体位置)**
OS: MacOS 12.0.1 
浏览器: Chrome  101.0.4951.64（正式版本） (x86_64)

**其他内容**
无

**Comment by Cuiyansong** [comment]
目前标题的配色会同步已选择的选项字体颜色

**Comment by Cuiyansong** [comment]
#1545
