### ISSUE TITLE
拖拽表格会导致报错页面空白

### ISSUE THREAD

**Issue by bravekings** [running-elephant/datart#1357]
[**Datart版本号**
声明一下你正在使用的 `datart` 版本号]
http://datart-demo.retech.cc/ demo版本

**错误描述**
仪表板内的私有图表，若有表头合并的情况，多层级的合并（3个以上），进行拖拽时会出现页面空白的现象

**如何重现**
重现错误的步骤，例如：
1. 到新建仪表板页面
2. 点击新建数据图表，普通table，表头合并的情况，多层级的合并（3个或以上）
3. 
![image](https://user-images.githubusercontent.com/46808184/169192730-153242bd-59d3-4855-ac6f-fa1b35e2e830.png)
4. 进行表头宽度拖拽
5. 页面出现空白
6. ![1652927952(1)](https://user-images.githubusercontent.com/46808184/169192620-20c27284-7bc7-4d23-b665-34d6705bcb3a.jpg)

**期望结果**
清晰简洁地描述你期望的结果是什么

**截图**

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: [例如 Windows 10]
- 数据源: [例如  MySQL 8.0.26]
- 浏览器: [例如 chrome 94, safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by francis-xjl** [comment]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/17879879/169289714-c3bd219b-eb33-40d0-9352-6c389eaf8cac.png">
我们也遇到了，求助。
