### ISSUE TITLE
Field search/filter in create viz page

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1362]
**Is your feature request related to a problem? Please describe.**
When creating a viz using a wide view, it can be difficult to locate the required field. 

![image](https://user-images.githubusercontent.com/100477931/169304754-1ea8932f-b151-44e4-8f5b-669d53d657a4.png)

**Describe the solution you'd like**
It would be helpful to include a search box to find/filter the fields for selection. Field list should also be sorted in alphabetical order by default.

**Describe alternatives you've considered**
Manual search which is not time effective.

**Additional context**

**Comment by scottsut** [comment]
This dropdown list allows searching.

**Comment by Cuiyansong** [comment]
Same as #1574 , we will tracking by 1574. Thanks for reporting, this pr will be closed.
