### ISSUE TITLE
非root用户无法启动

### ISSUE THREAD

**Issue by guodongym** [running-elephant/datart#1364]
**Datart Version**
datart-server-1.0.0-beta.3

**Describe the bug**
使用非root用户启动会报错
Error: Could not find or load main class datart.DatartServerApplication

换root用户之后正常

**Comment by scottsut** [comment]
系统账户权限问题，跟 datart 没有关系。

**Comment by guodongym** [comment]
> 系统账户权限问题，跟 datart 没有关系。

但是 davinci 是可以用那个非root正常启动的，而且这个用户也有sudo的权限

**Comment by guodongym** [comment]
source ~/.bashrc
改为 
sudo source ~/.bashrc   可以解决

**Comment by guodongym** [comment]
source ~/.bashrc
改为 
sudo source ~/.bashrc   可以解决

**Comment by guodongym** [comment]
@scottsut  可以参与贡献吗？ 

想参与贡献，但是readme里面的跳转连接不对，  **非常欢迎和感谢参与贡献，如何参与可参见 [Contributing](https://github.com/running-elephant/datart/blob/master)**

**Comment by scottsut** [comment]
> @scottsut 可以参与贡献吗？
> 
> 想参与贡献，但是readme里面的跳转连接不对， **非常欢迎和感谢参与贡献，如何参与可参见 [Contributing](https://github.com/running-elephant/datart/blob/master)**

感谢！但这个问题本质还是你的系统账户权限问题，具体是否需要改进我们评估一下。

**Comment by guodongym** [comment]
> 

好的，生产环境还是很大概率出现不让使用root账户部署的情况的

**Comment by Cuiyansong** [comment]
感谢贡献，如有问题请留言。
