### ISSUE TITLE
将datart进行前后端分离部署后，WebDriver.get(url)中url无法访问，导致无法截图问题

### ISSUE THREAD

**Issue by SkyBecauseLaLa** [running-elephant/datart#1365]
在我们尝试将datart进行前后端分离部署后，定时任务中通过 WebDriver.get(url) 获取url页面对应截图进行发送邮件，但由于前后端分离导致通过 String url = Application.getWebRootURL()+"/"+shareCreateParam.getVizType().getShareRoute()+"/"+share.getId()+"?eager=true&type="+share.getAuthenticationMode(); 生成的链接无法访问，页面404，
![image](https://user-images.githubusercontent.com/105908306/169474186-6b9a9a8c-57d1-467d-bb31-6e0c504696af.png)
我想大概是因为前后端分离后，导致该处接口无法转发
![image](https://user-images.githubusercontent.com/105908306/169474400-fc07cc36-a91e-4d84-9a15-bb9253d3a98e.png)
请问有什么方法解决吗，或者改进建议吗，谢谢

**Comment by xieliuduo** [comment]
如果将来方便 用户前后端分离部署的话   这块'/sharexxx.html' 可能提出来在配置文件中，程序从配置文件读取路径。目前的话你着急，要自己改一下了

**Comment by kiwi-field** [comment]
请问下这个我们应该怎么改呢,首先我们把对应的html存放到我们后端的resources目录下，然后request.getRequestDispatcher("/shareDashboard.html").forward(request, response);
这行代码怎么改造呢，另外前端同事需不需要改什么东西

**Comment by Zclhlmgqzc** [comment]
要改打包配置 

![image](https://user-images.githubusercontent.com/31752986/169509352-d6709b17-c6ec-4b91-bafc-659f1daaae19.png)

配合 nginx 然后后台访问 nginx 的路径就 OK 了

**Comment by Zclhlmgqzc** [comment]
···

root   /usr/share/nginx/html;

location / {
  index  index.html index.htm;
  try_files $uri $uri/ /index.html;
}
location /shareDashboard/ {
  index  index.html index.htm;
  try_files $uri $uri/ /shareDashboard/index.html?s=$uri&args;
}

···

**Comment by Zclhlmgqzc** [comment]
@mrcluo 

```
# html 下新建个 bi 目录 放文件 不要改这一行配置
root   /usr/share/nginx/html;

location /bi {
  index  index.html index.htm;
  try_files $uri $uri/ /index.html;
}
location /bi/shareDashboard/ {
  index  index.html index.htm;
  try_files $uri $uri/ /bi/shareDashboard/index.html?s=$uri&args;
}
```

**Comment by mrcluo** [comment]
不好意思，没说清楚
我们的情况有点不一样，我们服务器是单独的，没有新建bi目录，通过上面的nginx配置，把域名/bi/指向我们的服务器根目录
目前尝试了location 和 try_files 都试了加/bi/，都有点问题
1 如果是 域名/bi/指向我们的服务器根目录，请教下 nginx要怎么配呢，问了后端和运维不太清楚
2 如果是 域名/bi/指向我们的服务器根目录，上文提到的 https://github.com/running-elephant/datart/issues/1284#issuecomment-1118183224 还要配吗

**Comment by Zclhlmgqzc** [comment]
你现在是 直接把打包出来的文件放服务器上 现在变成 打包出来的文件放到一个 bi 文件夹再放服务器上 这样能听明白吗

**Comment by scottsut** [comment]
Related to #1284
