### ISSUE TITLE
shareChart白屏问题

### ISSUE THREAD

**Issue by yqwoe** [running-elephant/datart#1370]
**Datart Version**
The version of `datart` you using.

**Describe the bug**

偶尔的白屏，改变窗口偶尔会重新渲染

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by yqwoe** [comment]
分析:
出现问题的基本是 public/custom-plugins/xxx.js 插件；
原因:
猜测，加载xxx.js的顺序在加载viz data之后导致白屏。
临时解决办法：
```
#frontend/src/app/pages/SharePage/ShareChart.tsx 

before:
useMount(() => {
    ChartManager.instance()
      .load()
      .catch(err => console.error('Fail to load customize charts with ', err));
     loadVizData();
  });

after:

useMount(() => {
    ChartManager.instance()
      .load()
      .then(res => {
        loadVizData();
      })
      .catch(err => console.error('Fail to load customize charts with ', err));
  });

```

**Comment by Cuiyansong** [comment]
> 分析: 出现问题的基本是 public/custom-plugins/xxx.js 插件； 原因: 猜测，加载xxx.js的顺序在加载viz data之后导致白屏。 临时解决办法：
> 
> ```
> #frontend/src/app/pages/SharePage/ShareChart.tsx 
> 
> before:
> useMount(() => {
>     ChartManager.instance()
>       .load()
>       .catch(err => console.error('Fail to load customize charts with ', err));
>      loadVizData();
>   });
> 
> after:
> 
> useMount(() => {
>     ChartManager.instance()
>       .load()
>       .then(res => {
>         loadVizData();
>       })
>       .catch(err => console.error('Fail to load customize charts with ', err));
>   });
> ```

评估了你的方案是目前最合理的方案，感谢贡献！

**Comment by scottsut** [comment]
Fix 已随 beta.4 版本发布，如果问题依然存在，请重新打开这个 issue
