### ISSUE TITLE
滑块控制器回置到0时，无法再次拖动

### ISSUE THREAD

**Issue by wbjsly** [running-elephant/datart#1373]
服务端：
OS:  CentOS 7.5.1804
DB: ClickHouse 21.9.2.17
Datart: 1.0.0 Beta3

客户端：
OS: MacOS 12.3.1 
Browse:Safari 15.4 

问题：
滑块控制器回置到0时，无法再次拖动

操作步骤：
1、在仪表盘中增加一个滑块控制器，设置滑块最小值为0，显示标签为开启状态，其他值无限制。
2、保存后，在仪表盘向右拖动滑块，之后再向左拖动滑块到0（必须回到0）。
3、此时再向右拖动处在0的滑块时，无法拖动。

**Comment by wbjsly** [comment]
> 在解决这个之前 你可以先 关闭显示标签 选项 使用。 我们先定位一下具体问题，如果是 datart 的逻辑问题会尽快修复

好的，非常感谢！

**Comment by lyp000119** [comment]
https://user-images.githubusercontent.com/32259371/182828329-f92821ae-db4a-417b-805d-6765ebd10ab7.mp4
