### ISSUE TITLE
Question: Sort by fields not in viz

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1376]
When creating viz, we can define sort order on the fields added into the viz. There are times when we want to sort by fields not visible in the viz. How can we achieve this?

**Comment by clementchong** [comment]
> In SQL syntax, we cannot sort a column that is not in grouping or aggregation.

Understand the limitation from SQL. Power BI and Power Pivot done it via tooltip sort and sort by column setting respectively.

https://pbivisuals.com/2021/03/03/power-bi-sorting-data-by-a-column-not-shown-in-visual/

https://excelunplugged.com/2013/04/16/sorting-months-chronologically-and-not-alphabetically-in-a-pivot-table-report-based-on-power-pivot-data/

**Comment by Cuiyansong** [comment]
For now, we cannot support this feature, if there is any more questions, please let us know.
