### ISSUE TITLE
Pivot table cell tooltip missing i18n support

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1377]
**Datart Version**
Demo site 1.0.0b3

**Describe the bug**
In english mode, clicking on the pivot table cell shows tooltip in chinese.

**To Reproduce**

**Expected behavior**
The tooltip should display in correct language.

**Screenshots**

![image](https://user-images.githubusercontent.com/100477931/170261413-2ef0c585-48bc-493e-a0b5-ba15331b250f.png)

![image](https://user-images.githubusercontent.com/100477931/170261539-102798ab-ef0b-4a3d-af12-71a10ce8e406.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by clementchong** [comment]
> This issue is fixed, if it is not right on Beta4, please open this issue

Issue still there in beta4.

![image](https://user-images.githubusercontent.com/100477931/180119033-b129aca0-18a7-44b7-80f2-f1b8e53472ec.png)

**Comment by Cuiyansong** [comment]
We will discuss/confirm what will be translated in pivot table first.
