### ISSUE TITLE
react-frame-component link css

### ISSUE THREAD

**Issue by edison-tianhe** [running-elephant/datart#138]
**Is your feature request related to a problem? Please describe.**
frame保证了内部的css样式不会被污，提供了一个沙箱，但同时antd样式等(未来可能会有其他样式库)也被干掉了

**Describe the solution you'd like**
参考[getFrameHeader](https://github.com/running-elephant/datart/blob/master/frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartTools/ChartIFrameContainer.tsx#L33)函数，目前已经是集成了一部分antdCSS，但集的不是很成，比如ant-spin就没得，是否考虑换种解决方式，类似link标签的方式

**Comment by scottsut** [comment]
这个问题我们已经在调研了，后续方案更新在这个 issue

**Comment by scottsut** [comment]
Under consideration

https://github.com/hydrateio/react-styled-frame/blob/master/src/index.js
https://codesandbox.io/s/inject-styled-components-to-iframe-fj8id?file=/src/Frame/Frame.jsx
