### ISSUE TITLE
Runtime error when using drill down date field with space in name for display in pivot

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1394]
**Datart Version**
Demo site 1.0.03

**Describe the bug**
If a date field has space in its name, adding the drill down date level for display in pivot table would result in SQL error.

**To Reproduce**
Refer to screenshots

**Expected behavior**
The viz should work regardless if field name has space.

**Screenshots**

Default date format works ok
![image](https://user-images.githubusercontent.com/100477931/171004864-9dd09e06-779b-42c0-b8bd-dca27a7ff3a6.png)

Changing date level to Year/Quarter/Month/Week/Day has error

![image](https://user-images.githubusercontent.com/100477931/171005338-5cd1c27d-d05f-4b52-8571-6d71a5bc9f04.png)

![image](https://user-images.githubusercontent.com/100477931/171007221-e78c5f97-681c-44b6-8f64-ebdb5363edce.png)

It works ok if field name has no space

![image](https://user-images.githubusercontent.com/100477931/171006481-cdfc0981-e45e-4c9d-9418-1536504ed5f9.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by clementchong** [comment]
Can this issue be fixed by adding quotes to the field name?

**Comment by xiaohuangdou666** [comment]
For columns with spaces or keywords, you can alias them in the view SQL
对于有空格或者关键字的列，目前可以通过在视图sql中起别名解决

**Comment by clementchong** [comment]
> For columns with spaces or keywords, you can alias them in the view SQL 对于有空格或者关键字的列，目前可以通过在视图sql中起别名解决
Yes, I am aware of this workaround. However, we have users who would build reports themselves and they requested to retain the space instead of using underscore.

If I add alias in view, users need to alias back for proper business display. They prefer not to do this for every viz they are building.

I tried to trace the codes to find the line to include quotes but unable to pinpoint the exact line. Would it be in https://github.com/clementchong/datart/tree/master/frontend/src/app/components/ChartDrill ?

If someone can tell me where, I can try change and test out.

**Comment by clementchong** [comment]
I would also check frontend/src/app/models/ChartDataRequestBuilder.ts

**Comment by Cuiyansong** [comment]
From database column or table name convention/limitation, we cannot setup a name with "whitespace", so the case is really a corner case to be fixed for now. It seemed the issue is due to the "whitespace" in name not other special character right?

**Comment by clementchong** [comment]
yes, it is whitespace. Datart viz can support dragging fields with whitespace and we can see the field names in the generated SQL are enclosed in quotes. This is the part where we have whitespace in the date data type field and we use drill down, eg Month.

I think the quotes handling for fields need to be added to the drill down logic.

**Comment by scottsut** [comment]
After the discussion, we still recommend not to include spaces in field name. Not all databases support quote to escape,  field name that contain spaces may cause other unexpected problems.

**Comment by scottsut** [comment]
> Ok, I respect the decision. However, I like to clarify the physical column name in database has no whitespace. For better user experience, we alias column name with whitespace when we create view in datart. After that the issue arises during viz creation. The sql to underlying database should still be without whitespace.

Thanks for the scenario. We are considering adding aliases to the view-model fields. #1339

**Comment by clementchong** [comment]
> > Ok, I respect the decision. However, I like to clarify the physical column name in database has no whitespace. For better user experience, we alias column name with whitespace when we create view in datart. After that the issue arises during viz creation. The sql to underlying database should still be without whitespace.
> 
> Thanks for the scenario. We are considering adding aliases to the view-model fields. #1339

Sounds good! Does it mean there is no need to do something like below in future if it is implemented?

![image](https://user-images.githubusercontent.com/100477931/178739657-8a855c6f-8631-4d73-88aa-78513a8c4b25.png)

**Comment by scottsut** [comment]
> Sounds good! Does it mean there is no need to do something like below in future if it is implemented?
> 
> ![image](https://user-images.githubusercontent.com/100477931/178739657-8a855c6f-8631-4d73-88aa-78513a8c4b25.png)

I presume so.

**Comment by clementchong** [comment]
Ok thank you!
