### ISSUE TITLE
Pivot metric sort menu lacks i18n support

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1395]
**Datart Version**
Demo site 1.0.0b3

**Describe the bug**
Sort menu is hardcoded to chinese.

**To Reproduce**
See screenshots

**Expected behavior**
Menu should display in correct language

**Screenshots**
![image](https://user-images.githubusercontent.com/100477931/171018797-6c2ee111-a228-4117-a8ab-b6ac4def1f69.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by scottsut** [comment]
There are [antvis/S2](https://github.com/antvis/S2) internal labels.

**Comment by clementchong** [comment]
Request accepted at https://github.com/antvis/S2/issues/1394

**Comment by clementchong** [comment]
Fixed by the team at antvis/S2, please help include in next build of datart.

https://github.com/antvis/S2/pull/1397

**Comment by clementchong** [comment]
Issue still there in beta 4

![image](https://user-images.githubusercontent.com/100477931/180119292-213abbb3-2dee-4a24-93b7-42ca1a0395e7.png)

**Comment by Cuiyansong** [comment]
应该是S2-v1.18.1版本修复了国际化这个问题，升级的事情我们近期评估下新版本。
