### ISSUE TITLE
变量字段类型和数据库类型不匹配的时候，应该查不到数据，但却查到了两条数据

### ISSUE THREAD

**Issue by kiwi-field** [running-elephant/datart#1401]
**Datart Version**
The version of `datart` you using.
1.0.1-beta3
**Describe the bug**
变量字段类型和数据库类型不匹配的时候，应该查不到数据，但却查到了两条数据
**To Reproduce**
1. 创建表并导入数据
CREATE TABLE `Product` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `ProductType` int(11) NOT NULL COMMENT '订单类型：',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 ;

INSERT INTO `Product`(`id`, `ProductType`) VALUES (1, 1);
INSERT INTO `Product`(`id`, `ProductType`) VALUES (2, 0);
INSERT INTO `Product`(`id`, `ProductType`) VALUES (3, 1);
INSERT INTO `Product`(`id`, `ProductType`) VALUES (4, 0);
INSERT INTO `Product`(`id`, `ProductType`) VALUES (5, 4);

2.创建一个全局查询变量
![image](https://user-images.githubusercontent.com/30741355/171125112-decd3779-971f-4032-8745-ce98b12b4a56.png)

3.使用这个变量
`select  ProductType from test.Product where ProductType in ($RANK_LEVEL$)`

**Expected behavior**
数据库里的数据是数据类型的 0 1 2等值，执行这个sql应该查不到数据，但实际上查到了两条值为0的数据
![image](https://user-images.githubusercontent.com/30741355/171125592-800f633e-f72d-47b3-8f77-8d2690d3ced1.png)

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.18]

**Additional context**

**Comment by xiaohuangdou666** [comment]
mysql 比较时有类型隐式转换，参考官方文档解释
