### ISSUE TITLE
并发请求多问题建议

### ISSUE THREAD

**Issue by yhp353134** [running-elephant/datart#1405]
**你的功能要求与某个问题相关吗？**
风控分析师，不太考虑数据库架构，只是实现自己的功能，在一个可视化中添加了近100张看板，导致数据库卡死

**形容一下你想要的解决方案**
希望可以实现队列之类的查询，
或者可以设置最大查询队列，
或者实现权限管理，有权限的人可以保存看板，但是不可以建立可视化

**描述一下你考虑过的备选方案**
最简单的方式是把权限细化，可以控制到可视化和看板保存

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by yhp353134** [comment]
建议

**Comment by scottsut** [comment]
在主应用中，自动布局的仪表板加载图表数据时使用的是延迟加载策略，即滚动到可视区域才会加载。理论上不会卡死，请描述一下你的使用场景吧。

**Comment by yhp353134** [comment]
BI 使用在30人左右，风控团队10人用度比较频繁， 这10人把看板配置得很大，在同一时间使用，他们使用后，其他人基本都卡死了，因为数据库无法同时加载这么多连接查询

**Comment by yhp353134** [comment]
风控团队每个人   每个看板基本配置了几十张chart

**Comment by scottsut** [comment]
看看并发控制和缓存能否解决你的问题，加个 redis 就行

https://running-elephant.github.io/datart-docs/docs/view.html#8-1-%E5%B9%B6%E5%8F%91%E6%8E%A7%E5%88%B6
