### ISSUE TITLE
仪表板编辑页面组件列表拖拽问题

### ISSUE THREAD

**Issue by wmy7724** [running-elephant/datart#141]
如截图所示：在仪表板编辑页面—>组件列表，将‘TestMap’组件拖拽至‘TestChart’之前，期望效果是图表位置发生相应变化（‘TestMap’移至‘TestChart’左边），实际操作中，图表位置并未发生变化。
![image](https://user-images.githubusercontent.com/38877473/139777448-49ac5213-36fc-4ba4-b805-16a8bdfb22ac.png)

**Comment by xieliuduo** [comment]
这里其实可以在仪表板直接拖拽组件进行操作。而组件列表拖拽改变的是组件的顺序而不是位置。位置和顺序在datart中是两个概念。改变组件位置我们建议直接拖拽组件而不是组件列表。

**Comment by scottsut** [comment]
图层列表的位置是 z 轴位置，不代表 x y 坐标
