### ISSUE TITLE
hive 数据源，无法查询sql

### ISSUE THREAD

**Issue by anzuo09** [running-elephant/datart#1413]
**Datart版本号**
datart-1.0.0-beta.3

**错误描述**
hive 数据源，无法查询sql

**如何重现**
1. 新建数据视图页面
2. 执行select * from table
3. 看到错误：Request failed with status code 400

**期望结果**
查询hive 数据

**截图**

![微信图片编辑_20220602163321](https://user-images.githubusercontent.com/106730199/171591166-465224ce-8370-4abe-aaee-b74ff38a284a.jpg)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: 例如 centOS 7
- 数据源: hiveserver2
- 浏览器: chrome 

**其他内容**
有关这个问题的任意其他内容

![image](https://user-images.githubusercontent.com/106730199/171591038-6c1a93cc-788d-42a7-b5c6-61238ece8c6b.png)

**Comment by tianlu-root** [comment]
该问题已经修复，等beta.4版本发布后升级即可
