### ISSUE TITLE
定时任务有效时间显示问题

### ISSUE THREAD

**Issue by kiwi-field** [running-elephant/datart#1428]
**Datart Version**
1.0.0-beata3

**Describe the bug**
编辑定时任务页面基本时间没有及时刷新，

**To Reproduce**
1. 选择某一条定时任务，点击编辑，编辑之前的时间范围是2022-06-08 19:43:30  -   2022-06-30 19:43:35
2. ![image](https://user-images.githubusercontent.com/30741355/172856462-70bfd2fd-6476-4a38-89ea-55ee3001867a.png)
3. 修改时间范围如下.将起始时间改为2022-06-09 19:43:30  -   2022-06-30 19:43:35
4. 
![image](https://user-images.githubusercontent.com/30741355/172856752-4aef990f-7235-4119-be21-23c6cace6d8d.png)

5. 点击保存定时任务信息
6. 再将该定时任务启动
![image](https://user-images.githubusercontent.com/30741355/172857074-644f87c6-0d14-4f32-8143-d26994fb8618.png)

7. 右侧的时间范围又变成修改之前的了
8. 
![image](https://user-images.githubusercontent.com/30741355/172857160-29bfebaf-025e-4b0a-8beb-00ceb2f88edd.png)

**Expected behavior**
时间范围应该是修改后的

**Screenshots**

**Additional context**

**Comment by kiwi-field** [comment]
刷新以后就是正确的时间了。不影响后台定时任务的执行是吧，就刚修改的时候第一次显示有问题

**Comment by scottsut** [comment]
不影响，前端展示没有同步好
