### ISSUE TITLE
双Y轴图组件的y轴零点没有对齐

### ISSUE THREAD

**Issue by heropoet** [running-elephant/datart#1436]
**Datart版本号**
beta.3

**错误描述**
双Y轴图组件的y轴零点没有对齐,导致可视化给用户带来误解
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/41409482/173272643-26ef3cc0-af26-4b4e-80f2-e36c15f74cd4.png">

**如何重现**
重现错误的步骤，例如：
1. 到...页面
2. 点击...
3. 滚动到...
4. 看到错误

**期望结果**
1、双Y轴两边的零点对齐
2、最好能提供Y轴刻度、区间的设置选项

**截图**
如果方便的话，添加一个截图帮助解释你的问题

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: [例如 Windows 10]
- 数据源: [例如  MySQL 8.0.26]
- 浏览器: [例如 chrome 94, safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by qxqzx13** [comment]
[https://github.com/running-elephant/datart/pull/1497](url)
