### ISSUE TITLE
仪表板下载功能 是否可以支持pdf文件

### ISSUE THREAD

**Issue by clforzhx** [running-elephant/datart#144]
目前有需要 对仪表板进行下载 期望下载pdf格式~ 保留页面插件样式
当前是下载为excel表格，表格为具体的数据 用户还要自行 制作 柱状图 饼图 等等等。。

**Comment by scottsut** [comment]
有计划支持

**Comment by scottsut** [comment]
beta.3 版本已支持下载 PDF
