### ISSUE TITLE
控制器取值可以获取权限变量

### ISSUE THREAD

**Issue by DeathShort** [running-elephant/datart#1441]
现状：
控制器的取值每次都是获取全量数据，不能根据用户的实际权限获取指定的值

解决方案：
控制器可以从权限变量中获取取值，这样不同的用户的控制器就不会有多余的数据了。通过配置控制器间的关联字段，达到千人千面的效果
![image](https://user-images.githubusercontent.com/24557066/173527563-7bf22ad3-be5c-4c72-ac15-7ee12b89a6cd.png)

**Comment by scottsut** [comment]
取值配置选“常规”，可以按照登录用户的权限来获取值。问题不成立

**Comment by xieliuduo** [comment]
后续会有相关的优化 你提供的方案 很有参考价值，谢谢

**Comment by DeathShort** [comment]
非常感谢及时回复！
