### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by ParkerJX** [running-elephant/datart#1451]
**Datart Version**
beta3

**Describe the bug**
当 SQL 种出现 MySQL 函数CONCAT 会报错

比如：
<#if _CONCEPT_NAME != '' >
 AND b.concept_name LIKE CONCAT("%",$_CONCEPT_NAME$,"%")
</#if>

报错如下：
2022-06-15 17:56:40.929 ERROR datart.server.config.WebExceptionHandler : String index out of range: -1
java.lang.StringIndexOutOfBoundsException: String index out of range: -1

**Comment by Cuiyansong** [comment]
如还能复现，请重开ISSUE
