### ISSUE TITLE
日期类衍生出来的字段进行筛选时控制器下拉列表没有值

### ISSUE THREAD

**Issue by kiwi-field** [running-elephant/datart#1463]
**Datart Version**
master分支

**Describe the bug**
衍生类型的字段，在进行筛选时，控制器下拉列表没有值

**To Reproduce**
![image](https://user-images.githubusercontent.com/30741355/174226177-105aff7c-9863-4cbe-a900-55f4b2feca4a.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/30741355/174226234-b19645d4-9277-4ee4-9d1b-bee722f7e1df.png)

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by Cuiyansong** [comment]
筛选是否应该支持“衍生”日期类型？

**Comment by Cuiyansong** [comment]
当前版本过滤条件暂不支持“衍生”类日期，仅支持常规日期类型。
