### ISSUE TITLE
数据视图执行完sql以后，保存按钮是灰色，点击不了（偶发）

### ISSUE THREAD

**Issue by kiwi-field** [running-elephant/datart#1467]
**Datart Version**
master

**Describe the bug**
执行完sql以后，保存按钮是灰色，点击不了（除非手动更改数据模型任一字段的数据类型）

**To Reproduce**
1.打开任一视图
2. 执行sql
![image](https://user-images.githubusercontent.com/30741355/174242671-f7f99996-a9bb-4e5c-96b7-aeb7a309e991.png)
3.可以看到保存按钮为灰色
4.当我修改任一字段的数据类型从字符-->数值之后
![image](https://user-images.githubusercontent.com/30741355/174242750-9edf9c67-879b-49c5-8eba-b4f66539fd58.png)
5.保存的an按钮亮了
![image](https://user-images.githubusercontent.com/30741355/174242852-9ce89c01-54a6-4889-87fd-c3c93e81f31f.png)

**Expected behavior**
执行完的sql应该可以保存，不需要手动更改字段的数据类型

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by kiwi-field** [comment]
是这种情况，但这个问题我该怎么解决呢？还有一个疑惑，什么是执行片段，什么是执行所有语句呢

**Comment by kiwi-field** [comment]
取消刚进来编辑器中的 SQL 语句的选中状态，再次点击执行就可以保存了，鼠标放到执行按钮上面可以看到 “”执行片段”或者"执行"

**Comment by kiwi-field** [comment]
需要用户手动取消编辑器中的sql选中状态，就是这么设计的是吧

**Comment by scottsut** [comment]
这其实跟 monaco-editor 有关，当新建实例并给它赋值时，编辑器中的内容会自动全部选中。我们没有深究这个问题，如果你认为这个特性不符合你的预期，可以给我们贡献代码来完善它

**Comment by scottsut** [comment]
> 是这种情况，但这个问题我该怎么解决呢？还有一个疑惑，什么是执行片段，什么是执行所有语句呢

“执行片段”就是使用鼠标选中编辑器中的一部分语句来执行，这个功能基本上所有的数据库客户端都有吧？
