### ISSUE TITLE
添加clickhouse数据源报没有找到驱动

### ISSUE THREAD

**Issue by meixianshen** [running-elephant/datart#1480]
1.docker pull datart/datrt
2.docker run -p 8080:8080 datart/datart 
3.添加数据源
![image](https://user-images.githubusercontent.com/54343603/174566612-7eaac5d7-a15c-4f88-9c4b-cbbd7b5240d0.png)

**Comment by scottsut** [comment]
https://running-elephant.github.io/datart-docs/docs/jdbc.html

**Comment by meixianshen** [comment]
thank you
