### ISSUE TITLE
通过impala查询日期字段没有映射成日期格式，也没有衍生出日期相关的字段

### ISSUE THREAD

**Issue by kiwi-field** [running-elephant/datart#1489]
**Datart Version**
1.0.0-beta3

**Describe the bug**
impala查询日期类型的字段，映射的数据模型不对

**To Reproduce**
1. 配置一个impala连接
2. 通过刚才的impala数据源，新建一个数据视图，执行以下sql  ````  select CURRENT_DATE()   ````
3. 映射的数据模型不对
![image](https://user-images.githubusercontent.com/30741355/174724227-77fd4e95-f41d-4945-9696-ec103c2638d5.png)
5. See error

**Expected behavior**
应该映射成日期格式，并且在对应的可视化页面应该衍生出日期相关的字段
**Screenshots**
![image](https://user-images.githubusercontent.com/30741355/174724459-610b49c3-aae2-47e7-a038-09aea90c1bff.png)
**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by heropoet** [comment]
Presto数据源也是一样的，目测只有mysql数据源是支持的

**Comment by scottsut** [comment]
beta.3 的 release note 里有说明，目前只支持 4 种数据库的衍生日期字段

**Comment by kiwi-field** [comment]
![image](https://user-images.githubusercontent.com/30741355/175440736-9945398e-275c-4daf-b01f-86855180b40d.png)
这4个是吧

**Comment by scottsut** [comment]
是的
