### ISSUE TITLE
权限设置新建按钮被自动跳转禁用

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1490]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
 
  eg: 在定时任务权限设置页面，
        首先设定 新建定时任务为启用，然后为下方的资源添加管理权限时新建权限会自动跳转至禁用；

**To Reproduce**
同上

**Comment by Plume3362** [comment]
> 
![20220621150833](https://user-images.githubusercontent.com/49897998/174737861-de5eb696-84c9-4f8a-a287-3376be318072.png)
![image](https://user-images.githubusercontent.com/49897998/174737943-4b9ee273-fe4e-4411-87c4-dbfeb3ae9118.png)

**Comment by Plume3362** [comment]
@scottsut

**Comment by Cuiyansong** [comment]
- 列表权限设置（旧版）
- 目录树资源权限设置（新版）

**Comment by Cuiyansong** [comment]
relate issue #1502
