### ISSUE TITLE
仪表盘点击跳转功能增强

### ISSUE THREAD

**Issue by huzk8** [running-elephant/datart#1492]
**形容一下你想要的解决方案**
- 翻牌器支持跳转设置，效果类似柱状图的
- 表格跳转目前只支持点击左边的维度跳转，期望可以点击数据项进行跳转，并且调整时带上参数
- 配置跳转控制器时，希望能引用当前仪表板的过滤器的设置参数，一并传递到跳转后的仪表板

**Comment by scottsut** [comment]
1、2 两条，携带数值参数跳转，生成的筛选条件应该是什么样的？

**Comment by huzk8** [comment]
> 1、2 两条，携带数值参数跳转，生成的筛选条件应该是什么样的？

1、点击翻牌器时，将当前页面的筛选条件带到另一个看板的筛选器中
2、点击表格中数据项筛选时，以行纬度+列维度分别对应到两个控制器进行筛选，不同列的筛选配置不同

**Comment by huzk8** [comment]
> 1、2 两条，携带数值参数跳转，生成的筛选条件应该是什么样的？

1、点击翻牌器时，直接跳转到某个仪表板
2、点击表格数据项筛选时，以行纬度+列维度分别对应到两个控制器进行筛选，不同列的筛选配置不同

**Comment by scottsut** [comment]
> 1、点击翻牌器时，直接跳转到某个仪表板，不用带筛选条件 2、点击表格数据项筛选时，以行纬度+列维度分别对应到两个控制器进行筛选，不同列的筛选配置不同

你对表格的描述混杂了透视表的逻辑，这两者是有区别的

**Comment by huzk8** [comment]
恩，确实没表达清楚



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月23日(周四) 下午5:38
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [running-elephant/datart] 仪表盘点击跳转功能增强 (Issue #1492)




  
1、点击翻牌器时，直接跳转到某个仪表板，不用带筛选条件 2、点击表格数据项筛选时，以行纬度+列维度分别对应到两个控制器进行筛选，不同列的筛选配置不同
  
你对表格的描述混杂了透视表的逻辑，这两者是有区别的

**Comment by Cuiyansong** [comment]
新一版的跳转即将发布，可以关注下后续功能。

**Comment by Plortinus** [comment]
> 新一版的跳转即将发布，可以关注下后续功能。

跳转功能发布了吗
