### ISSUE TITLE
保存数据视图表字段长度过短

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1495]
**Datart Version**
1.0.0-beta.3 

**Describe the bug**
![image](https://user-images.githubusercontent.com/49897998/174925021-26f4f288-76d4-477e-a55a-7bdd24602f41.png)
![image](https://user-images.githubusercontent.com/49897998/174925147-dd7862a1-6b91-4ee9-80a5-3e0e61c749b9.png)

适当增加字段长度 @scottsut

**Comment by scottsut** [comment]
麻烦提供一下复现步骤

**Comment by Plume3362** [comment]
![image](https://user-images.githubusercontent.com/49897998/174971425-1910fbc1-a012-4517-9fcb-c537f68857a0.png)
第一次保存之前设置列权限

**Comment by Plume3362** [comment]
@scottsut

**Comment by scottsut** [comment]
临时的解决方案，刷新下页面再编辑就行了。代码问题我们后续会修复

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
