### ISSUE TITLE
数据视图-翻牌器-样式（头部、主体、尾部）的字体大小无法调整

### ISSUE THREAD

**Issue by kiwi-field** [running-elephant/datart#1499]
**Datart Version**
1.0.0-beta3

**Describe the bug**
数据视图-翻牌器-样式（头部、主体、尾部）的字体大小无法调整

**To Reproduce**
1. 新建一个数据视图
2. 选择翻牌器
3. 选择3个指标
4. 修改头部、主体、尾部配置项下的字体大小不生效

**Expected behavior**
应该生效

**Screenshots**
第2步截图.
![image](https://user-images.githubusercontent.com/30741355/174976353-97ab909f-1003-4444-9d94-8077bd1f268b.png)
第3步截图.
![image](https://user-images.githubusercontent.com/30741355/174976742-e1636c68-f707-4253-b785-f030b8c25030.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
感谢贡献，如有问题请留言。
