### ISSUE TITLE
创建可视化 - 翻牌器 - 调整样式中整体样式的头部、主体、尾部字体大小无效果

### ISSUE THREAD

**Issue by SkyBecauseLaLa** [running-elephant/datart#1500]
在创建可视化 -》翻牌器 -》样式 -》整体：调整头部字体大小、主体字体大小、尾部字体大小数值均没有效果
![image](https://user-images.githubusercontent.com/105908306/174980108-13ea079f-702b-4e7a-a7bb-75731560e75f.png)

**Comment by scottsut** [comment]
用左起第4个翻牌器，第3个后续会移除

**Comment by SkyBecauseLaLa** [comment]
感谢解答
