### ISSUE TITLE
富文本变量问题

### ISSUE THREAD

**Issue by gaolmao** [running-elephant/datart#1507]
**Datart版本号**
1.0.0-beta.3
**错误描述**
查询结果中除了数据结果外，我需要在表头下方显示出各类筛选条件的中文，作为报表表头的一部分。如图，在查询结果中增加了富文本显示，显示报表名、机构（网点）名称、日期等信息。但是富文本部分的机构名称无法正常显示，报表数据是正常显示的。即富文本引用的数据存在变量条件查询时，引用就失效了。
机构名称通过查询网点编号从数据库获取。

**如何重现**

**期望结果**
在查询结果中富文本也能像表格数据一样，支持传入变量参数，根据参数显示不同结果。

**截图**

![IMG_20220623_180000](https://user-images.githubusercontent.com/107606876/175276495-6c7a2d14-aae6-438e-8ba8-d79019c7effb.jpg)

**Comment by scottsut** [comment]
从筛选机制来看，“引用失效”是不可能的。这个情况大概率是数据不对、或是配置不对。请提供以下内容帮助进一步确定问题：
1. 富文本图表的配置界面截图
2. 先打开浏览器控制台的网络栏，然后在仪表板中选择“网点行号 111*” ，将该富文本图表查询返回值截图

**Comment by gaolmao** [comment]
您好，确认了下，应该是变量引用中带了引号替换不过来，修改后机构名称可以正常显示了，但开始日期、结束日期在查询语句中去不掉引号，还是无法替换。
如果想将查询区中的信息，在富文本结果区域显示，是不是还有其他方式，感谢支持。
详细如下，定义了三个变量：
<img width="416" alt="image" src="https://user-images.githubusercontent.com/107606876/175855717-723829e2-480d-4bfa-a620-71d21898ea00.png">
数据视图定义：
<img width="415" alt="image" src="https://user-images.githubusercontent.com/107606876/175856039-255f1c8c-1d29-4aa0-a2be-c8d21ff88e19.png">

富文本图表的配置截图
<img width="415" alt="image" src="https://user-images.githubusercontent.com/107606876/175856070-cbf1536e-361d-41f3-b9d8-dfba4998e220.png">

仪表板结果截图：
<img width="416" alt="image" src="https://user-images.githubusercontent.com/107606876/175856095-27c222be-148a-438e-ad2d-3854eac8d8c8.png">

**Comment by scottsut** [comment]
SQL 里为什么要加引号？字符型和日期型变量在后端拼接时会自动加引号

**Comment by scottsut** [comment]
那 STAT_DATE 实际上是不是字段名称呢？

**Comment by scottsut** [comment]
你这两个变量有添加默认值吗？

**Comment by gaolmao** [comment]
没有添加默认值。 我补充上默认值后可以正常显示了。多谢多谢了。
