### ISSUE TITLE
定时同步数据库库表信息不生效

### ISSUE THREAD

**Issue by gaolmao** [running-elephant/datart#1508]
**Datart版本号**
1.0.0-beta3

**错误描述**
在数据源编辑中，将定时同步数据库库表信息开启后，没有按照描述“Datart将按照指定时间间隔定时同步数据库库表信息”更新，一直是新建时同步的数据库表信息。

**如何重现**
重现错误的步骤，例如：
1. 新建一个数据源，将定时同步数据库库表信息开启。
2. 在数据源中新建几张数据表。
3. 多个小时后，查询数据视图中的数据库表无更新。

**期望结果**
数据视图中的数据库表定时更新。

**截图**
设置截图：
<img width="441" alt="1" src="https://user-images.githubusercontent.com/107606876/175283966-93fbd511-0346-44cd-83fb-8090bc552144.PNG">
数据视图截图：
<img width="308" alt="2" src="https://user-images.githubusercontent.com/107606876/175284015-bdc1372f-2b51-451a-a07e-4c13db19f04c.PNG">

数据库b表：
<img width="256" alt="3" src="https://user-images.githubusercontent.com/107606876/175284039-8585211e-ed91-46fd-ab06-ad59ecb998ed.PNG">

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: Windows 10
- 数据源: MySQL 8.0.26
- 浏览器: chrome 94

**其他内容**
有关这个问题的任意其他内容

**Comment by scottsut** [comment]
是什么数据库？

**Comment by Cuiyansong** [comment]
link https://github.com/running-elephant/datart/pull/1801/commits/b0008ff4d5bba469a997c35b8959817b4fc93e44
