### ISSUE TITLE
多选下拉列表选多了错位,希望能优化一下

### ISSUE THREAD

**Issue by taojing001** [running-elephant/datart#1511]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
多选下拉列表选多了错位,拉长比较丑,希望能优化一下
![image](https://user-images.githubusercontent.com/23050412/175457887-11273bc5-087a-4fb3-8763-9c3d166996f6.png)
![image](https://user-images.githubusercontent.com/23050412/175457991-437afe92-61fc-43ab-9a2d-2ccf0c3faaf5.png)

**Comment by scottsut** [comment]
Related to #1571
