### ISSUE TITLE
希望控制器能支持树形结构数据

### ISSUE THREAD

**Issue by taojing001** [running-elephant/datart#1512]
**Is your feature request related to a problem? Please describe.**
希望控制器能支持树形结构数据的筛选，没有树形结构控制器，只能把数据处理成只保留叶子节点数据，展示成这个样子
![image](https://user-images.githubusercontent.com/23050412/175459812-69b05dfa-abaa-4904-aba3-90dbec03ddc3.png)

**Describe the solution you'd like**
希望控制器能支持树形结构数据的筛选

**Additional context**
![image](https://user-images.githubusercontent.com/23050412/175459739-ba3c1558-4d72-4bdc-bb79-43e1c3fd9d35.png)

**Comment by KANLON** [comment]
+1

**Comment by lidong081824** [comment]
+1

**Comment by lyp000119** [comment]
https://github.com/running-elephant/datart/pull/1923
