### ISSUE TITLE
新建可视化分析无法取消筛选

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1513]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
新建可视化时对某个指标进行筛选后无法取消筛选

**To Reproduce**
1. 可视化下点击开始分析
2. 拖拽某个字段进行筛选
3. 重新筛选移除之后无法保存，提示输入筛选方式

**Expected behavior**
有一个可以清除过滤的按钮或可以去除所有筛选条件

**Screenshots**
![image](https://user-images.githubusercontent.com/49897998/175491256-9f27f3b2-fc0e-452d-ac0e-5a50b2a7ff2b.png)
![image](https://user-images.githubusercontent.com/49897998/175491286-716bac64-753e-48cd-a557-155031867b9e.png)
![image](https://user-images.githubusercontent.com/49897998/175491314-7eea518c-80c3-45b2-bc0e-46ce67b2f503.png)

**Comment by Cuiyansong** [comment]
如果不想筛选任何条件，是否直接删除拖拽的节点（字段），即可？

**Comment by Cuiyansong** [comment]
感谢贡献，如还有问题请留言。
