### ISSUE TITLE
可视化-仪表板-添加到故事版时出现空白页

### ISSUE THREAD

**Issue by kiwi-field** [running-elephant/datart#1515]
**Datart Version**
1.0.0-beta3

**Describe the bug**
将某一个仪表版添加到故事版出现空白页面

**To Reproduce**
1. 新建一个仪表板
2. 将仪表板添加到故事版
3. 出现空白页面

**Expected behavior**
应该正常添加到故事版
**Screenshots**
![image](https://user-images.githubusercontent.com/30741355/175502932-617634b6-d2e7-4d30-b28a-7a22d43f7278.png)
![image](https://user-images.githubusercontent.com/30741355/175503015-95bb651e-9dc3-440c-a2a2-a07c59c2402d.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by scottsut** [comment]
请把浏览器控制台的错误信息截图一下

**Comment by kiwi-field** [comment]
![image](https://user-images.githubusercontent.com/30741355/175842485-1f69536c-58fa-44a9-86ee-f29937accabe.png)

**Comment by Plume3362** [comment]
@scottsut 这个有后续吗

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
