### ISSUE TITLE
仪表盘中的控制器可以重名

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1521]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
从仪表盘中新建控制器的标题可以重复

**Expected behavior**
对仪表板中的组件做标题唯一性校验

**Screenshots**
![image](https://user-images.githubusercontent.com/49897998/175845051-f3248b9d-9d61-40dc-bf8e-6ea9eef00163.png)

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
