### ISSUE TITLE
Date drill down not available for fields under hierachy

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1524]
**Datart Version**
Demo site 1.0.0b3

**Describe the bug**
A date field has drill down feature. The same date field loses drill down after it is added into hierarchy in data model.

**To Reproduce**

**Expected behavior**
Same drill down feature should be available.

**Screenshots**
![image](https://user-images.githubusercontent.com/100477931/175897103-bae90e48-e45e-41dc-81bb-9df732261cb8.png)

![image](https://user-images.githubusercontent.com/100477931/175897231-0c4ba4dd-ba87-4e46-8003-4e71a5d6150e.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by lyp000119** [comment]
https://github.com/running-elephant/datart/pull/1519/commits/eb0cdd3ec0770faa235a6c43ff2e7f8ef883cd6e

**Comment by lyp000119** [comment]
https://github.com/running-elephant/datart/pull/1519/commits/eb0cdd3ec0770faa235a6c43ff2e7f8ef883cd6e
already fixed

**Comment by clementchong** [comment]
Thank you! Great!
