### ISSUE TITLE
datart有提供网站访问情况的统计功能吗？

### ISSUE THREAD

**Issue by JashonHuang** [running-elephant/datart#1529]
**你的功能要求与某个问题相关吗？**
做为数据看板， 需要统计某个数据板块的dau及pv情况
**形容一下你想要的解决方案**
管理员有后台统计数据，可以看到整个站点的使用情况， 新增多少页面， 发布多少页面， 
每个页面的实际流量，哪个用户在频繁使用

**Comment by scottsut** [comment]
目前没有，有需要可以自己二次开发添加
