### ISSUE TITLE
设置账号的时候，输入了姓名和部门，点击保存之后，刷新页面没保存成功

### ISSUE THREAD

**Issue by KANLON** [running-elephant/datart#1537]
**Datart Version**
使用的版本为这个 [1.0.0-beta.3](https://github.com/running-elephant/datart/releases/tag/1.0.0-beta.3)

**Describe the bug**
设置账号的时候，输入了姓名和部门，点击保存之后，刷新页面没保存成功

**To Reproduce**
1. 进入datart页面，点击右下角账号设置
2. 编辑中文名和部门信息，点击保存
3. 刷新页面，再点击右下角账号设置，部门信息不见了

**Expected behavior**
账号设置这里设置中文和部门应该设置成功，并且刷新之后能看到设置的信息

**Screenshots**
![image](https://user-images.githubusercontent.com/22886101/176191106-3b4763ca-18ab-4b1e-a15e-941dc1de9d0c.png)

我看用户表没有部门的属性，好像这个只是装饰，设置不成功

**Comment by Cuiyansong** [comment]
目前将“部门”改为“描述”，后期再考虑扩展用户Profile的相关内容
