### ISSUE TITLE
Question: Is there a way to click and view underlying data records from vizualisations?

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1540]
I see that there is a feature to set jump and allows filter values to be passed to a new page. Is it possible to click on the viz and have an option to view underlying data records?

This would be very useful to users who are interested to know what the summary data in viz is made up of.

**Comment by Cuiyansong** [comment]
I m not quite sure what you are talking about? Could you please give us some example or detail operation on chart/board?

**Comment by Cuiyansong** [comment]
In next version of Beta4, we add new feature of Jump/link/View Detail Data to extend chart/board interaction.
For example, let say the `blue` bar is mean dimension is 0 and with 30 records.When we setup a config on view detail data with left mouse click event, then we click chart `blue` bar, it will show a dialog with "30 records data" as a table. The backend logic is we add a filter with dimension equal to 0 when dialog fetch records.
Is it the behaivour as you expect?

**Comment by clementchong** [comment]
Yes, sounds like what I was looking for! It should enable users to view the underlying data for each bar or number in a pivot.

Looking forward to beta4.

**Comment by Cuiyansong** [comment]
Beta4 is under testing and will release soon! 

We will close this issue, if new version interaction feature is not what you want, please reopen the issue~

**Comment by clementchong** [comment]
Thank you!
