### ISSUE TITLE
数据视图新建目录或视图没有权限

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1542]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
非组织拥有者没有所有视图的管理权限时，无法在根目录新建数据视图或目录

**To Reproduce**
1. 用没有所有视图管理权限的测试账号新加数据视图或目录
2. 所属目录选择根目录

3. 抛出异常且弹出两个框。。。

**Expected behavior**
在没有根目录的权限时，能否新建；如果不能，那除非有权限的账号建了目录且赋予测试账号改目录的权限，否则永远不能新建

**Screenshots**
![图片](https://user-images.githubusercontent.com/49897998/176391272-80b85ced-7987-4a7d-b9c1-ed82b453b688.png)
![图片](https://user-images.githubusercontent.com/49897998/176391483-bec8d330-cfd6-4c22-a836-6b05cf97e74e.png)
![图片](https://user-images.githubusercontent.com/49897998/176391529-d29c127f-ade3-4279-9b07-4da2320a779d.png)

**Comment by scottsut** [comment]
是这样设计的，没有目录权限的确不能创建。普通用户如果要新建资源，先让管理员给你一个有权限的目录。

这方面有好的建议欢迎提出。

**Comment by Plume3362** [comment]
其实我觉得 会不会不把根目录当作一个目录去做权限判断会不会比较好，也就是说只要有新增的权限就有在根目录创建的权限；
另外问一下，为什么会有两个弹框，而且有的地方并不会把后端返回的异常弹到页面上？

**Comment by Plume3362** [comment]
@scottsut

**Comment by scottsut** [comment]
> 其实我觉得 会不会不把根目录当作一个目录去做权限判断会不会比较好，也就是说只要有新增的权限就有在根目录创建的权限； 另外问一下，为什么会有两个弹框，而且有的地方并不会把后端返回的异常弹到页面上？

首先，datart 的目录结构没有独立的新建权限，文件夹的管理权限即是许可在该文件夹下的新建权限。

另外，根目录和常规目录没有区别，目录的权限是继承的，如果期望某用户能够在根目录下新增资源，就要赋予根目录的管理权限，那么自然根目录下其他的资源他都可以访问和操作了。

两个弹框是代码上没有优化好，后续会逐步优化。

**Comment by scottsut** [comment]
> 其实我觉得 会不会不把根目录当作一个目录去做权限判断会不会比较好，也就是说只要有新增的权限就有在根目录创建的权限； 另外问一下，为什么会有两个弹框，而且有的地方并不会把后端返回的异常弹到页面上？

从管理角度看也是有弊端的。任何人都能在根目录下创建资源的话，公司体量大一些，从管理员视角看会混乱不堪

**Comment by Cuiyansong** [comment]
感谢贡献，如果还有此问题请留言。
