### ISSUE TITLE
定时任务有时会发送失败

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1543]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
发送定时任务配置有时会执行失败

![图片](https://user-images.githubusercontent.com/49897998/176395567-c116cbd5-9612-4331-a0d2-77fa47744c84.png)

**Comment by scottsut** [comment]
请求时间太长超时了。`application-config.yml` 中默认的截图超时是60秒，有需要可以自己改长一些。

**Comment by Plume3362** [comment]
@scottsut 感觉有时候不是这个原因，现在很简单的图，超时设置了三分钟也会出现这个异常

**Comment by Plume3362** [comment]
![图片](https://user-images.githubusercontent.com/49897998/178729779-d4c97c72-94ba-4c31-8648-55d5c6bab91b.png)
![图片](https://user-images.githubusercontent.com/49897998/178729879-4fd11404-82d1-4b36-b0d6-cf94da786403.png)

**Comment by Plume3362** [comment]
而且两个服务配置相同的截图服务，一个会截图成功，另一个从来没有成功过

**Comment by scottsut** [comment]
> 而且两个服务配置相同的截图服务，一个会截图成功，另一个从来没有成功过

你看看两边的 `datart.address` 配置，有一个可能是错的

**Comment by Plume3362** [comment]
@scottsut 之前两边的address是一样的，刚才把data,conf中的datart.address和application-config.yml中的datart.server.address都改过，截图这里还是有问题。。

**Comment by Plume3362** [comment]
确实是要修改 config.yml里面的datart.server.address的地址，然后看下生成的分享链接能不能正确打开
