### ISSUE TITLE
权限->数据视图，当未给成员赋数据视图所有资源权限时，成员创建数据视图无法保存

### ISSUE THREAD

**Issue by SkyBecauseLaLa** [running-elephant/datart#1544]
权限 -> 数据视图权限 -> 未给成员赋所有资源权限，只给部分视图权限，成员存在创建数据视图图标，当创建数据视图后进行保存时，保存报错。(是没有根目录的权限就无法创建吗，那这样是不是不应该有创建数据视图的按钮呢)
![image](https://user-images.githubusercontent.com/105908306/176399988-ef8564df-9cbb-491a-87af-b987cc30ed2c.png)
![企业微信截图_1656493324995](https://user-images.githubusercontent.com/105908306/176400035-997a6a29-0e1a-400c-b51f-1782ad3ac870.png)

**Comment by Plume3362** [comment]
我刚提过这个issuu，它其实有判断目录权限的部分，如果你给这个成员账号新建一个有权限的目录，就可以把视图或者目录建在这个目录下面

**Comment by scottsut** [comment]
关键点在于你是否授予了某个目录权限。

这个问题文档里有说明，参考文档的权限章节 https://running-elephant.github.io/datart-docs/docs/permission.html#1-1-%E8%B5%84%E6%BA%90%E6%9D%83%E9%99%90

**Comment by Cuiyansong** [comment]
感谢贡献，如还有问题请在此Issue下留言。
