### ISSUE TITLE
定时任务保存按钮状态错误

### ISSUE THREAD

**Issue by scottsut** [running-elephant/datart#1552]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
定时任务保存按钮状态错误

**To Reproduce**
1. 打开一个已经开始执行的定时任务，此时保存按钮置灰，是正确的
2. 切换到新增页，保存按钮依然置灰，错误

**Expected behavior**
切换到新增页后保存按钮可用

**Screenshots**

https://user-images.githubusercontent.com/4098913/176669846-dd6bf627-c569-4816-8481-b7ffb6ef0fd2.mp4

**Comment by Cuiyansong** [comment]
Pls verify PR #1578 ， if it is fixed
