### ISSUE TITLE
Waterfall chart total description lacks i18n support

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1554]
**Datart Version**
Demo site 1.0.0b3

**Describe the bug**
The total label is hardcoded to chinese.

**To Reproduce**

**Expected behavior**
It should display in selected language.

**Screenshots**
![image](https://user-images.githubusercontent.com/100477931/176693878-b6749d06-6581-4f9b-9934-4c66577198e0.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by clementchong** [comment]
2 more hardcoding in the chart mouseover popup.

For my own reference, file to change is https://github.com/running-elephant/datart/blob/dev/frontend/src/app/components/ChartGraph/WaterfallChart/WaterfallChart.tsx

![image](https://user-images.githubusercontent.com/100477931/176826155-6a0711b9-9f26-4a55-96c2-2e612110b0ec.png)

**Comment by Cuiyansong** [comment]
Right, not just one place, will fixed.

**Comment by clementchong** [comment]
Thank you!
