### ISSUE TITLE
WidgetInfoProvider.tsx TypeScript definition error

### ISSUE THREAD

**Issue by Gongkaikai** [running-elephant/datart#156]
**Describe the bug**
本地启动前端部分报错

**To Reproduce**
报错文件： [frontend/src/app/pages/DashBoardPage/components/WidgetInfoProvider.tsx](https://github.com/running-elephant/datart/blob/dev/frontend/src/app/pages/DashBoardPage/components/WidgetInfoProvider.tsx)

**Screenshots**
![1](https://user-images.githubusercontent.com/19772826/140446319-9dafc50f-eef0-46a3-b9dc-ab40da6b8c69.jpg)
![2](https://user-images.githubusercontent.com/19772826/140446329-0049b7b9-a286-43e1-ac6e-601f6e10fd95.jpg)

**Comment by scottsut** [comment]
` master`分支还是`dev`分支？

**Comment by Gongkaikai** [comment]
> ` master`分支`dev`分支？

两个分支都试过了，都是这个问题

**Comment by scottsut** [comment]
> 两个分支都试过了，都是这个问题

typescript 依赖版本是多少？

**Comment by Gongkaikai** [comment]
> > 两个分支都试过了，都是这个问题
> 
> typescript 依赖版本是多少？

TypeScript: Version 4.4.4
Nodejs: v15.14.0，v12.9.0
macOS 10.14.6
Chrome 95.0.4638.69

**Comment by scottsut** [comment]
> TypeScript: Version 4.4.4 Nodejs: v15.14.0，v12.9.0 macOS 10.14.6 Chrome 95.0.4638.69

类型定义问题，暂时无法复现。这里的代码逻辑没问题，你二开的话自己魔改一下，都设为`any`让编译能够通过，我们后续能够复现了再修复

**Comment by Gongkaikai** [comment]
> 类型定义问题，暂时无法复现。这里的代码逻辑没问题，你二开的话自己魔改一下，都设为`any`让编译能够通过，我们后续能够复现了再修复

好的
