### ISSUE TITLE
数据视图sql书写区域，sql下拉框展示空白

### ISSUE THREAD

**Issue by mrcluo** [running-elephant/datart#1563]
**技术栈**
主应用： qiankun + vue
子应用:   qiankun + datart

**场景：**
本地打开子应用datart，正常
发布到线上环境，sql的下拉框展示空白，但是是可以点击的。功能正常，只是ui不展示。如下图

[
![image](https://user-images.githubusercontent.com/40492120/177079916-7ac7800e-0a52-4e52-82af-e3702515e7c2.png)
](url)

**尝试解决：**
不清楚这边的技术是用什么实现的，这里空白可以提供一个思路吗

**感谢大佬，期望翻牌**

**Comment by Cuiyansong** [comment]
下拉提示框是monaco editor生成的，看一下控制台是否有相关错误提示。

**Comment by Cuiyansong** [comment]
"但是是可以点击的。功能正常，只是ui不展示", 下拉框默认是有值的，当单击之后会显示下拉框的值，是这样吗？

**Comment by mrcluo** [comment]
> "但是是可以点击的。功能正常，只是ui不展示", 下拉框默认是有值的，当单击之后会显示下拉框的值，是这样吗？

嗯嗯，感谢。google搜了很多，发现是qiankun css沙箱未隔离的引发的问题，辛苦你了
