### ISSUE TITLE
仪表板筛选器配置页面新增搜索框

### ISSUE THREAD

**Issue by ems0419** [running-elephant/datart#1572]
**你的功能要求与某个问题相关吗？**
当数据视图量较大且数据视图中的字段较多时，多选下拉列表筛选器的配置页面——取值配置部分没有数据视图/字段搜索框，眼动搜索非常累人。

**形容一下你想要的解决方案**
希望增加对应的搜索框，谢谢

**其他内容**
![image](https://user-images.githubusercontent.com/10233742/177312737-df69283a-d467-4579-b688-f4033c6a356a.png)

**Comment by handsomepjf** [comment]
同名视图也很麻烦，因为这里缺少层级结构
