### ISSUE TITLE
新建/编辑数据图表时搜索字段

### ISSUE THREAD

**Issue by ems0419** [running-elephant/datart#1574]
**你的功能要求与某个问题相关吗？**
编辑/新建数据视图的额页面没有字段搜索框，需要用眼睛来寻找字段，费劲费眼

**形容一下你想要的解决方案**
1、增加字段搜索框
2、允许用户给字段进行自定义分类

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图
![image](https://user-images.githubusercontent.com/10233742/177313406-ff90ec3c-7775-418f-85fe-dd27db3a772d.png)

**Comment by Cuiyansong** [comment]
Duplicate #1362

**Comment by Cuiyansong** [comment]
当前交互是，点击右侧扩展按钮图表，然后选择“搜索字段名称”，即可查询。
