### ISSUE TITLE
Question: Can we add jump option to score chart?

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1575]
Score chart also allows filter. Can we add jump option and also pass the filter value? Does it have to be dimension only?

![image](https://user-images.githubusercontent.com/100477931/177323153-76d874db-1247-48b7-90cc-1dddcbfc14d7.png)

For example, able to click on the viz/number in score chart to see the listing of underlying data for download, etc.

**Comment by scottsut** [comment]
1. About "add jump option to scorecard", we are planning to do it.
2. "to see the listing of underlying data", it's a new feature in the upcoming beta4, called "view detail". But scorecard is not supported in the first batch.

**Comment by clementchong** [comment]
ok, thank you for including it in the plan!

**Comment by lyp000119** [comment]
![image](https://user-images.githubusercontent.com/32259371/182827567-4820593a-d2ee-472a-a598-83bb22dacbfc.png)
