### ISSUE TITLE
数据视图美化SQL导致预置变量不可执行

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1585]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
数据视图美化SQL导致预置变量前后加了空格执行失败

**To Reproduce**
1. 新建带变量数据视图
2. 点击美化
3. 发现$前后加了空格

**Expected behavior**
对变量判断不要加空格

**Screenshots**
![图片](https://user-images.githubusercontent.com/49897998/177676860-9eefd0a3-9392-4b5f-a2a2-f9e8c971400d.png)
![图片](https://user-images.githubusercontent.com/49897998/177676975-fc0637e9-b59c-48a2-b4ca-848792b17c1b.png)

**Comment by scottsut** [comment]
美化功能目前确实是有问题的
