### ISSUE TITLE
Small issue with label in percentage stack column chart

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1588]
**Datart Version**
1.0.0b3

**Describe the bug**
When we use the percentage stack column chart, it is understood the bars always add up to 100%. When we also set numeric format and prefix/suffix to the metric, the setting is also inherited by the label which is not correct.

**To Reproduce**

**Expected behavior**
The labels should always be in percentage. Either introduce a checkbox to display the % sign or hardcode % as a suffix to the label.

**Screenshots**
![image](https://user-images.githubusercontent.com/100477931/177697274-f850c584-b0f3-4683-9dfc-d0e6235c0a04.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。

**Comment by clementchong** [comment]
> 感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。

好的，谢谢你！
