### ISSUE TITLE
Feature: Can the chart axis scale align with metric format?

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1593]
When we set the metric to use provided format like M for millions and K for thousands, the labels display well. However, it would be better if the scale on the axis can display the same.

Eg: below has the Y-axis still showing numbers in full.
![image](https://user-images.githubusercontent.com/100477931/177749563-7317726a-f21f-4291-8b03-c547609e3403.png)

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。

**Comment by clementchong** [comment]
> 感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。

好的！谢谢你！
