### ISSUE TITLE
启动脚本格式错误，启动报$'\r': 未找到命令

### ISSUE THREAD

**Issue by liqiuhong1** [running-elephant/datart#16]
[root@localhost bin]# sh datart-server.sh
datart-server.sh:行2: $'\r': 未找到命令
datart-server.sh:行18: $'\r': 未找到命令
datart-server.sh:行20: $'\r': 未找到命令

**Comment by wuguozhu** [comment]
我也遇到这个问题，我是这么解决的
```
sed -i 's/\r//g' datart-server.sh
```

**Comment by zhouwenblog** [comment]
datart-server-1.0.0-alpha.0-install\datart-server-1.0.0-alpha.0\bin\datart-server.sh
安装包里面的这个文件格式不正确，需要转换成linux 格式，目前gitlab上发布版压缩包里面的文件是dos格式
源代码里面是linux格式
可以临时使用vi 
:set ff=unix
解决
