### ISSUE TITLE
控制器：日期组件 按年筛选无效

### ISSUE THREAD

**Issue by jy147154** [running-elephant/datart#1603]
**Datart版本号**
0.3最新版本

**错误描述**

控制器：日期组件 按年筛选数据无效，选择有数据的年后显示空数据
对应的图表都已选上，有数据，MYSQL内字段为date格式

月，周，日筛选都有效，就是年筛选不行，尝试了各种新建和已有的图表都不行

**截图**

![Dingtalk_20220708172741](https://user-images.githubusercontent.com/76261388/177963012-a01682fe-d084-4128-a915-74286b612edc.jpg)
![Dingtalk_20220708172759](https://user-images.githubusercontent.com/76261388/177963029-b15cc510-7407-4258-bceb-b0ad9c245d70.jpg)

**Comment by scottsut** [comment]
日期控制器为独立时间点选择，你的诉求应该使用日期范围控制器
