### ISSUE TITLE
下载表头

### ISSUE THREAD

**Issue by baymaxLove** [running-elephant/datart#1604]
**Datart版本号**
Beta3.0

**错误描述**
下载表头不是别名

**如何重现**
重现错误的步骤，例如：
任何下载Excel 表头都是字段名

**期望结果**
下载Excel 表头是别名

**截图**

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: [例如 Windows 10]
- 数据源: [例如  MySQL 8.0.26]
- 浏览器: [例如 chrome 94, safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by scottsut** [comment]
beta.4 已经修复
