### ISSUE TITLE
validate function computed field failed 优化

### ISSUE THREAD

**Issue by scottsut** [running-elephant/datart#1616]
**Datart Version**
The version of `datart` you using.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
