### ISSUE TITLE
SQLEditor.tsx type error

### ISSUE THREAD

**Issue by caiiansheng** [running-elephant/datart#162]
缺少开发文档
本地开发，前端报错
![image](https://user-images.githubusercontent.com/26760483/140494712-85909c4e-4fc3-4506-a7c9-f7583736821a.png)

**Comment by scottsut** [comment]
请提供 `typescript`、`react-monaco-editor`、`monaco-editor` 依赖具体版本

**Comment by caiiansheng** [comment]
typescript@4.4.4
react-monaco-editor@0.43.0
monaco-editor@0.30.0

**Comment by scottsut** [comment]
Reproduced, `monaco-editor@0.30.0` caused the problem.
