### ISSUE TITLE
控制器文本内容字体颜色无法做控制

### ISSUE THREAD

**Issue by handsomepjf** [running-elephant/datart#1621]
**Datart Version**
The version of `datart` you using.
1.0.0-beta.3 release
**Describe the bug**
控制器文本内容字体颜色无法做控制，如果我选择深色背景图，然后控制器背景选择为透明，那么黑色得字体将让我很难看清楚。
![image](https://user-images.githubusercontent.com/63778314/178419355-deb22b39-0154-4e4d-b070-b54103cfd863.png)

**Expected behavior**
我希望控制器字体颜色能在某个地方做控制，例如计时器一样

**Comment by scottsut** [comment]
Duplicate of #1028
