### ISSUE TITLE
分享的仪表板/故事板无法联动

### ISSUE THREAD

**Issue by JoshTseeee** [running-elephant/datart#1628]
**Datart版本号**
1.0.0-beta4

**错误描述**
分享出去的仪表板无法联动

**如何重现**
由于升级了beta4, 重新创建视图, 绑定联动关系, 在系统里操作仪表板可以正常联动, 但是分享出去的链接中仪表板无法实现联动, 重新分享也如此

**截图**
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/26848111/178620989-1d948e49-f6a6-4d27-982e-3d578d6fb14e.png">

**Comment by Cuiyansong** [comment]
Support Share Chart/Dashboard Drill And Link #1662

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
