### ISSUE TITLE
修改图表聚合方式时，不清空图表配置

### ISSUE THREAD

**Issue by jxllq1** [running-elephant/datart#1629]
**Is your feature request related to a problem? Please describe.**
当添加了多个计算字段时，如计算占比，图表默认开启数据聚合，此时需如果需要关闭数据聚合，会清空图表所有配置。
我需要重新写计算字段

**Describe the solution you'd like**
期望与图表切换数据集一样，不清空图表配置。

**Describe alternatives you've considered**

**Additional context**
<img width="961" alt="image" src="https://user-images.githubusercontent.com/20063892/178635153-f4e11554-1c57-4df1-83e7-4f49beaa3876.png">

**Comment by Cuiyansong** [comment]
切换聚合方式，之前的计算字段也被清空，这是一个BUG，目前已在RC.0版本修复。
