### ISSUE TITLE
报表下载 Excel 表头可否在设置别名的情况下，优先使用别名

### ISSUE THREAD

**Issue by ParkerJX** [running-elephant/datart#163]
**形容一下你想要的解决方案**
报表下载 Excel 表头可否在设置别名的情况下，优先使用别名

**目前是这样的，如图**
![image](https://user-images.githubusercontent.com/15976650/140495628-6eaa179f-8bd3-452e-b528-75ca8f4f7bbe.png)

**Comment by scottsut** [comment]
beta.3 版本已支持
