### ISSUE TITLE
拖入字段接口请求完成之后再去渲染图表

### ISSUE THREAD

**Issue by dandanwy** [running-elephant/datart#1633]
**你的功能要求与某个问题相关吗？**
拖入字段配置图表渲染一次，请求接口回来又渲染一次图表

**形容一下你想要的解决方案**
希望可以等数据请求完成之后去渲染图表

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by Cuiyansong** [comment]
- 对于请求返回时间大于500ms的请求，增加Lazy Loading并在数据返回后渲染如表
- 对于请求返回时间小于500ms的请求，不做Lazy处理，因界面刷新及响应速度快，并且能避免闪屏效果。
