### ISSUE TITLE
点击下钻没有带上过滤条件

### ISSUE THREAD

**Issue by qxqzx13** [running-elephant/datart#1644]
**Datart版本号**
声明一下你正在使用的 `datart` 版本号
beta.4

**错误描述**
点击下钻没有带上过滤条件

**截图**
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/48074792/178956918-1bdccd50-0f77-4c26-97e9-b54b57ec878e.png">

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
