### ISSUE TITLE
View Toolbar moves away after coming back from other menu page

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1650]
**Datart Version**
Demo site 1.0.0b4

**Describe the bug**
The view toolbar location is not fixed. After coming back to view from other menu pages, the toolbar moves to the right.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/100477931/179147748-ce879127-497f-4102-a666-c0c668be3381.png)

![image](https://user-images.githubusercontent.com/100477931/179147890-1e652492-11ef-495e-b113-18ac1d119938.png)

![image](https://user-images.githubusercontent.com/100477931/179147961-e063b645-029c-4157-ba43-d0c0494310a7.png)

![image](https://user-images.githubusercontent.com/100477931/179148015-48968322-9de3-4873-976e-77725d055787.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
Please verify this issue on RC.1, if it still exist, please reopen this issue.
