### ISSUE TITLE
数据视图字段名称中带 / 导致解析失败

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1652]
**Datart Version**
1.0.0-beta3

**Describe the bug**
数据视图字段名称中带 / 导致解析失败

**Expected behavior**
正常解析

**Screenshots**
![图片](https://user-images.githubusercontent.com/49897998/179171059-faa5d413-2ba6-4cdc-9f67-001a1243e103.png)
![图片](https://user-images.githubusercontent.com/49897998/179171148-fbddb8f0-e7d0-4d23-80c2-ddcd2dd09367.png)

**Comment by scottsut** [comment]
> @scottsut @Cuiyansong 这个和 #1632 是同样的错误码？

对，是一样的问题，这个 issue 先关闭了，我们在 #1632 中跟踪进度

**Comment by scottsut** [comment]
不是一样的问题

**Comment by Cuiyansong** [comment]
问题无法复现，如仍然有此类问题请留言。
