### ISSUE TITLE
点击目录无法展开收起，只能通过点击小图标展开收起，建议优化

### ISSUE THREAD

**Issue by leeegeng** [running-elephant/datart#1667]
**Is your feature request related to a problem? Please describe.**
目前只能通过点击小的三角符号展开，不易用，建议点击目录项，直接展开、折叠目录
**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/52368324/179453491-70d4c637-db1f-4d00-bb9c-86fd90b988dc.png)
![image](https://user-images.githubusercontent.com/52368324/179453561-14540c90-9db7-4cb2-add2-50ead6180781.png)

**Comment by lyp000119** [comment]
https://user-images.githubusercontent.com/32259371/182825808-f817e0f5-cdc5-427d-a31c-1b094be9bf4d.mp4
