### ISSUE TITLE
联动 打开方式 设置为 "对话框"时 打开的对话框是一个 "mini的datart" 

### ISSUE THREAD

**Issue by zhu-mingye** [running-elephant/datart#1669]
**Datart Version**
beta4

**Describe the bug**
联动 打开方式 设置为 "对话框"时 打开的对话框是一个 "mini的datart" 这个不太友好 事实上 仅展示表格数据 或者图表数据  而不需要左侧侧边栏

**To Reproduce**
1. 创建仪表盘 
2. 配置 跳转设置
3. 打开方式 设置为 "对话框" 其他自行选择
4. 保存后点击某条数据 可见下图

**Expected behavior**
不太友好  查看数据不直观

**Screenshots**

![图片](https://user-images.githubusercontent.com/58576849/179460309-6ff8f9cf-2777-41f6-ab14-bed576f4440e.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: centos7
 - Source Database:  MySQL 8
 - Browser:  chrome  

**Additional context**

**Comment by lyp000119** [comment]
![image](https://user-images.githubusercontent.com/32259371/182826866-5ba0a939-807b-48aa-86d4-3e64c84d6411.png)
