### ISSUE TITLE
修改数据视图字段类型，数字被额外加.0

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1670]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
创建数据连接，将年份修改为字符串类型，结果 2020 变成了 2020.0

**Expected behavior**

**Screenshots**
![图片](https://user-images.githubusercontent.com/49897998/179480047-ea288711-3346-422f-ba83-8861119691f5.png)
![图片](https://user-images.githubusercontent.com/49897998/179480114-6394cc81-696e-43e6-8f25-d2394ee006d7.png)
![图片](https://user-images.githubusercontent.com/49897998/179480234-b2b478ab-930b-4cbf-bbdf-f40ddb409f9c.png)
[测试202207181458.xlsx](https://github.com/running-elephant/datart/files/9130771/202207181458.xlsx)

**Comment by Plume3362** [comment]
@scottsut

**Comment by Cuiyansong** [comment]
无法复现，如有问题请留言。
