### ISSUE TITLE
关于数据库模式同步的异常处理

### ISSUE THREAD

**Issue by q1139168548** [running-elephant/datart#1679]
**Datart Version**
1.0.0-beta4

**Describe the bug**
由于数据库结构同步时，会对所有表和视图进行 `show columns` 操作，如果此时数据库账号的权限不足，则会抛出异常，现在的代码逻辑是将 `SQLException` 直接throw至上层，这会导致整个数据库结构同步操作失败，其他有权限的已经正常获取到的数据库结构会因为此异常而丢弃，从而在页面上看不到任何数据库结构信息。

**Comment by tianlu-root** [comment]
这里的SQLException不只是包含了权限导致失败的问题。还包括连接超时，数据库本身兼容等很多原因导致的失败。这些情况中任何一种情况发生时，都必须终止整个数据库同步操作，以保证数据库同步操作的一致性。并且明确地抛出错误原因。而不是简单的返回一个空数据让程序看起来执行成功了，这个数据很可能是一个脏数据。 如果是权限导致的同步失败，应该有两个方面来解决这个问题：1、用户端解决，为datart的数据源账号分配足够的权限。 2、代码中能够识别出是权限问题并且只处理权限导致的异常。否则在这里粗糙的直接处理SQLException这种方式肯定是不可行的。

**Comment by q1139168548** [comment]
了解了，我这发生这个问题的背景是，我们的Mysql里有大量的视图，所以产生了一些奇奇怪怪的权限问题，直接catch异常确实有点粗糙
