### ISSUE TITLE
数据图表交互功能分享页面没有生效。

### ISSUE THREAD

**Issue by b15952025503** [running-elephant/datart#1688]
**Datart Version**
beta4 版本

**Describe the bug**
数据图表配置了交互功能里面的跳转设置，当前页面点击是可以跳转的，但是分享后的页面点击没有发生跳转的事件。

**To Reproduce**
1.开始分析配置一个数据图表
2. 配置图表的交互功能为左键点击链接跳转
3. 保存发布进行分享link的生成
4. 访问分享链接然后点击触发

**Expected behavior**
基于图表分享之后的页面交互功能可以正常使用

**Screenshots**
![1658296473075](https://user-images.githubusercontent.com/45256950/179907131-911ee76e-fdf5-42b1-9fde-98da8eef0cfb.png)

**Environmental details: (optional, depending on where the bug occurs)**
demo环境 
http://datart-demo.retech.cc/
http://datart-demo.retech.cc/organizations/39c5c9bf187642478f225d687f675860/vizs/chartEditor?dataChartId=3c5932a011844aa0bfbfa6dd47b931e9&chartType=dataChart&container=dataChart

**Comment by Cuiyansong** [comment]
share chart, share dashborad的跳转/联动/查看数据将在下一个版本（RC.0）支持。RC.0预计近期发布。
当前issue关闭，请关注新版本。
