### ISSUE TITLE
图表-移至回收站后再还原，还原后的图表无法下载excel

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1689]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
图表-移至回收站后，然后再还原， 还原后的图表因名称不合法无法下载 excel格式

![图片](https://user-images.githubusercontent.com/49897998/179926979-5cbfa2dc-a7dc-4403-8c5b-b6eac8d6c787.png)
![图片](https://user-images.githubusercontent.com/49897998/179926873-4091bdfb-7d4c-465a-abd1-6c71939f389d.png)

**Comment by Plume3362** [comment]
@scottsut

**Comment by qxqzx13** [comment]
现在还原后可以修改名称， 名称内不携带 ‘.’ 即可下载
