### ISSUE TITLE
着色功能不能使用

### ISSUE THREAD

**Issue by llf007** [running-elephant/datart#1702]
**Datart版本号**
1.0.0-beta.4

**错误描述**

**1、不能自义定对饼图，每个饼区着色**
![001](https://user-images.githubusercontent.com/60683568/180143204-fcad3c61-3d66-49af-a436-4a39bd83d261.png)

**2、选择颜色主题，显示undefined，不起作用**
![002](https://user-images.githubusercontent.com/60683568/180143225-6297d3a8-55e6-4823-8a2d-5e2f7d040c29.png)

**其他内容**
其他柱图、线图等图表，也不能改颜色。

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
