### ISSUE TITLE
可视化使用衍生的时间聚合字段做筛选时报错

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1707]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
新建可视化使用衍生的时间聚合字段做筛选时，会把衍生的字段依旧当作时间类型做筛选

**To Reproduce**

**Expected behavior**
![图片](https://user-images.githubusercontent.com/49897998/180173285-49c8eee7-2f62-44ce-b6e0-791f503e48a2.png)
![图片](https://user-images.githubusercontent.com/49897998/180173308-f98e7b7d-aeec-4144-ade0-154d90c48393.png)
![图片](https://user-images.githubusercontent.com/49897998/180173340-13fd1045-4d8c-4d56-856a-ef73f24362b9.png)
@scottsut

**Comment by stillsilly** [comment]
这个已经修复了，前端处理，衍生字段不能拖到筛选
#1463 
@scottsut  issue可以关掉，谢谢
