### ISSUE TITLE
数据视图，保存、详情、另存为等icon被顶出屏幕外

### ISSUE THREAD

**Issue by jxllq1** [running-elephant/datart#1710]
**Datart版本号**
beta.4

**错误描述**
进行相关操作之后，操作按钮看起来消失了，实际是被顶出了屏幕外。
如截图：
<img width="884" alt="image" src="https://user-images.githubusercontent.com/20063892/180211890-16063cc0-ad0f-4103-9bcf-acc0474a375f.png">

**如何重现**
重现错误的步骤，例如：
1. 到数据视图页面，点击一个普通的sql视图。（表视图不存在该问题）
2. 点击 执行 ，执行sql，得到结果后，点击右侧可视化导航，查看某个看板
3. 再回到 数据视图时，
4. 看到数据视图的操作功能icon被顶出页面。

**期望结果**
功能操作icon保留在原位。

**截图**
![Kapture 2022-07-21 at 20 24 22](https://user-images.githubusercontent.com/20063892/180212845-2ceb84f3-dcd4-464d-b45e-7f5b1c162d42.gif)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: [例如 Windows 10]
- 数据源: [例如  MySQL 8.0.26]
- 浏览器: [例如 chrome 94, safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by Cuiyansong** [comment]
感谢提出ISSUE，问题已修复，如复现请留言。
