### ISSUE TITLE
仪表板实现透明效果

### ISSUE THREAD

**Issue by wujing521** [running-elephant/datart#1711]
在实际操作仪表板的时候未对图表和仪表板添加任何背景，但是实际分享出去还是会有白色的背景
![image](https://user-images.githubusercontent.com/54877096/180217180-e2e29d97-6de8-49f0-b840-b6022254e4da.png)
![image](https://user-images.githubusercontent.com/54877096/180217222-2670106a-31d6-4f22-9f88-dd5172305b24.png)

**Comment by Cuiyansong** [comment]
目前RC.1版本已支持仪表板设置不同颜色以及透明色，可以在背景颜色设置的时候，选择更多，然后将透明度致为0即可。
