### ISSUE TITLE
图表过滤维度字段计数聚合保存后 无法回显

### ISSUE THREAD

**Issue by qxqzx13** [running-elephant/datart#1717]
**Datart版本号**
beta.4

**错误描述**
![image](https://user-images.githubusercontent.com/48074792/180403087-81f9898f-e66c-4e3d-b520-e1678c6264be.png)
table 添加维度字段 使用计数聚合， 保存后再次打开 无法回显

**Comment by Cuiyansong** [comment]
目前RC.0版本无法复现问题，请提供详细步骤或者能提供复现步骤的视频
