### ISSUE TITLE
编辑并删除分享后的链接，再添加链接报错

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1721]
**Datart Version**
1.0.0-beta.3

**To Reproduce**
1.选择仪表盘或者故事板中的数据记录，点击分享管理
2.点击【添加链接】
3.链接添加成功后，点击【操作】并保存
4.修改成功后，点击【删除】
5.删除成功后，点击【添加链接】
![图片](https://user-images.githubusercontent.com/49897998/180422022-a000833b-23d1-414b-8bc8-aca1a6a4c531.png)
![图片](https://user-images.githubusercontent.com/49897998/180422084-7cb649a9-06c0-4cce-954a-15c3970c337f.png)
![图片](https://user-images.githubusercontent.com/49897998/180422136-3171472b-8490-437e-80ec-9f33051574d7.png)
![图片](https://user-images.githubusercontent.com/49897998/180422307-51cc165c-1887-4cb2-be6c-1997a2f25e57.png)
@scottsut

**Comment by Cuiyansong** [comment]
感谢贡献，RC.0版本已修复，如有问题请留言。
