### ISSUE TITLE
图表条件样式字段下拉框选项宽度过小导致显示不全信息

### ISSUE THREAD

**Issue by Cuiyansong** [running-elephant/datart#1724]
**Datart Version**
RC.0

**Describe the bug**
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/4497555/180595801-e693c549-554c-41ad-a137-93fe3f43e076.png">

**Comment by Cuiyansong** [comment]
Issue 2: 字段也没有显示设置的别名

**Comment by lyp000119** [comment]
![image](https://user-images.githubusercontent.com/32259371/182825324-5467d6f5-fb0b-4e57-a8ca-c4fc08c7cd4d.png)
