### ISSUE TITLE
只有查看权限的账号看到了未发布的故事板

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1735]
**Datart Version**
1.0.0-beta.4

**Describe the bug**
对一个账号只赋予某个未发布的故事板 查看权限，该账号的演示列表里有该故事板

**To Reproduce**
1.新建故事板
2. 对一个账号只赋予 查看权限
3. 登录该账号，发现可以看到未发布的故事板

![图片](https://user-images.githubusercontent.com/49897998/180711610-be808f44-6f84-4530-a6b4-93043a1cbe95.png)
![图片](https://user-images.githubusercontent.com/49897998/180712043-0ede81b5-ea09-46e8-9cf7-9059d1fc430f.png)
@scottsut

**Comment by Cuiyansong** [comment]
Related to Resource Permission Issue, @qxqzx13 please look at it.
