### ISSUE TITLE
分享链接的下载功能建议

### ISSUE THREAD

**Issue by gaofei8704** [running-elephant/datart#1739]
**你的功能要求与某个问题相关吗？**
beta3以后，分享链接的下载功能已经屏蔽掉了，但是点击按钮还存在：
![image](https://user-images.githubusercontent.com/4240872/180731886-15ba19a8-c695-4b92-89b7-26e13ed60d46.png)

**形容一下你想要的解决方案**
能否将下载做成配置式的功能，类似参数一样，或者通过分享链接内的内容来控制是否可以下载

**Comment by scottsut** [comment]
目前不太倾向这样实现。屏蔽下载是为了避免权限问题，而希望分享页提供下载功能的用户多半是将分享页嵌入到自有应用中使用，同时希望分享页拥有应用内一样的功能。我们后续会尽量提升主应用的集成便利度，让用户直接集成主应用来满足诉求

**Comment by Cuiyansong** [comment]
我们会在最新的ISSUE中更新修复细节，issue #1751
