### ISSUE TITLE
建议图表字段自动填充别名信息

### ISSUE THREAD

**Issue by hds1999** [running-elephant/datart#1744]
**你的功能要求与某个问题相关吗？**
 

**形容一下你想要的解决方案**
建议在图表编辑的时候，拖拽字段，自动根据模型中字段的名称填充给图表字段的别名，如下图示例：
![image](https://user-images.githubusercontent.com/20547693/180911570-1d2b985e-13f8-4be0-8343-298221eb133a.png)

![image](https://user-images.githubusercontent.com/20547693/180911525-2f5bf603-8f9c-4b88-8893-e939b5bef28f.png)

**描述一下你考虑过的备选方案** 

**其他内容**

**Comment by Cuiyansong** [comment]
这样是不是就丢失了“聚合”方式的信息，如果再次拖入“售价”，别名如何显示？

**Comment by hds1999** [comment]
聚合方式和别名应该是没有关系的。

**Comment by Cuiyansong** [comment]
SUM(XXXXXX别名)这种？
