### ISSUE TITLE
可视化跳转参数不对

### ISSUE THREAD

**Issue by caiiansheng** [running-elephant/datart#175]
**错误描述**
视图设置跳转，关联字段后，点击调转，跳转带入的参数是指标属性及值，这个是不对的，应该是传入维度的属性及值

**如何重现**
必现

**期望结果**
视图设置跳转，关联字段后，点击调转，应该是传入点击视图的维度的值,不应该传指标的属性及值

**Comment by scottsut** [comment]
Duplicate of #132
