### ISSUE TITLE
分享链接下载功能不可用 建议将分享的下载功能剔除

### ISSUE THREAD

**Issue by zhu-mingye** [running-elephant/datart#1751]
**Datart版本号**
beta4

**错误描述**
自前两个版本  分享链接中的下载功能已经不可用 但目前仍然保留 给使用者造成错觉 认为可用  

**如何重现**
重现错误的步骤，例如：
1. 分享
2. 使用者点击链接
3. 右上角三个点 展开 点击三个点 点击下载
4. 可见下载错误
5. 后台日志error NPE

**期望结果**
删除此功能按钮 或者其相关功能

**截图**

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: [例如 Windows 10]
- 数据源: [例如  MySQL 8.0.26]
- 浏览器: [例如 chrome 94, safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by Cuiyansong** [comment]
link same issue https://github.com/running-elephant/datart/issues/1739
