### ISSUE TITLE
datachart过滤条件类型为包含的时候，如果清除掉输入的值会报错

### ISSUE THREAD

**Issue by KANLON** [running-elephant/datart#1754]
**Datart Version**
版本: 1.0.0-rc.0

**Describe the bug**
datachart过滤条件类型为包含的时候，如果清除掉输入的值会报错

**To Reproduce**
1. 从view进入分析页面，选择某些字段为筛选条件
2. 设置文本类型的筛选条件为 条件，"包含",如下图，并且随便输入一个默认值

![image](https://user-images.githubusercontent.com/22886101/181144686-f7eff4d0-12aa-437d-926a-ae7ad2b53396.png)

4. 保存，查看该datachart表格
5. 在表格筛选条件中，把默认值去掉，报错了

![image](https://user-images.githubusercontent.com/22886101/181144889-91a3003b-f4ff-4855-9a69-f9912aba3af6.png)

**Expected behavior**
应该清空掉默认值不报错，处理的数据结果应该是不过滤的数据结果的

**Screenshots**
![image](https://user-images.githubusercontent.com/22886101/181145000-7102b2de-a7f7-466e-aad0-adba69db15f3.png)

**Environmental details: (optional, depending on where the bug occurs)**
 -  Windows 10
 - Chrome/103.0.0.0

**Additional context**
http://datart-demo.retech.cc/organizations/b14ac7aed7f54ad986f5644f06f4a77d/vizs/0a3a2cd083ca4380a6412210006caf8d
直接访问这个demo页面，把过滤器去掉就可以看到结果

**Comment by Cuiyansong** [comment]
期望的方式是，当清空包含内容时，去掉当前的过滤条件，而不是包含“空值”，对吗？如果是的话，这一点可以改进。

**Comment by KANLON** [comment]
对的
