### ISSUE TITLE
图表编辑页面导出的图表没有带标题

### ISSUE THREAD

**Issue by hds1999** [running-elephant/datart#1756]
**Datart版本号**
版本: 1.0.0-rc.0

**错误描述**
图表编辑页面导出的图表没有带标题，保存后导出是带标题的。

**如何重现**
重现错误的步骤，例如：

**期望结果**
清晰简洁地描述你期望的结果是什么

**截图**
 
![image](https://user-images.githubusercontent.com/20547693/181158170-5f2a05c6-b634-40f4-aacd-47b56b9ecf30.png)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS:centos
- 数据源: clickhouse
- 浏览器: chrome 

**其他内容**

**Comment by scottsut** [comment]
编辑页为临时结果导出，图表可能都没有保存没有标题，因此统一不带标题
