### ISSUE TITLE
Sql parse bug

### ISSUE THREAD

**Issue by lbship** [running-elephant/datart#1758]
version: 1.0.0-beta.4
SQL:SELECT * FROM  ( select b.parentuserid,b.parent_account,  sysCreateTime as 时间,ctno as 卡号,'消费' as 状态,ticketsn as 单号,a.clientorderid as 交易单号,a.userid,b.company as 消费门店,a.addname as 收银员,a.cardtype as 卡类型,a.cmoney as 消费金额,a.allbalance as 当前剩余金额,  null as 备注   from   haolilaiconsume a  inner join (  select c.id as parentuserid,c.account as parent_account,a.id as userid,a.account,a.company,d.regionaluserid,e.account as regional_account   from user a   left join usergroup b on a.id=b.userid   left join user c ON b.parentuserid = c.id  left join regionalgroup d on a.id=d.userid  left join user e on d.regionaluserid=e.id  where c.account in ('hq','n_00','cz0','hz','nb0')  union select  469  as parentuserid,'r25'  as parent_account,46 as userid,'null' as account,'演示' as company,null as regionaluserid,null as regional_account  ) b on a.userid=b.userid  where (account=$DATART_USER_USERNAME$) )  AS `DATART_VTABLE` LIMIT 1000 OFFSET 0 
DB: MYSQL 
EXCEPTION:org.apache.calcite.sql.parser.SqlParseException: Encountered "user" at line 1, column 442.
Was expecting one of:
    "LATERAL" ...
    "TABLE" ...
    "UNNEST" ...
    "SPECIFIC" ...
    <IDENTIFIER> ...
    <HYPHENATED_IDENTIFIER> ...
    <QUOTED_IDENTIFIER> ...
    <BACK_QUOTED_IDENTIFIER> ...
    <BRACKET_QUOTED_IDENTIFIER> ...
    <UNICODE_QUOTED_IDENTIFIER> ...
    "(" ...

**Comment by scottsut** [comment]
user 关键字需要处理一下

datart 是通用型工具，对特定数据库的语法支持能力很难做到客户端工具级别，需要手动处理关键字问题
