### ISSUE TITLE
表视图的关联关系保存不住

### ISSUE THREAD

**Issue by allentern** [running-elephant/datart#1759]
Datart版本号
版本: 1.0.0-rc.0

错误描述
表视图中，关联关系不显示字段名，即使选择了字段，仍然显示表名。保存后再次打开视图，关联关系丢失。

如何重现
1.新建数据视图-表视图方式，
2.选择主表，选择表连接，
3.设置关联关系，选择字段，但仍然显示表名。
4.保存，
5.再次打开视图，关联关系丢失。

期望结果
1.关联关系能保存。
2.关联字段正确显示字段名。

截图
![image](https://user-images.githubusercontent.com/776181/181186321-cc639895-2fd5-4c7c-ad35-dc73d399fb50.png)

运行环境详情：(可选，取决于错误发生的具体位置)

OS:centos
数据源: mysql
浏览器: chrome
其他内容

**Comment by allentern** [comment]
> 请打开浏览器控制台，提供一下保存时的请求参数

在跑象demo环境，新增了一个数据视图，通用的问题，参见截图：
![datart表视图-关联字段保存不住](https://user-images.githubusercontent.com/776181/181594247-8119dcf1-5937-45d5-9c2b-6695d459ee80.png)

**Comment by scottsut** [comment]
其实保存住了，没有正确反显。这个问题会尽快发 hotfix
