### ISSUE TITLE
Question: Any reason why QTRZ_* table names are in uppercase?

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1761]
Like to understand why all the QRTZ tables having uppercase names. We have an issue when migrating database export from windows to linux environment.

![image](https://user-images.githubusercontent.com/100477931/181245716-e0b04705-b9ce-4370-87bc-ef17a5679c18.png)

**Comment by Cuiyansong** [comment]
what is the issue detail when migration with UpperCase name?

**Comment by clementchong** [comment]
> what is the issue detail when migration with UpperCase name?

Windows default to lowercase. If we export database and import to another environment like Linux, we get error during startup

**Comment by Cuiyansong** [comment]
It seemed the QRTZ name is setup with default uppercase by [Quartz Scheduler](http://www.quartz-scheduler.org/documentation/quartz-2.0.2/configuration/ConfigMain.html), and some db is case-sensitive on windows system, one solution is change db default sensitive setting, e.g. [mysql document](https://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html)

**Comment by clementchong** [comment]
> It seemed the QRTZ name is setup with default uppercase by [Quartz Scheduler](http://www.quartz-scheduler.org/documentation/quartz-2.0.2/configuration/ConfigMain.html), and some db is case-sensitive on windows system, one solution is change db default sensitive setting, e.g. [mysql document](https://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html)

Ok noted. Thank you.
