### ISSUE TITLE
报表保存为excel 成功， 保存为图片出错

### ISSUE THREAD

**Issue by yanni-coffee** [running-elephant/datart#1766]
**Datart Version**
rc1

**Describe the bug**
export to picture or pdf  

**Screenshots**

![image](https://user-images.githubusercontent.com/101331516/181442369-ec0bb921-2f08-4bd2-a7a2-87c1a8ce7052.png)

**Comment by bestGao** [comment]
导出pdf 图片都报错，已经配置了standalone-chrome 启动了4444端口还是不行

**Comment by scottsut** [comment]
请按照 issue 模板正确描述问题
