### ISSUE TITLE
新建图表先把字段已有的属性拖到筛选后就可以再拖到字段中

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1783]
**Datart Version**
1.0.0-rc.0

![图片](https://user-images.githubusercontent.com/49897998/182124815-ee635745-e2bf-4f4d-9670-50d489afbc08.png)
![图片](https://user-images.githubusercontent.com/49897998/182124851-107c8dc2-0c3c-4ab9-b5fb-27b1c33f325b.png)
然后将筛选中的属性上移
![图片](https://user-images.githubusercontent.com/49897998/182124920-5406487c-6fff-44b6-9510-e23496b357a7.png)

**Comment by Cuiyansong** [comment]
link pr #1818

**Comment by Cuiyansong** [comment]
对于字符串和日期类型是不允许重复的，但是指标类型，因为可以修改聚合方式，所以是可以拖拽重复的。
