### ISSUE TITLE
发现前端代码中写死了某些版本信息，并且该版本大小写跟/sys/info接口返回的不一样，有点疑问

### ISSUE THREAD

**Issue by KANLON** [running-elephant/datart#1789]
**你的功能要求与某个问题相关吗？**
发现前端代码中写死了某些版本1.0.0-RC.0  信息，并且该版本大小写跟/sys/info接口返回的不一样，有点疑问，/sys/info 接口返回的版本名称都是小写的，但是这次前端的版本 为 1.0.0-RC.0   大写的

**形容一下你想要的解决方案**
希望前端版本能跟接口的版本保持一样，都是小写，我看前端之前的版本也是小写，希望能统一一样

**描述一下你考虑过的备选方案**
最好希望能考虑前端的版本信息获取都全部通过 /sys/info 接口获取

**其他内容**
接口返回的版本
![image](https://user-images.githubusercontent.com/22886101/182284934-c9e3c835-49c9-4e5e-9dcd-2654a01871e2.png)

前端代码写死的版本
![image](https://user-images.githubusercontent.com/22886101/182285099-1f2491ab-a1f7-437d-b853-85eb484768e5.png)

**Comment by Cuiyansong** [comment]
目前代码中，RC都是大写的，你这个数据可能是dev当时一个版本的脏数据？

**Comment by Cuiyansong** [comment]
sysinfo下面的version是后端打包的时候编译进去的，截图中是前端用的，虽然有大小写不一致，但不应该有影响

**Comment by KANLON** [comment]
我这边初步看是没有影响的，只是我们这边在做前后端分离，只是看到这个有点不统一，所以有疑问，想着如果你们方便修改最好可以修改为统一的？

**Comment by Cuiyansong** [comment]
我们以后会注意大小写问题
