### ISSUE TITLE
设置每周第一天是哪一天的配置参数

### ISSUE THREAD

**Issue by wbjsly** [running-elephant/datart#1792]
环境：Beta 1.0.0-rc.0
客户端语言：中文和English切换前后对比
现象：当客户端语言是English时默认每周第一天是周日，而当语言是中文时默认每周第一天是周一
问题：这会导致相同的报表，不同语言环境的人看到的统计数据不一致
期望：
1、有设置每周第一天是哪一天的配置参数
2、服务器端取本周时间范围的逻辑，不应该受到客户端语言环境的影响（不该取客户端的语言来作为判断本周时间范围条件）
![image](https://user-images.githubusercontent.com/25900538/182311277-559f8e6a-268a-433d-952f-8e9988896272.png)
![image](https://user-images.githubusercontent.com/25900538/182311328-798af8de-3f0d-41e0-9459-2c2139fbcf26.png)
@scottsut

**Comment by Cuiyansong** [comment]
如果能在用户Profile管理界面切换时区会不会更方便？

**Comment by wbjsly** [comment]
> 
1、在客户端切换时区，存在让C端用户还要理解不同时区的每周第一天具体是哪一天（周六、周日或周一）的认知学习。达到的目的其实也是通过时区来明确设置每周第一天是哪一天。
2、第一种方式是在服务器端设置每周第一天是哪一天，默认按照总部所在地区规则来设置，当然也可以设置为从客户端取。
      第二种方式是取客户端的设置，这个在实际C端用户对数据前需要先校正统一好否则会存在统计口径不一致而对不上数据的现象。若涉及跨多地域用户来说会是个麻烦事。
3、建议你们参考一下Datart的实际是使用用户的地域范围和业务覆盖范围来考虑如何优化。

**Comment by Cuiyansong** [comment]
第几周，以及周一的定义目前是根据语言环境自动识别的，参考[MomentJS](http://momentjs.cn/docs/#/use-it/)说明；从业务的角度来讲，目前如果没有给用户开放更改语言和时区的情况下，统一使用标准的ISO日期/星期，我觉得是合理的。
