### ISSUE TITLE
Incorrect variable id passed when editing view

### ISSUE THREAD

**Issue by scottsut** [running-elephant/datart#180]
**To Reproduce**
Reproducing

**Expected behavior**
The `id` passed is generated by server.

**Screenshots**
![image](https://user-images.githubusercontent.com/4098913/140860759-24ece33a-db69-4405-8563-9bc281c6eaa3.png)

**Comment by Cuiyansong** [comment]
感谢贡献，此问题已验证并修复，如新版本仍然有问题请留言或者重开此问题。
