### ISSUE TITLE
建议增加release 版本号在界面

### ISSUE THREAD

**Issue by rickqi** [running-elephant/datart#183]
**你的功能要求与某个问题相关吗？**
清晰简洁地描述这个问题

**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
登录界面右下角有显示版本号
