### ISSUE TITLE
请问前端如何运行调试？

### ISSUE THREAD

**Issue by zhang-sansi** [running-elephant/datart#1830]
我想要对前端页面进行改动，想要让前端代码能实现修改后自动编译，但不熟悉这块技术不知从何下手，能给我一些指引吗？

**Comment by stillsilly** [comment]
让前端项目跑起来容易，但是这个项目挺大挺复杂的，你不会前端的话，不好改   

步骤：
cd 进 frontend目录
`npm run bootstrap`
`npm prestart`
`npm start`
就跑起来了，会自动开一个浏览器标签页 localhost:3000  
修改代码后会自动编译

要有后端接口页面才能正常工作，部署在本地或者自己的服务器都可以，懒得部署的话，可以用datart官方的接口，他们做了跨域限制，自己做一层代理转发一下就行了  
我提供一个简单方便的解决跨域的办法：
全局安装 http-server
`npm install http-server -g`

然后执行：
`http-server --port 8080 --proxy http://datart-demo.retech.cc/ --cors`
会把本地8080的请求全部转发到http://datart-demo.retech.cc/

**Comment by zhang-sansi** [comment]
> 让前端项目跑起来容易，但是这个项目挺大挺复杂的，你不会前端的话，不好改
> 
> 步骤： cd 进 frontend 目录 `npm run bootstrap` `npm start` 就跑起来了，会自动开一个浏览器标签页 localhost:3000 修改代码后会自动编译
> 
> 要有后端接口页面才能正常工作，部署在本地或者自己的服务器都可以，懒得部署的话，可以用datart官方的接口 把 craco.config.js 文件里的 http://localhost:8080/ 改成 http://datart-demo.retech.cc/ craco.config.js 文件修改后要重新 `npm start` 才能生效

感谢！
