### ISSUE TITLE
Suggestion: A better word for the pivot table row header column name

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1842]
This relates to https://github.com/running-elephant/datart/issues/1114

After the improvement, the column name supports i18n now. However, the default column name "Number" is not a good description for the field. Would propose to use the same name "Metric" to cover any numeric field added to the Metric field.

![image](https://user-images.githubusercontent.com/100477931/183392591-cd133fef-25bb-4b67-a685-3b93d9aa3681.png)

![image](https://user-images.githubusercontent.com/100477931/183392660-c59b5956-d0e2-4a91-9fb5-149bce919cdf.png)

Would submit a PR if ok to go.

**Comment by Cuiyansong** [comment]
I like the word "Metric" better than "Number"

**Comment by clementchong** [comment]
PR submitted. Thank you!
