### ISSUE TITLE
普通表格，可否增加行小计功能

### ISSUE THREAD

**Issue by suntianxian** [running-elephant/datart#1854]
普通表格，行合并后，可否增加行小计功能

**Comment by handsomepjf** [comment]
现在得普通表格更多是一个明细表格，可能后面确实是需要一个这种类型得
分组表格
![origin_img_v2_9ecb8a5f-5e72-450a-bb3f-0117ba0c8deg](https://user-images.githubusercontent.com/63778314/185577767-1fe70f4d-ea17-4fcb-9018-a68ccc085e3b.jpg)

**Comment by scottsut** [comment]
可以考虑用计算字段自行实现
