### ISSUE TITLE
1.0.0-rc.1版本仪表板内表格无法翻页

### ISSUE THREAD

**Issue by leeegeng** [running-elephant/datart#1862]
**Datart Version**
1.0.0-rc.1

**Describe the bug**
数据图标中的表格可以正常翻页，仪表板中图表无法翻页。

![image](https://user-images.githubusercontent.com/52368324/184049323-277c8876-1410-49fd-9699-2a83286b05af.png)

点击分页，没有反应

**Comment by clementchong** [comment]
我也有一样的问题。。

**Comment by Cuiyansong** [comment]
Sorry for the trouble/mistake, tomorrow we will publish a hotfix release, with several bugs fix.

**Comment by clementchong** [comment]
> Sorry for the trouble/mistake, tomorrow we will publish a hotfix release, with several bugs fix.

Thank you for the good news. There is no need to feel bad, you guys are doing a great job!
