### ISSUE TITLE
翻牌器联动功能问题

### ISSUE THREAD

**Issue by leeegeng** [running-elephant/datart#1863]
**Datart Version**
1.0.0-rc.1 

**Describe the bug**
翻牌器->【交互】功能有以下问题：

1 【跳转设置】能够跳转到目标页面，但参数没有传递，目标页面没有对联动关系设置进行检索过滤；

2 【联动】功能有同样问题，同一个仪表板内的联动关系设置不生效，如联动表格，点击翻牌器后，表格没有反应。

**Comment by Cuiyansong** [comment]
目前，跳转/联动的参数是基于“维度”值的，而翻牌器等图表没有维度就不会生成过滤条件参数。
