### ISSUE TITLE
Sql parse bug

### ISSUE THREAD

**Issue by lyp000119** [running-elephant/datart#1866]
version: 1.0.0-beta.4
SQL:SELECT * FROM  ( SELECT * FROM GDP WHERE 地区 IN $gdp_area1$ )  AS `DATART_VTABLE` LIMIT 1000 OFFSET 0 
DB: MYSQL 
EXCEPTION:org.apache.calcite.sql.parser.SqlParseException: Encountered "IN $gdp_area1$" at line 1, column 45.
Was expecting one of:
    "EXCEPT" ...
    "FETCH" ...
    "GROUP" ...
    "HAVING" ...
    "INTERSECT" ...
    "LIMIT" ...
    "OFFSET" ...
    "ORDER" ...
    "MINUS" ...
    "UNION" ...
    "WINDOW" ...
    ")" ...
    "." ...
    "NOT" ...
    "IN" "(" ...
    "BETWEEN" ...
    "LIKE" ...
    "SIMILAR" ...
    "=" ...
    ">" ...
    "<" ...
    "<=" ...
    ">=" ...
    "<>" ...
    "!=" ...
    "+" ...
    "-" ...
    "*" ...
    "/" ...
    "%" ...
    "||" ...
    "AND" ...
    "OR" ...
    "IS" ...
    "MEMBER" ...
    "SUBMULTISET" ...
    "CONTAINS" ...
    "OVERLAPS" ...
    "EQUALS" ...
    "PRECEDES" ...
    "SUCCEEDS" ...
    "IMMEDIATELY" ...
    "MULTISET" ...
    "&" ...
    "[" ...
    "FORMAT" ...
    "(" ...

**Comment by tianlu-root** [comment]
IN  后面需要跟 ( )
