### ISSUE TITLE
在demo系统中按部门汇总工资信息，无结果

### ISSUE THREAD

**Issue by hds1999** [running-elephant/datart#187]
在demo系统中按部门汇总工资信息，无结果
![image](https://user-images.githubusercontent.com/20547693/140904325-8379d34f-92f8-490a-9146-f0a95e145374.png)

**Comment by scottsut** [comment]
请提供更详细的信息帮忙定位问题：
1、数据库类型
2、图表编辑界面右上角的原始数据视图截图
3、查询请求参数以及返回结果截图

**Comment by hds1999** [comment]
就是官方的demo系统中的数据：
数据源：sxdtest
数据库类型：file
数据视图：sxd_test

http://datart-demo.retech.cc/organizations/82a6c970029b410e9726a45f572595d2/vizs/f4c5f903ca344605b36b9cbf6122c315
![image](https://user-images.githubusercontent.com/20547693/141035743-99a4d271-7f2d-42b3-85f0-c187d8835b78.png)

**Comment by scottsut** [comment]
因为你上传文件时指定的字段类型不对，datart 服务按照上传文件时指定的字段类型建表，对字符型字段进行聚合因此报错了。

![image](https://user-images.githubusercontent.com/4098913/141039568-c40a01fd-fb6a-45f2-ab24-d57930d44578.png)

改成数值类型后，可以正常查询数据

![image](https://user-images.githubusercontent.com/4098913/141039632-de722d14-8eda-4866-bf16-1a80fbb5fed7.png)
