### ISSUE TITLE
redis的连接时而断联导致页面报错

### ISSUE THREAD

**Issue by Plume3362** [running-elephant/datart#1875]
**Datart Version**
1.0.0-beta.3

**Describe the bug**
加载图表时有时redis服务端断联socket超时

**To Reproduce**
1. 加载图表时偶发报错

**Expected behavior**
解决该问题

**Screenshots**
![企业微信截图_16602899906828](https://user-images.githubusercontent.com/49897998/184310137-3b35e3b4-9891-4f9b-9e99-ba439f087e77.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

@scottsut

**Comment by Cuiyansong** [comment]
请关注下Redis错误日志，可能是网络问题，与Datart无关。
