### ISSUE TITLE
自定义插件如何手动触发查询

### ISSUE THREAD

**Issue by suntianxian** [running-elephant/datart#1876]
自定义插件如何手动触发查询

集成了别的表格插件，表格插件的分页按钮事件已经触发，但是如何调用datart的查询接口返回数据，并重新渲染页面呢？

![image](https://user-images.githubusercontent.com/33952402/184312785-8037a8f7-267a-46f4-b8ff-d02acde0b8aa.png)

**Comment by Cuiyansong** [comment]
可以参考下图表代码中的，分页事件

**Comment by suntianxian** [comment]
> 可以参考下图表代码中的，分页事件

1.图标代码是react写的，我这插件是vue写的，学习难度有点大，就算看懂了，也不知道能不能调用，在VUE里面怎么调用
2.官方能不能提供一个方法去调用，无非就是改改参数🤦‍

**Comment by Cuiyansong** [comment]
参考下项目代码中的`BasicTableChart.tsx`中的分页事件。当自己定义图表发生分页时，需要调用mouse events的click事件并且传递正确的interaction type（`interactionType: ChartInteractionEvent.PagingOrSort`）
```typescript
 onChange: (pagination, filters, sorter, extra) => {
        if (extra?.action === 'sort' || extra?.action === 'paginate') {
          this.invokePagingRelatedEvents(
            sorter?.column?.colName,
            sorter?.order,
            pagination?.current,
            sorter?.column?.aggregate,
          );
        }
      }
```
