### ISSUE TITLE
资源导入导出bug

### ISSUE THREAD

**Issue by cssd2022** [running-elephant/datart#1877]
**Datart版本号**
rc-0

**错误描述**
资源导入导出时，目录的org_id错误已经有人提了。#1864
另外仪表板里使用全局变量情况下，导入时报source_id can not null

**截图**
![微信图片_20220812170323](https://user-images.githubusercontent.com/104971416/184322252-2ab1c576-a0d9-465d-b330-af501a4df2da.png)

**Comment by Cuiyansong** [comment]
Maybe fix this issue pr #1910
