### ISSUE TITLE
FILE和HTTP类型数据源，编辑表，并且修改配置后，会添加一条脏数据

### ISSUE THREAD

**Issue by qiangxue1206** [running-elephant/datart#1878]
**Datart版本号**
dev

**错误描述**
FILE和HTTP类型数据源，编辑表，并且修改配置后，会添加一条脏数据

**如何重现**
重现错误的步骤，例如：
1. 打开数据源页面
2. 新增FILE或HTTP类型数据源
3. 新增一条表配置
4. 编辑新增后的表配置，并且修改表名
5. 保存后配置中会多一条脏数据

**期望结果**
FILE和HTTP类型数据源，编辑表，并且修改配置后，可以正常保存

**截图**
问题复现截图：
https://user-images.githubusercontent.com/44155933/184329021-07703207-413c-469b-bac7-9d307ff3b272.mp4
修复后截图：
https://user-images.githubusercontent.com/44155933/184328881-0f04119a-b89c-436a-bc92-bb1085691453.mp4

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: Windows 11
- 数据源: /
- 浏览器: chrome 103.0.5060.134

**其他内容**
稍后提交下问题修复的PR

**Comment by qiangxue1206** [comment]
问题修复的PR具体见：https://github.com/running-elephant/datart/pull/1880

**Comment by Cuiyansong** [comment]
感谢提出问题并提供PR修复，PR将会合并在RC2 Release。
