### ISSUE TITLE
建议数据视图定义的时候可以增加分类

### ISSUE THREAD

**Issue by hds1999** [running-elephant/datart#188]
**形容一下你想要的解决方案**
    建议数据视图定义的时候可以增加分类，在图表设计界面可以按照分类树结构展示数据视图，这样可以灵活的定义区分维度、指标，业务使用人员可以在图表设计的时候快速的通过分类找到自己需要的信息。 
谢谢！

**Comment by Cuiyansong** [comment]
能具体/分类的描述下需求吗？

**Comment by Cuiyansong** [comment]
if you have more suggestions, please leave a message here.
