### ISSUE TITLE
仪表板数据交互bug

### ISSUE THREAD

**Issue by yfsmmr777** [running-elephant/datart#1882]
**Datart Version**
The version of `datart` you using.

**Describe the bug**
1，仪表板的筛选控件不能对交互功能的“查看数据”起作用
2，自定义字段不能显示到仪表板的交互功能中

**To Reproduce**
1. 配置仪表板图表“翻牌器”
2. 配置“交互”--“查看数据”
3. 选择字段，改为“自定义”
4. 选择维度字段和指标字段
5

**Expected behavior**

**Screenshots**
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/110766974/184517713-ab504da3-847c-4bbe-a7a1-a0c4bf9f4458.png">

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/110766974/184517770-4287321d-fd9c-4de0-ba4a-44ee237d9caf.png">

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/110766974/184517792-89c217ae-aa2d-4280-8e17-7863a27e7c70.png">

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
目前“交互”不支持指标，只支持维度作为过滤条件。而当前翻牌器仅仅有指标，所以，目前设计上是支持交互事件，但是不会带任何过滤条件。
