### ISSUE TITLE
Kubernetes部署

### ISSUE THREAD

**Issue by 88fantasy** [running-elephant/datart#1884]
**你的功能要求与某个问题相关吗？**
否

**形容一下你想要的解决方案**
部署在 kubernetes 上 (通过 helm或其他) 

**描述一下你考虑过的备选方案**

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by Cuiyansong** [comment]
目前没有使用以及预制k8s的需求，感谢贡献方案，但是目前暂时不会考虑合并进来。
