### ISSUE TITLE
[BUG] 表格不能排序

### ISSUE THREAD

**Issue by zhu-mingye** [running-elephant/datart#1898]
**Datart Version**
rc1 / demo环境同样

**Describe the bug**
表格不能排序  聚合和不聚合的一样的问题 

**To Reproduce**

**Expected behavior**

**Screenshots**
demo环境 复现截图

![图片](https://user-images.githubusercontent.com/58576849/185075776-fa91600d-18c4-47e7-8a82-3b70c94a5eb2.png)

初始状态:
![图片](https://user-images.githubusercontent.com/58576849/185075866-11636fc3-5f69-439d-b745-9681252fd392.png)

升序:
![图片](https://user-images.githubusercontent.com/58576849/185075948-37611a0f-5de9-4710-92d1-3bad3c96b27b.png)

降序:
![图片](https://user-images.githubusercontent.com/58576849/185076031-407c99dc-5e41-480f-9dc1-c7e8cd5bbd18.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
This issue have been fixed in PR #1883 with related issue "table cannot paging in dashboard", this fix will release a new hotfix version before RC.2 official release.

**Comment by zhu-mingye** [comment]
> This issue have been fixed in PR #1883 with related issue "table cannot paging in dashboard", this fix will release a new hotfix version before RC.2 official release.

OK  thanks
