### ISSUE TITLE
图片组件无法上传图片

### ISSUE THREAD

**Issue by caiiansheng** [running-elephant/datart#190]
**Describe the bug**
添加图片组件，点击编辑 没有任何反应

**To Reproduce**
![image](https://user-images.githubusercontent.com/26760483/141034757-eb75ed4b-406e-4fc5-8592-3aef1d2ae307.png)

**Comment by scottsut** [comment]
选中组件后在右侧配置栏里上传图片

![image](https://user-images.githubusercontent.com/4098913/141040121-46f90d78-0242-42c5-a333-fe6dfcf07a10.png)

或参考文档中的动图示例

https://running-elephant.github.io/datart-docs/docs/dashboard.html#2-1-2-%E5%AA%92%E4%BD%93%E7%BB%84%E4%BB%B6
