### ISSUE TITLE
Switch view dialog message enhancement for English

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#1903]
**Datart Version**
Demo site 1.0.0rc.1

**Describe the bug**
The existing english description and button text are not too clear.

**To Reproduce**

**Expected behavior**
Simplified the message and also reword few buttons.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/100477931/185278624-35c397a1-38f4-4713-8c80-876304417e3c.png)

After:
![image](https://user-images.githubusercontent.com/100477931/185279262-7b6e7c85-2561-445f-a601-6fc93d530a91.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
Thanks for contribution.
