### ISSUE TITLE
制作http类型的视图，部分视图出现bug

### ISSUE THREAD

**Issue by yizhongliuJava** [running-elephant/datart#191]
![image](https://user-images.githubusercontent.com/34359686/141056030-6f184a93-8d3d-41fd-bf7c-f864c41bec2a.png)

红框类型视图基本不可用(http类型)
翻牌器  柱状图  条形图 分组表等都不能用，仅仅明细表可用，可能是数据类型判断错误导致

**Comment by scottsut** [comment]
请提供更详细的信息帮忙定位问题：
1、错误信息截图
2、图表编辑界面右上角的原始数据视图截图
3、查询请求参数以及返回结果截图

**Comment by yizhongliuJava** [comment]
1.数据集 
![企业微信截图_16365263619060](https://user-images.githubusercontent.com/34359686/141063887-c8458e0f-f7f3-4368-89cd-48ffcd51c051.png)
2.不同视图错误截图 
![企业微信截图_16365264818714](https://user-images.githubusercontent.com/34359686/141063924-cb35e379-a411-4822-9015-6af9c97a8f17.png)
![企业微信截图_16365264353822](https://user-images.githubusercontent.com/34359686/141063938-15d8e2a4-dbe3-48f5-8471-55275a4c782f.png)
![企业微信截图_16365265406278](https://user-images.githubusercontent.com/34359686/141064391-e3d08524-89a9-4a85-b180-75f30a27a3fe.png)
![企业微信截图_16365265254549](https://user-images.githubusercontent.com/34359686/141064402-674b72e6-e6ae-4ef6-b1e0-da530aa196e7.png)
分组表和翻牌器主要是以上错误，其他chart也是这种错误

**Comment by scottsut** [comment]
`SUM or AVG on wrong data type`  可能是 http schema 类型设置不对，参考 [这个 issue](#187 )
