### ISSUE TITLE
图表导出 pdf 和图片在明细表时只会导出第一页

### ISSUE THREAD

**Issue by 88fantasy** [running-elephant/datart#1915]
**Datart版本号**
1.0.0 rc1

**错误描述**
datart 的 pdf 和图片是依靠截图来实现的
对于分页的明细表,  只会导出第一页, 后面的分页都没有了

[科研项目列表_2022-08-19_15-26-11-039_805.pdf](https://github.com/running-elephant/datart/files/9380139/_2022-08-19_15-26-11-039_805.pdf)

**Comment by 88fantasy** [comment]
excel 是完整的

是否可以考虑通过 excel 转 pdf?

**Comment by scottsut** [comment]
暂无计划，谢谢建议！
