### ISSUE TITLE
请教如何在datart应用部署中增加上下文根

### ISSUE THREAD

**Issue by gaolmao** [running-elephant/datart#1922]
**你的功能要求与某个问题相关吗？**
您好，由于希望在同一个应用服务器部署除datart外不同的应用，我想在datart部署后，用户访问应用时增加上下文的根目录。如http://localhost:8080/datart

**形容一下你想要的解决方案**
请问如何配置才能能实现这个功能，用户在浏览器访问输入url为：http://localhost:8080/datart
。

**描述一下你考虑过的备选方案**
我已经尝试在如下文件进行修改：
后端application.xml中增加配置：server.servlet.context-path="/datart"
前端package.json 中增加 homepage="http://localhost:8080/datart"
编译后在前端浏览器输入http://localhost:8080/datart/index.html ，报一些css、js404错误。

**其他内容**
访问报错截图如下：
![微信图片_20220822182354](https://user-images.githubusercontent.com/107606876/185899608-c277996d-9e86-47f1-9f5e-de173ec3bd2e.jpg)

**Comment by Cuiyansong** [comment]
用Nginx代理会不会更便捷方便一些

**Comment by landuo** [comment]
> **你的功能要求与某个问题相关吗？** 您好，由于希望在同一个应用服务器部署除datart外不同的应用，我想在datart部署后，用户访问应用时增加上下文的根目录。如http://localhost:8080/datart
> 
> **形容一下你想要的解决方案** 请问如何配置才能能实现这个功能，用户在浏览器访问输入url为：http://localhost:8080/datart 。
> 
> **描述一下你考虑过的备选方案** 我已经尝试在如下文件进行修改： 后端application.xml中增加配置：server.servlet.context-path="/datart" 前端package.json 中增加 homepage="http://localhost:8080/datart" 编译后在前端浏览器输入http://localhost:8080/datart/index.html ，报一些css、js404错误。
> 
> **其他内容** 访问报错截图如下： ![微信图片_20220822182354](https://user-images.githubusercontent.com/107606876/185899608-c277996d-9e86-47f1-9f5e-de173ec3bd2e.jpg)

我也按照 [#1011](https://github.com/running-elephant/datart/issues/1011) 中的方法去设置了，也出现类似某些css js找不到的问题，而且分享的时候链接是不带/datart的

**Comment by gaolmao** [comment]
尝试使用nginx路由配置，只能转换后端context-path，前端生成的js路径会有问题。按照 [https://github.com/running-elephant/datart/issues/1011](url)  中的方式配置后，发现分享页面路径不对，还需要再加一个地方：
fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，分享链接就对了，但是可能还是有其他地方路径问题，报错：Uncaught SyntaxError: Unexpected token '<' 
这个问题好像之前提出的人还不少，有进一步进展我再继续更新。

**Comment by gaolmao** [comment]
更新下，在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，清理缓存，分享页也正常了。

**Comment by ThornPan** [comment]
> 更新下，在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，清理缓存，分享页也正常了。

我按照1011里面的方法配置了，然后在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，但是打开分享页面是空白的，这个情况您遇到过吗

**Comment by gaolmao** [comment]
你好，确实是还有问题，我目前显示也是空白页。我对前端不熟，只能是比对修改之前正常分享的页面，发现还是有路径不正确的地方。


就是在static/css/shareChart...css中的文件，好像是URL不对，但我没找到如何修改。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 下午2:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [running-elephant/datart] 请教如何在datart应用部署中增加上下文根 (Issue #1922)




  
更新下，在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，清理缓存，分享页也正常了。
  
我按照1011里面的方法配置了，然后在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，但是打开分享页面是空白的，这个情况您遇到过吗

**Comment by ThornPan** [comment]
> 你好，确实是还有问题，我目前显示也是空白页。我对前端不熟，只能是比对修改之前正常分享的页面，发现还是有路径不正确的地方。 就是在static/css/shareChart...css中的文件，好像是URL不对，但我没找到如何修改。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年8月30日(周二) 下午2:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [running-elephant/datart] 请教如何在datart应用部署中增加上下文根 (Issue #1922) 更新下，在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，清理缓存，分享页也正常了。 我按照1011里面的方法配置了，然后在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，但是打开分享页面是空白的，这个情况您遇到过吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

我发现在frontend/src/app/pages/SharePage/Chart/Router.tsx中，<Route path="/shareChart/:token" component={LazyShareChart} /> 这一行，加入根目录就可以解决分享页空白的问题了，改成<Route path="/datart/shareChart/:token" component={LazyShareChart} />，shareDashboard应该也是类似

**Comment by ThornPan** [comment]
> 你好，确实是还有问题，我目前显示也是空白页。我对前端不熟，只能是比对修改之前正常分享的页面，发现还是有路径不正确的地方。 就是在static/css/shareChart...css中的文件，好像是URL不对，但我没找到如何修改。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年8月30日(周二) 下午2:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;;"State ***@***.***&gt;; 主题: Re: [running-elephant/datart] 请教如何在datart应用部署中增加上下文根 (Issue #1922) 更新下，在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，清理缓存，分享页也正常了。 我按照1011里面的方法配置了，然后在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，但是打开分享页面是空白的，这个情况您遇到过吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***&gt;

我发现在frontend/src/app/pages/SharePage/Chart/Router.tsx中， 这一行，加入根目录就可以解决分享页空白的问题了，改成<Route path="/datart/shareChart/:token" component={LazyShareChart} />，shareDashboard应该也是类似

**Comment by ThornPan** [comment]
> > 你好，确实是还有问题，我目前显示也是空白页。我对前端不熟，只能是比对修改之前正常分享的页面，发现还是有路径不正确的地方。 就是在static/css/shareChart...css中的文件，好像是URL不对，但我没找到如何修改。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2022年8月30日(周二) 下午2:55 收件人: _**@**_.**_>; 抄送: _**@**_._**>;"State _**@**_.**_>; 主题: Re: [running-elephant/datart] 请教如何在datart应用部署中增加上下文根 (Issue #1922) 更新下，在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，清理缓存，分享页也正常了。 我按照1011里面的方法配置了，然后在fontend\src\utils\request.ts 中getServerDomain 方法中增加上/datart 路径，但是打开分享页面是空白的，这个情况您遇到过吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: _**@**_.***>
> 
> 我发现在frontend/src/app/pages/SharePage/Chart/Router.tsx中， 这一行，加入根目录就可以解决分享页空白的问题了，改成，shareDashboard应该也是类似

![6B983A8E-6E33-473a-A299-56983166934D](https://user-images.githubusercontent.com/20057405/187400294-74b90063-36da-4c77-a98e-97e728ef0e45.png)

**Comment by gaolmao** [comment]
确实是这样~~

**Comment by 6LWa6ZKx** [comment]
新建一个.env文件，里面写上“PUBLIC_URL=/datart”。这样就全局可用了。因为很多地方都有“PUBLIC_URL”这个路径使用。
