### ISSUE TITLE
用户的名字（name）字段为null，会导致所有查询失败。

### ISSUE THREAD

**Issue by yqwoe** [running-elephant/datart#1924]
**Datart Version**
The version of `datart` you using.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/7060489/186047870-78be423d-604c-4d58-b714-6cbab5dcdabe.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by Cuiyansong** [comment]
请按要求完善Issue信息，如版本，复现步骤等。
