### ISSUE TITLE
功能需求提出

### ISSUE THREAD

**Issue by wangyayuan18** [running-elephant/datart#1925]
**你的功能要求与某个问题相关吗？**
清晰简洁地描述这个问题
1.标题支持增加logo、边框、下划线样式、增加可商用字体（艺术字）、图库

2.看板/图形编辑实时更新或1分钟保存一次(因为在编辑的时候，开发人员不小心点到了鼠标侧边按钮直接导致看板取消编辑，之前编辑的东西就功亏一篑了)

3.图表单独标线框(模板现有标线框是单颜色，想要的效果是上下左右框线要单独设置颜色)

4.增加图表样式(现有图表样式是24个，可以增加其他图表(例如：旋风图，雷达图，气泡图，3d地图(地图流向)，热力图，针线图等等))
5.默认字体白色(修改图表现在字体颜色默认是黑色，但大部分背景图是深色图，能不能默认编辑图表字体颜色为白色，因为现在一个图表一个图标的字体颜色要从黑色调成白色所以很麻烦)

6.图表不支持跨看板复制(我想要这个看板的饼图cp到另一个看板，现有功能是没有的)

7.增加取色器、格式刷功能

8.选择图像右上角三个点 -点击进入编辑  希望改为右键进入编辑

**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by hunterMichael** [comment]
👍
