### ISSUE TITLE
table动态扩充列

### ISSUE THREAD

**Issue by hunterMichael** [running-elephant/datart#1926]
**你的功能要求与某个问题相关吗？**
表格数据是否支持动态扩充，比如某销售数据，今天只有1号、2号数据，则前端显示2列数据。
明天有1，2，3号数据，则前端可以显示3列数据。如下图所示
a.8月2日销售数据
![image](https://user-images.githubusercontent.com/51942801/186107390-c4e8c01e-4c0b-4118-a6d1-ce8ffa399d15.png)
b.8月3日销售数据
![image](https://user-images.githubusercontent.com/51942801/186107528-f7a0be1a-3fda-4286-ad76-a7886ea82485.png)

**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by lidong081824** [comment]
希望增加+1

**Comment by llf007** [comment]
![image](https://user-images.githubusercontent.com/60683568/186656134-53a1e8f7-3ebb-42df-9bff-c8b87d02d480.png)
你可以试试【透视表】，将日期放到【列】

**Comment by hunterMichael** [comment]
目前是按透视表方式做的，但是透视表不能满足一些其它需求
