### ISSUE TITLE
页面分享后没有下载功能

### ISSUE THREAD

**Issue by hunterMichael** [running-elephant/datart#1937]
**你的功能要求与某个问题相关吗？**
报表页面分享后，没有下载按钮

**形容一下你想要的解决方案**
增加下载按钮功能

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
之前davinci是支持此功能的

**Comment by Cuiyansong** [comment]
This issue will be closed,  and tracking on #1942
