### ISSUE TITLE
采用Docker部署后不能执行图片及PDF下载

### ISSUE THREAD

**Issue by kanyways** [running-elephant/datart#1943]
**Datart Version**
- Datart Version：datart/datart:latest (964eef4a6610) **1.0.0.rc.1**
- standalone-chrome：selenium/standalone-chrome:latest (812317d6b5b4) **104.0.5112.79**

**Describe the bug**
采用Docker部署后不能执行图片及PDF下载。

```bash
docker rm -f datart-server && docker run --name datart-server --restart=always -d -i -p 8089:8089 -v /data/apps/datart/config/datart.conf:/datart/config/datart.conf  -v /data/apps/datart/files:/datart/files da
tart/datart:latest

docker rm -f selenium-chrome  && docker run -p 4444:4444 -p 7900:7900 -d --name selenium-chrome --shm-size="2g" selenium/standalone-chrome
````

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9895669/186836596-5f10c9da-f440-4e4c-b96e-77c9f38a987d.png)

Datart
![image](https://user-images.githubusercontent.com/9895669/186836814-2f9bfadb-f766-4382-aab4-b7bef6fb93a2.png)

selenium-chrome
![image](https://user-images.githubusercontent.com/9895669/186836859-15ccdc67-a077-49a2-86f9-48a731638c8c.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: Windows 10
 - Source Database: MySQL 8.0.27
 - Browser: Chrome 104.0.5112.102
 - Server：CentOS 8.0
 - Docker Version：20.10.9

**Additional context**

**Comment by lishidetainan** [comment]
I have similar proberlom, have you solved the issure

**Comment by scottsut** [comment]
确保 datart 能够正常访问 selenium。
