### ISSUE TITLE
datart 登陆对接能力，权限对接能力现在有了吗，有的话能详细说一下嘛

### ISSUE THREAD

**Issue by glongning** [running-elephant/datart#1953]
**你的功能要求与某个问题相关吗？**
文档上对datart 登陆对接能力只有简短的描述，是暂时没有还是已经有了，如果已经有了能否详细说一下具体怎么对接
以下是改技术文档上的内容：
datart 可作为独立平台使用，但不仅限于此，为了更好支持快速构建定制化数据应用系统，datart 可以很容易被整合、被内嵌至其他三方系统，承担数据可视化部分功能。通过 datart 的登录对接能力、权限对接能力、Source 层对接能力和 Visualization 层分享、SDK等能力，用户可以基于 datart 平台对接或二开以快速满足业务系统定制化需求。

**Comment by glongning** [comment]
文档上没有具体的datart 登陆对接能力，权限对接能力

**Comment by xuguanghui1988** [comment]
同问

**Comment by atliwen** [comment]
翻了一遍源码。 是通过jwk做的登录。  后端都明白了，只要安装规则创造一个 TK 就好了。  然而，前端完全看不懂啊。 分享页面 登录授权查看下， 可以直接获取TK 登录显示。  前端实在是看不懂！VUE 会  react 实在是不会。 就差一点点了。

**Comment by scottsut** [comment]
参考文档中的[单点登录](https://running-elephant.github.io/datart-docs/docs/#3-2-7-%E5%8D%95%E7%82%B9%E7%99%BB%E5%BD%95%E9%85%8D%E7%BD%AE)配置部分
