### ISSUE TITLE
表格组件，样式可以修改背景色，为什么不能修改表格的列标题的样式

### ISSUE THREAD

**Issue by glongning** [running-elephant/datart#1955]
表格组件，样式可以修改背景色，不能修改表格的列标题的样，样式自由度不够高，会导致可视化界面不够好看。
如图：
<img width="205" alt="2" src="https://user-images.githubusercontent.com/112456605/187380227-b4ab6adc-a971-45d1-a9a7-87cfb187296a.PNG">

**Comment by glongning** [comment]
样式自由度还缺点，只能微调，不能达到做到自定制界面的作用

**Comment by scottsut** [comment]
定制需求可以自行二次开发来满足。
