### ISSUE TITLE
仪表板交互跳转如何将日期范围控制器（包括其他控制器）传递给下一个仪表板

### ISSUE THREAD

**Issue by handsomepjf** [running-elephant/datart#1957]
**你的功能要求与某个问题相关吗？**
清晰简洁地描述这个问题
目前是在一个汇总列表交互跳明细列表得场景，存在日期范围筛选得控制器以及其他控制器，汇总表里点击相关字段跳转下一个仪表板或者URL能实现在已经形成得控制器筛选条件带入下一个场景
**形容一下你想要的解决方案**
清晰简洁地描述你希望发生什么
不清楚是否已经有功能实现了这个操作
**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
谢谢建议！暂时没有这方面计划。
