### ISSUE TITLE
fronted项目编译报错

### ISSUE THREAD

**Issue by yangfd1** [running-elephant/datart#1960]
**Datart Version**
2.0.

**Describe the bug**
TypeScript error in D:/WorkSpace/datart/frontend/src/app/components/ChartEditor.tsx(672,11):
Type '{ width: number; formProps: { labelAlign: string; labelCol: { offset: number; span: number; }; wrapperCol: { span: number; }; }; okText: any; }' is not assignable to type 'IntrinsicAttributes & SaveFormProps'.
  Property 'width' does not exist on type 'IntrinsicAttributes & SaveFormProps'.  TS2322

    670 |         />
    671 |         <SaveForm
  > 672 |           width={400}
        |           ^
    673 |           formProps={{
    674 |             labelAlign: 'left',
    675 |             labelCol: { offset: 1, span: 6 },
[HPM] Error occurred while trying to proxy request /api/v1/sys/info from localhost:3000 to http://localhost:8080/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors).
多个文件都报错：Property '  ' does not exist on type 'IntrinsicAttributes & SaveFormProps'

**To Reproduce**

**Expected behavior**
编译成功，正常运行

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS:  Windows 10
 - Source Database: MySQL 8.0.30
 - Browser: chrome 102

**Additional context**

**Comment by Cuiyansong** [comment]
1. delete `node_modules`
2. run `npm install`

**Comment by Cuiyansong** [comment]
datart 什么时候有v2 version了，请合理/正规描述issue

**Comment by yangfd1** [comment]
> datart 什么时候有v2 version了，请合理/正规描述issue

下载的最新的gitee上的，我看License是2.0

**Comment by q1139168548** [comment]
那是Apache License 2.0，不是datart版本，datart版本在pom.xml里看或者登陆页右下角看
