### ISSUE TITLE
source_schemas的 设计缺陷问题

### ISSUE THREAD

**Issue by kim-up** [running-elephant/datart#1973]
source_schemas的schemas字段，目前保存的是 所有库、表、字段的一个大JSON。
但是按照实际稍微大一点的企业的大数据的数据表的规模会达到上万张，比如，impala查询引擎就有这个问题。

**Comment by tianlu-root** [comment]
你的impala查询出现了什么问题？上万张表所占用的空间远远达不到longtext的容量限制。

**Comment by HendSame** [comment]
> 你的impala查询出现了什么问题？上万张表所占用的空间远远达不到longtext的容量限制。

容量还好，就是所有表的元数据都放到一个JSON里面，会导致更新元数据时：必须等待要获取完全部库的元数据时，才能更新到`source_schemas `。这样如果，表很多，整个过程比较长，几十分钟或者更长。
