### ISSUE TITLE
仪表板中添加公共数据图表保存后无法正常显示数据图表组件内容

### ISSUE THREAD

**Issue by berg-xu** [running-elephant/datart#198]
**Describe the bug**
仪表板中添加公共数据图表保存后无法正常显示数据图表组件内容。

**To Reproduce**
1.  选择可视化页面, 新增公共数据图表A, 然后新增仪表板B,将公共数据图表A添加到仪表板B中,选择保存.刷新页面后,公共数据图表A无法正常显示在仪表板B中.
4.   错误截图如下：
公共数据图表A：
![image](https://user-images.githubusercontent.com/45385723/141231973-4bc6fd26-2531-42cd-b958-64f61a38fc2a.png)

仪表板B:
![image](https://user-images.githubusercontent.com/45385723/141232025-073f1e29-759d-44d2-8d30-5899f345aeec.png)

**Comment by xieliuduo** [comment]
实在  demo演示环境吗？如果不是自己部署的是哪个版本的datart ，拉最新的dev分支试一下呢

**Comment by berg-xu** [comment]
@xieliuduo 非demo环境，自己部署的alpha.0版本中遇到的问题。 多谢,我更新到alpha.2版本试一试。
