### ISSUE TITLE
编辑图表，不能修改图表名称，这不合适，得删除图表重新创建

### ISSUE THREAD

**Issue by glongning** [running-elephant/datart#1982]
编辑图表，不能修改图表名称，这不合适，得删除图表重新创建

**Comment by lyp000119** [comment]
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/32259371/189056087-ea305251-59c5-4762-b436-8a9c46f6d5d2.png">
这里可以修改名称的

**Comment by glongning** [comment]
嗯呢
