### ISSUE TITLE
交叉表汇总标题显示问题

### ISSUE THREAD

**Issue by wbjsly** [running-elephant/datart#1993]
Datart:    1.0 RC0
Brower：Safari 15.6.1

![image](https://user-images.githubusercontent.com/25900538/189800029-62446094-dfa2-43f5-a6f8-a3877b7fd1e9.png)
![image](https://user-images.githubusercontent.com/25900538/189800131-9a0d412e-f4a3-44c6-93aa-92712a6279b6.png)

**Comment by scottsut** [comment]
#1407
