### ISSUE TITLE
看板导出为图片或导出为pdf，看板中的自定义筛选条件无效

### ISSUE THREAD

**Issue by q945737523** [running-elephant/datart#1994]
**Datart Version**
bate3，rc1

**Describe the bug**
看板导出为图片或导出为pdf，无法按看板中的自定义筛选项条件导出

**To Reproduce**
1. 打开创建好的看板
2. 修改默认筛选时间，数据按选择时间加载完毕
3. 点击右上角导出为图片
4. 下载后的图片未按选择时间展示内容

**Expected behavior**
下载的图片数据按对应筛选条件加载数据

**Screenshots**
![image](https://user-images.githubusercontent.com/41318391/189823214-5b149e5f-1b6a-4abd-b962-d005cfb2e56f.png)

**Environmental details: (optional, depending on where the bug occurs)**

**Additional context**

**Comment by scottsut** [comment]
目前无法导出带自定义筛选项的图片和PDF
