### ISSUE TITLE
视图中的编写sql时能否写参数

### ISSUE THREAD

**Issue by jinfeng202111** [running-elephant/datart#1997]
视图中的编写sql时能否写参数，在报表页面上输入不同的参数值，就可以针对不同的数据集进行报表展示了，比如：

![378a130092697f3f2a073cc59e0b8879_](https://user-images.githubusercontent.com/94880167/190040638-5cecec79-c1a6-4886-9726-b30713aa2734.png)
做成报表的数据会根据用户设置的开始时间而不一样

**Comment by scottsut** [comment]
参考文档中的变量章节
