### ISSUE TITLE
视图和图表除法（/），不能用

### ISSUE THREAD

**Issue by chenruige** [running-elephant/datart#2007]
**Datart版本号**
V1

**错误描述**
视图和图表除法（/），不能用

**如何重现**
重现错误的步骤，例如：
![image](https://user-images.githubusercontent.com/55741215/190391934-068d20d6-f1c7-47f3-bba7-21b00c91d191.png)
![image](https://user-images.githubusercontent.com/55741215/190392058-0f4cecc2-2b71-4773-ac1c-53f805dd611c.png)
![image](https://user-images.githubusercontent.com/55741215/190392129-dc0e5f84-8114-4151-8ba1-1e1ea4ccbcf8.png)

**期望结果**
清晰简洁地描述你期望的结果是什么

**截图**
如果方便的话，添加一个截图帮助解释你的问题

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: [例如 MACOS]
- 数据源: [例如  PG12]
- 浏览器: [例如 Safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by chenruige** [comment]
数据异常

**Comment by zpqsunny** [comment]
可能被除数存在0 对应的source 可能不支持， 例如pgsql

**Comment by llf007** [comment]
A/B，当B有可能为0时，试试写成：A / NULLIF(B, 0)

**Comment by xiaoqufengdi** [comment]
试试对除数加个括号
