### ISSUE TITLE
更新(重编辑)仪表板中已引用的公共数据图表内容后仪表板中公共数据图表内容无法自动刷新更新为最新数据图表

### ISSUE THREAD

**Issue by berg-xu** [running-elephant/datart#201]
**Describe the bug**
更新(重编辑)仪表板中已引用的公共数据图表内容后仪表板中公共数据图表内容无法自动刷新更新为最新数据图表。

目前部署为 alpha.2版本。

**To Reproduce**
1. 选择可视化页面, 新增公共数据图表A, 然后新增仪表板B,将公共数据图表A添加到仪表板B中,选择保存. 刷新页面后,再次重编辑公共数据图表A后保存，仪表板B中引用的公共数据图表A数据内容仍为重编辑前的数据内容，即仪表板B未同步更新已更新的数据图表内容。
 点击<刷新>按钮也未同步更新。

2. 截图如下：
更新(重编辑)后的公共数据图表A内容如下：
![image](https://user-images.githubusercontent.com/45385723/141255511-dfcc1e8f-d30c-43aa-a603-4d380e699c0f.png)

仪表板B中引入公共数据图表A内容仍为更新A前的数据内容：
![image](https://user-images.githubusercontent.com/45385723/141255616-e41f227b-b33d-4a5c-ab1e-0c42d53d6910.png)

点击红框所标注的 《刷新》, 数据内容也未同步更新。

1、看是否更新公共数据图表内容后，仪表板中引用的公共数据图表能同步更新显示;
2、点击刷新更新数据。

目前测试仅通过 刷新页面或者重新添加同一个数据图表组件能更新数据。

**Expected behavior**

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by scottsut** [comment]
这个刷新按钮不是为更新组件配置设计的，是同步数据，我们考虑纠正文字避免歧义。

另外，你更新组件配置后，关联的仪表板请关闭-重新打开来刷新组件。
