### ISSUE TITLE
ORA-00904: "DATART_VTABLE"."V_R_N": 标识符无效

### ISSUE THREAD

**Issue by llf007** [running-elephant/datart#2014]
**Datart版本号**
版本: 1.0.0-rc.1

**错误描述**
使用Oracle数据源，开启服务端聚合，在可视化图时都会提示：
ORA-00904: "DATART_VTABLE"."V_R_N": 标识符无效

**如何重现**

![image](https://user-images.githubusercontent.com/60683568/190945552-555f0f7e-6a9c-4af2-8b74-6f29e0738b96.png)
源数据表SELECT查询正常，没有“V_R_N”这个字段

![image](https://user-images.githubusercontent.com/60683568/190946398-7136be71-1ddb-476c-9246-924ee2556da6.png)
使用Oracle数据源，并且开启服务端聚合

![image](https://user-images.githubusercontent.com/60683568/190945796-75de11a0-b668-4fd2-8e86-d232b44d17f4.png)
数据视图，查询会多出“V_R_N”这个字段

![image](https://user-images.githubusercontent.com/60683568/190946305-347c8f99-8f45-45ce-9e9e-e32b626a0eb2.png)
可视化都会提示：ORA-00904: "DATART_VTABLE"."V_R_N": 标识符无效

**期望结果**
希望大牛排查，修复数据视图多了"V_R_N"字段的Bug。

点赞👍

**Comment by scottsut** [comment]
rc.2 版本已修复
