### ISSUE TITLE
导出excel（导出到excel）功能，在导出多个图表的时候可能下载不了（图表较多，耗费时间较长的时候基本就可以复现了）

### ISSUE THREAD

**Issue by KANLON** [running-elephant/datart#2018]
**Datart Version**
版本: 1.0.0-rc.1

**Describe the bug**
导出excel（导出到excel）功能，在导出多个图表的时候可能下载不了（图表较多，耗费时间较长的时候基本就可以复现了）

我从代码来看， 是检查用户权限的时候报空指针异常了，我发现在任务下载的时候，如果有其他请求进入，例如 下载列表的定时请求多次的时候，会有概率将下载线程中的用户清空掉，暂时还不知道什么原因！希望可以官方可以帮忙看看

**To Reproduce**
1.  打开 demo 链接 http://datart-demo.retech.cc/organizations/aff00fca50ba405582d642715666caa7/vizs/67ac87afe4694df899d6b147f02baeec
2. 点击左上角的 “导出到excel”功能
3. 等待几秒，查看是否下载成功，如果下载成功，可以多试几次，基本每次都会下载不了；等待几秒后显示失败

**Expected behavior**
点击导出到excel后，能正常下载数据

**Screenshots**
![image](https://user-images.githubusercontent.com/22886101/190999405-d210ef69-e904-486c-84d4-b523a9e1ee2c.png)

![image](https://user-images.githubusercontent.com/22886101/190999360-90e27cc7-359e-40e8-a856-ffafb95e3aef.png)

**Environmental details: (optional, depending on where the bug occurs)**
 -  Windows 10
 - 版本 105.0.5195.126（正式版本） （64 位）

**Comment by lbship** [comment]
这个之前也遇到过了，一样的问题，表太大偶尔会报空指针

**Comment by Data-bytes305** [comment]
有啥解决方法吗？ 最近也遇到了。

**Comment by EastLord** [comment]
我也遇到过，自己用ThreadLocal改了一下

**Comment by Drafthj** [comment]
主线程和导出线程，共用了一个Subject对象，主线程logCurrent后就清空了Subject的Principal，可以在runAs方法里，先用ThreadContext.unbindSubject()先将Subject和线程解绑

**Comment by HP-jackZhang** [comment]
我怎么发现导出的excel 只有表头 没有数据？

**Comment by KANLON** [comment]
> 我怎么发现导出的excel 只有表头 没有数据？

这个是另外一个bug，如果可视化组件是复制的，可能会触发这个bug，如果是复制的可视化组件，你新建一个就没问题了，后面我也提个mr
