### ISSUE TITLE
可以回写数据库吗？

### ISSUE THREAD

**Issue by EthanGuo2022** [running-elephant/datart#2021]
**你的功能要求与某个问题相关吗？**
darart中可以实现回写数据库吗？如表单填报

**形容一下你想要的解决方案**
增加简单表单填报的功能

**描述一下你考虑过的备选方案**
无

**其他内容**
有关这个功能要求的任意其他内容或截图

**Comment by scottsut** [comment]
谢谢建议！暂时没有计划。
