### ISSUE TITLE
Datart图片资源无法显示

### ISSUE THREAD

**Issue by EthanGuo2022** [running-elephant/datart#2027]
**Datart版本号**
1c

**错误描述**
![image](https://user-images.githubusercontent.com/113949104/192131867-8b3a3bf2-714f-4680-b3d2-1842adacd1a0.png)
有的可以，有图片不可以。仪表盘背景和图片组件都有这个问题

**Comment by Cuiyansong** [comment]
可否在Demo环境上创建个仪表板并导入这个有问题的图片，我们排查一下问题。
