### ISSUE TITLE
rc1版本分享链接下载功能缺失

### ISSUE THREAD

**Issue by nickyanghui** [running-elephant/datart#2028]
在bata3版本中，链接分享外部支持excel下载；
升级至rc1版本后，此功能缺失。
希望尽快修复此bug

**Comment by zhaoqingwin** [comment]
ShareDashboardPage.tsx 文件中 搜 allowDownload  将 false 改为 true ，然后重新编译前端代码就可以了

**Comment by scottsut** [comment]
Related to #1942
