### ISSUE TITLE
带变量数据视图，查询无数据

### ISSUE THREAD

**Issue by chenruige** [running-elephant/datart#2035]
demo环境
数据视图带变量
![image](https://user-images.githubusercontent.com/55741215/193037364-4475134b-9f36-4042-88e1-11d705b50ca3.png)
多值下拉列表，查询无数据（单一值也可以正常查询；不带if else条件语句也可以正常查询）
![image](https://user-images.githubusercontent.com/55741215/193037507-e9d9e9be-7cdd-4734-822d-4f1de7d7785d.png)
查询语句报错
![image](https://user-images.githubusercontent.com/55741215/193037638-0e633848-af18-4ec0-baac-0ca33d239d69.png)

**Comment by scottsut** [comment]
条件语句中所使用的是 freemarker 语法，请确认语法是否正确。
