### ISSUE TITLE
控制器没有了么？

### ISSUE THREAD

**Issue by taotao365s** [running-elephant/datart#205]
记得在davinci里有的，datart里咋找不到了

**Comment by scottsut** [comment]
现在叫筛选

https://running-elephant.github.io/datart-docs/docs/dashboard.html#2-1-4-%E7%AD%9B%E9%80%89%E7%BB%84%E4%BB%B6

https://running-elephant.github.io/datart-docs/docs/datachart.html#1-2-2-%E7%AD%9B%E9%80%89
