### ISSUE TITLE
当数据源为excel时, 按时间维度为季度时存在每年4季度值不正确

### ISSUE THREAD

**Issue by zpqsunny** [running-elephant/datart#2060]
**Datart版本号**
声明一下你正在使用的 `datart` 版本号
rc.1
**错误描述**
清晰简洁地描述这个错误
当数据源为excel时, 按时间维度为季度时存在每年4季度值不正确,其他1-3季度数据正确

**如何重现**
重现错误的步骤，例如：
1.数据源为excel时
2.时间维度为季度时
3.聚合数值字段 sum, avg

**期望结果**
清晰简洁地描述你期望的结果是什么

**截图**
如果方便的话，
添加一个截图帮助解释你的问题
<img width="819" alt="截屏2022-11-01 20 54 14" src="https://user-images.githubusercontent.com/20296627/199244577-7eaf843c-55db-47dc-9a00-2d921d9dd2e2.png">
以下是excel计算每个季度的值
14年 1季度

<img width="296" alt="截屏2022-11-01 20 59 16" src="https://user-images.githubusercontent.com/20296627/199245395-e6beb6fd-c55e-4062-b2f5-065b1d22e37b.png">

14年 2季度
<img width="290" alt="截屏2022-11-01 21 00 38" src="https://user-images.githubusercontent.com/20296627/199244867-33d9cad4-d00c-41d1-bd1d-697a4d3a2655.png">

14年 3季度

<img width="265" alt="截屏2022-11-01 21 01 33" src="https://user-images.githubusercontent.com/20296627/199245839-41f7fe25-c00a-401c-aca0-8d82a1e6db1e.png">

14年 4季度
<img width="267" alt="截屏2022-11-01 21 02 28" src="https://user-images.githubusercontent.com/20296627/199245025-34d5ccfa-a5dc-49e8-ad10-d63d9ed39261.png">

15年 4季度

<img width="261" alt="截屏2022-11-01 21 03 19" src="https://user-images.githubusercontent.com/20296627/199245973-70893693-dc8f-4076-9f0c-6047c94a0caa.png">

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: [mac os]
- 数据源: [MySQL 8.0.26]
- 浏览器: [chrome 94, safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by scottsut** [comment]
这属于业务问题，请自行检查数据加工中哪个步骤导致了偏差。
