### ISSUE TITLE
导出和分享入口是否可以移出来，与发布、编辑、更多按钮同级

### ISSUE THREAD

**Issue by q1139168548** [running-elephant/datart#2065]
**你的功能要求与某个问题相关吗？**
1. 导出和分享是比较常用的功能，放在【更多】气泡卡片中，增加了操作成本
2. 导出和分享与其他使用率较低的功能放在一起，比较混乱
我认为现在【更多】气泡卡片中承载了太多功能，也为常用功能增加了操作成本

**形容一下你想要的解决方案**
将导出和分享按钮移到Header栏中，与发布/编辑/更多按钮同级，在我司内部已完成，改完是这样的：
![image](https://user-images.githubusercontent.com/48168645/200986833-abbdc76e-92fd-44b6-a8e4-295f48531b99.png)
![image](https://user-images.githubusercontent.com/48168645/200986881-64d06771-9195-4a1a-911b-0b501d43f999.png)

**Comment by lbship** [comment]
支持，这个建议还是挺实用的

**Comment by scottsut** [comment]
我们暂无计划，支持你自行二次开发来满足业务诉求👍
