### ISSUE TITLE
可视化数据如何修改limit 限制

### ISSUE THREAD

**Issue by magicxixi** [running-elephant/datart#2069]
datart中可视化分析如何修改这个 limit 限制，数据周期较长，数据量较大
![image](https://user-images.githubusercontent.com/41222672/201882544-7f59dead-b97d-4c5b-ad26-30c8ee7fe2f3.png)

**Comment by qxqzx13** [comment]
可以在对应视图中修改limit

**Comment by scottsut** [comment]
分析栏自行设定“总行数”
