### ISSUE TITLE
数据源缓存问题以及使用同步数据库模式问题

### ISSUE THREAD

**Issue by MybeautifulSunShine** [running-elephant/datart#2070]
1 数据源我使用的Http 把缓存开了 并且设置缓存的时间为2分钟 
2 更新http返回的数据 在数据视图中该数据并没有更改
3 把缓存关闭 该数据会随着http返回的数据而更改
4 然后又开启缓存,再次查询此数据就又变回之前的数据 造成脏读的现象
 
然后我又点击同步数据库模式也没起作用 
所以这个缓存好像不是随着数据源返回的结果而更改 也就是说这个http数据源 的缓存与 真实返回的数据不一致 
 
问题 1 我应该怎么样操作 才能更新缓存? (除了关闭缓存功能) 
问题2  这个缓存功能是不是与平常理解的一样随着源数据的更改而更改吗

**Comment by scottsut** [comment]
1. 频繁开闭缓存会再次这种现象，需要等上次缓存过期才能更新。
2. 你对缓存的理解可能和我们不一致，缓存功能是为了缓解数据源端压力，不用每次查询都从数据源重新取数。如果你期望每次查询到最新数据，就不要开启缓存。
