### ISSUE TITLE
希望支持多机部署，下载文件可配置OSS

### ISSUE THREAD

**Issue by jsrgjcy** [running-elephant/datart#2072]
想将服务进行多机部署，使用Nginx分摊访问压力。

但是下载的Excel等文件都存在于本地机器上，不是统一的文件访问路径，因此无法集群部署。希望能添加支持

**Comment by scottsut** [comment]
集群部署一直都是支持的，文件路径可以按照[文档描述](https://running-elephant.github.io/datart-docs/docs/#3-2-3-datart-%E5%85%A8%E5%B1%80%E9%85%8D%E7%BD%AE)进行外部挂载。

**Comment by jsrgjcy** [comment]
![image](https://github.com/running-elephant/datart/assets/12188493/f9c6d443-8953-4c95-891c-a92b0600b171)
这个配置能设置为 OSS、FTP这种文件地址吗？账密怎么配置？

**Comment by scottsut** [comment]
> 这个配置能设置为 OSS、FTP这种文件地址吗？账密怎么配置？

目前还不支持。

**Comment by xucw** [comment]
@scottsut datart集群部署，有部署文档吗？
