### ISSUE TITLE
仪表盘分享链接的加载性能有很大问题

### ISSUE THREAD

**Issue by gongfanfei** [running-elephant/datart#2077]
**Datart Version**
rc-1
**Describe the bug**
自由仪表盘组件内容越多，分享的URL对应加载时间越长

**To Reproduce**
1. 创建个自由仪表盘
2. 先添加两个组件，分享链接的 加载速度还是可以的
3. 组件添加至20个，分享链接的 加载消耗时间越长

**Expected behavior**
期望：无论仪表盘内容组件多少，链接加载的时间可以优化3-5s。数据可以页面打开后加载

**Additional context**

**Comment by scottsut** [comment]
浏览器会限制单页面请求并发数量，chrome 中是6个并行请求，因此仪表板加载速度取决于图表背后的数据查询效率。
