### ISSUE TITLE
当对应的SQL查询报错时，仪表板控件没有正确的显示错误标记和错误信息

### ISSUE THREAD

**Issue by q1139168548** [running-elephant/datart#2095]
**Datart版本号**
1.0.0 rc1

**错误描述**
当图表组件查询报错（由F12开发人员工具看到的），图表组件右上角Toolbar中的错误图标没有显示，也无任务错误信息展示

**如何重现**

我已在DEMO环境中复现，[ISSUE2095_TEST](http://datart-demo.retech.cc/organizations/56079285f2014850a7aadac44c2e4169/vizs/45c5e58fe8e946a5b14ca10fb82486a4)
1.新建一个包含表达式变量的数据视图，SQL设置为：`SELECT 1 $VAR1$`，此时能够执行成功，并可以保存
2.新建一个仪表板，为上一个SQL创建一个简单的表格图表，加入到这个仪表板中
3.在仪表板中新建一个文本控制器，绑定 `VAR1` 变量
4.在控制器中输入任意值，此时SQL会变为 `SELECT 1 'ABC'`，语法有误
5.后端抛出`SQLSyntaxErrorException，Unknown column 'ABC' in 'field list'`，
6.前端无反应

**期望结果**
正确的展示错误图标、抛出展示错误信息

**Comment by q1139168548** [comment]
我定位的初步原因是在
`frontend/src/app/pages/DashBoardPage/pages/Board/slice/thunk.ts`的440行
`
dispatch(
        boardActions.setWidgetErrInfo({
          boardId,
          widgetId,
          errInfo: getErrorMessage(error),
          errorType: 'request',
        }),
);
`
这里调用的  `getErrorMessage(error)`  方法，传入的ERROR对象是被`request.ts`的`standardErrorMessageTransformer`方法处理过的，所以会返回这个方法会返回undifined

**Comment by Cuiyansong** [comment]
LGTM
