### ISSUE TITLE
希望能在图表中加一个特别关注 的筛选条件 和特别关注图标。

### ISSUE THREAD

**Issue by xuhuandeshilinghun** [running-elephant/datart#2098]
说明：
 因为图表查看会带筛选条件， 特别关注 这个功能 和图表应该算比较搭配的， 用户习惯可能会关注某些数据，所以要是有这个功能，用户就不用在重新查了，直接在特别关注筛选框中，找到相应的数据。 图表给人的感觉其实就是方便 和 简洁。尽可能的以最少的文字 让用户看到更多有价值的信息。所以， 特别关注这个功能，我觉得，比较重要的。

大致需求：
1. 在 图表框内，可以加一个特别关注的 五角星，点击灰色变金色，关注。把关注的内容保存进表里； 
2. 在筛选条件里，可以把特别关注这个列表展示出来。  （在 编辑图表时，选择筛选条件时，可以加一个特变关注的组件，然后用户可以拖动某个字段作为特别关注的字段。）；
 3.   图表展示时， 特别关注字段，在筛选条件 上面一栏，和其他条件展示一起即可。 特别关注可以通过下拉列表展示。 

**其他内容**
![1](https://user-images.githubusercontent.com/26674252/221147701-0ed7d724-ac0d-4863-82ab-75835c818508.png)

![2](https://user-images.githubusercontent.com/26674252/221147738-3ef3a6d3-db9c-4438-8a1c-5d6073020a11.jpg)

**Comment by scottsut** [comment]
暂不考虑，谢谢建议！
