### ISSUE TITLE
Feature add StarRocks datasource extend

### ISSUE THREAD

**Issue by jianjun159** [running-elephant/datart#2120]
**Is your feature request related to a problem? Please describe.**
Expect the StarRocks option in the data source

**Describe the solution you'd like**
You can select the StarRocks when the data source is connected

**Describe alternatives you've considered**
You can use the MySQL or Doris connection mode

**Additional context**

**Comment by jianjun159** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/128395511/228139941-f8fe89fa-4654-4d16-b2c2-4433e310dd6d.png">

**Comment by scottsut** [comment]
请参考文档[扩展JDBC数据源](https://running-elephant.github.io/datart-docs/docs/jdbc.html)章节

**Comment by jianjun159** [comment]
> 请参考文档[扩展JDBC数据源](https://running-elephant.github.io/datart-docs/docs/jdbc.html)章节

已参考扩展JDBC数据源章节，并发起PR #2121 ，感谢您百忙之中的回复
