### ISSUE TITLE
分享页输入查询时接口响应中有没有标识

### ISSUE THREAD

**Issue by linyinxiang** [running-elephant/datart#2136]
**你的功能要求与某个问题相关吗？**
分享页查询时接口请求中没标识,不知道是否请求中还是没数据

**形容一下你想要的解决方案**
增加loading?

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截

**Comment by scottsut** [comment]
查询中图表组件右上角有loading图表
