### ISSUE TITLE
数据视表【合计】值错误

### ISSUE THREAD

**Issue by llf007** [running-elephant/datart#2137]
**Datart版本号**
声明一下你正在使用的 `datart` 版本号
版本: 1.0.0-rc.2

**错误描述**
数据视表总行数，会影响正确的合计值，尤其是当数据库明细行数超1000行时。
例如：当总行数为100行、1000行时合计值不同

![image](https://user-images.githubusercontent.com/60683568/230024380-e4cfa377-a27e-474f-8f30-bbe027daf903.png)

**如何重现**
重现错误的步骤，例如：
1、数据透视表-启用总计
2、修改总行数，当总行数改为5000以上时，客户端浏览器卡到不使用
![image](https://user-images.githubusercontent.com/60683568/230024845-53cf10f2-2b99-4d3c-8a03-a0bc34113629.png)

**期望结果**
清晰简洁地描述你期望的结果是什么
希望总计是先SELECT出结果，再limit截取总行数。
![image](https://user-images.githubusercontent.com/60683568/230028557-6eac572b-11a3-48e5-81f2-d82237c8e08c.png)

**Comment by scottsut** [comment]
数据总行数不同时，合计值是有可能不一样的。按图中内容举例，当总行数分别为 1000 和 5000 条时，9E航空公司的航班号数量有可能不一致，导致汇总数据不一样。建议提供更加确凿的重现场景。

另外，建议在数据视图中通过 group by 和 limit 来进行验证，看看 limit 数量不同时，总计数是否会不一致。
