### ISSUE TITLE
连接mysql后即使是使用root账号运行后依然无法生成表格

### ISSUE THREAD

**Issue by JunmingZ** [running-elephant/datart#2154]
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/48620344/231709781-5588fa41-f88d-49d4-bc94-01d64d85eec6.png">

报异常
ERROR o.s.scheduling.quartz.LocalDataSourceJobStore : ClusterManager: Error managing cluster: Failure obtaining db row lock: Table 'datart.qrtz_locks' doesn't exist
org.quartz.impl.jdbcjobstore.LockException: Failure obtaining db row lock: Table 'datart.qrtz_locks' doesn't exist

**Comment by mainky** [comment]
这个问题我也遇到了，您解决了吗
