### ISSUE TITLE
【datart-dev】图表编辑报错

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#217]
第一步:
![image](https://user-images.githubusercontent.com/83893570/141734498-710b07a7-ae17-45dd-a46e-d34be4e8c7cb.png)

第二步： 图表名称没带过来
![image](https://user-images.githubusercontent.com/83893570/141734595-c0bb864d-86e8-4f27-8de9-81f26a7a554e.png)

第三步: 保存报错 "Request failed with status code 400". 原因: name字段为空.
![image](https://user-images.githubusercontent.com/83893570/141734714-9de2cadb-7656-424f-943c-3fafba5379c0.png)

**Comment by xieliuduo** [comment]
#215
