### ISSUE TITLE
【dev】数据视图非常慢

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#219]
![image](https://user-images.githubusercontent.com/83893570/141772286-c5646b41-138f-4128-accc-964f89ff48d9.png)
这种方式非常慢，半天出不来(数据量很大上千万了)

咨询下  目前后台逻辑是查询查询所有数据再java后台取 1000  而不是下面这种下推到数据库？

若改为
![image](https://user-images.githubusercontent.com/83893570/141772663-f66d8338-0cc3-42b0-b283-9c83638cffea.png)
很快能出来.

**Comment by scottsut** [comment]
是否在数据源中开启了 `serverAggregate ` ？

![image](https://user-images.githubusercontent.com/4098913/141775532-78fcdd2b-84ce-4aae-803d-54340df0208a.png)

**Comment by Data-bytes305** [comment]
![image](https://user-images.githubusercontent.com/83893570/141789232-9cb42e5c-948e-4273-896b-1b72488f98de.png)

**Comment by tianlu-root** [comment]
使用的是哪个版本？

**Comment by tianlu-root** [comment]
针对这个问题提交了一个fix，使用dev分支最新代码测试一下，看问题是不是得到解决？

**Comment by Data-bytes305** [comment]
还是非常的慢, 没有下面加limit 快.

**Comment by Data-bytes305** [comment]
而且保存的时候 一直转圈圈 要很久.
![image](https://user-images.githubusercontent.com/83893570/141935870-79ebd187-63c5-47f8-86f6-fdbc66037a47.png)
保存的时候还会在数据库执行一遍sql嘛？

**Comment by Data-bytes305** [comment]
![Uploading image.png…]()
而且这种方式跟我在数据库里执行性能也相差很大.

**Comment by tianlu-root** [comment]
根据你的描述，问题更像是网络或者服务器资源配置问题。检查一下服务器端网络延迟情况和服务器资源是否充足？

**Comment by Data-bytes305** [comment]
服务器网络肯定没问题的. 我在davinci系统很快就能出来. 

![image](https://user-images.githubusercontent.com/83893570/141947692-c98436c2-7294-4610-837e-7aa0b6d2b581.png)

**Comment by scottsut** [comment]
@Data-bytes305 有找到最终原因吗？
