### ISSUE TITLE
数据视图 中文名称 保存出现了乱码

### ISSUE THREAD

**Issue by zhouwenblog** [running-elephant/datart#22]
![图片](https://user-images.githubusercontent.com/31482780/137522126-5bd33bd2-873c-4128-9d30-d41b9f346a5b.png)

数据库用utf-8 ,application-config.yml 里面也要在jdbc连接串里面加上useUnicode=true&characterEncoding=utf-8
 url: jdbc:mysql://xxxx:3306/datart?&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8

**Comment by xieliuduo** [comment]
数据库用utf-8 ,application-config.yml 里面也要在jdbc连接串里面加上utf-8 
 url: jdbc:mysql://192.168.234.128:3306/datart?&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8
