### ISSUE TITLE
表格、数据透视表【合计】与【分页】问题

### ISSUE THREAD

**Issue by llf007** [running-elephant/datart#2219]
**Datart版本号**
声明一下你正在使用的 `datart` 版本号:
v1.0.0-rc.2

例如：表格数据有5000行
合计值应为：所有行的合计

不能因为启用分页
合计值变为：一个分页的合计

以下是一个最简单例子：
![image](https://github.com/running-elephant/datart/assets/60683568/4399af9b-31c5-4cec-abe0-98fd68e9ed4e)

![image](https://github.com/running-elephant/datart/assets/60683568/e8682900-1b5c-42ce-a6cc-6b36ff8d5f0d)

**Comment by byc233518** [comment]
会不会这样更容易产生误解
