### ISSUE TITLE
柱状图是否支持动态排序

### ISSUE THREAD

**Issue by jcchai1205** [running-elephant/datart#2234]
echart支持动态排序柱状图，datart是否支持？

**描述一下你考虑过的备选方案**
自定义插件化图表是否可以实现？在生命周期函数中执行定时任务？onMount启用定时任务？

**Comment by scottsut** [comment]
可以去跑象公众号搜一搜去年图表插件开发大赛文章，参赛选手天河的作品就是动态排序柱状图，你可以参考一下
