### ISSUE TITLE
仪表板-自由布局-配置等比宽度缩放，当在浏览器打开仪表板时，右侧和下方会有空白部分

### ISSUE THREAD

**Issue by inkshj** [running-elephant/datart#2243]
**Datart版本号**
1.0.0-rc.2

**错误描述**
仪表板-自由布局-配置等比宽度缩放，当在浏览器打开仪表板时，右侧和下方会有空白部分
![image](https://github.com/running-elephant/datart/assets/93383659/9e54b79e-997d-4acd-a6c7-2f8192101578)

![image](https://github.com/running-elephant/datart/assets/93383659/c1b3a651-3681-42ea-b97a-48d44a389355)

**如何重现**
1. 新建自由布局的仪表板，添加背景颜色，配置等比宽度缩放；保存
2. 分享管理-添加链接
3. 复制链接在浏览器中打开

**期望结果**
自由布局并且时等比宽度缩放的仪表板，待不同尺寸的屏幕下打开右侧及下方不会有空白部分

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: mac
- 数据源: MySQL 8.0.13
- 浏览器: chrome

**Comment by scottsut** [comment]
Related to #1901

**Comment by Sunzhuokai** [comment]
Related       [newBackgroundStyle.overflow = 'auto';](https://github.com/running-elephant/datart/blob/f52621a3064cd919b631b3cfbc5972edf7501875/frontend/src/app/pages/DashBoardPage/hooks/useSlideStyle.ts#L172)

**Comment by inkshj** [comment]
后续会做优化吗，有没有具体修复的时间

**Comment by qiangxue1206** [comment]
> Related [newBackgroundStyle.overflow = 'auto';](https://github.com/running-elephant/datart/blob/f52621a3064cd919b631b3cfbc5972edf7501875/frontend/src/app/pages/DashBoardPage/hooks/useSlideStyle.ts#L172)

有用，全屏缩放时，不需要设置滚动，这样才能全屏铺满，下方不会有留白
