### ISSUE TITLE
[dev]-[widget]-数据格式化错误

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#254]
选择格式  ->  数字型 -> 单位为万 且 启动了分隔符时，前端页面没有显示‘万’
![image](https://user-images.githubusercontent.com/83893570/143189020-4d84de42-aeeb-4874-9212-851cb891a752.png)

![image](https://user-images.githubusercontent.com/83893570/143189182-a1037a20-2c5b-4868-9b6a-16efd8bc53a1.png)

**Comment by Cuiyansong** [comment]
没有复现，在Chart编辑器界面，可以显示“启用分隔符”。请问，第二个截图，是在哪里操作的？

**Comment by Data-bytes305** [comment]
刚打包最新的dev.  翻牌器
![image](https://user-images.githubusercontent.com/83893570/143215030-046bde83-5acb-4f0e-96fc-a419a7938def.png)
