### ISSUE TITLE
支持在ChartConfig中直接引入组件

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#260]
**描述**:
ChartConfig 当前只支持在配置项写入详细的配置，但是会遇到某些复杂的场景，配置花销可能大于直接引入组件，能否支持将chart需要的数据和方法直接暴露给自定义的组件，减少繁重的配置

**解决方案**
如 ChartStyleSectionRowOption加入CustomComponent: MemoExoticComponent，向其暴露数据、样式、配置属性和更新方法

**背景**
实际开发中，遇到了比较特殊的需求，如在table中加入自定义条件扩展table的显示功能，需要复杂的弹窗交互

**Comment by Cuiyansong** [comment]
1. ChartConfig的基础是JSON Schema的表单样式配置，表单配置支持无限级的嵌套和面板/模态对话框的切换，当然遇到复杂的交互场景，目前只用JSON Schema定义确实有些繁重和困难。
2. “如 ChartStyleSectionRowOption加入CustomComponent: MemoExoticComponent，向其暴露数据、样式、配置属性和更新方法”，请详细展开说明，没有Get到问题。
3. 除了基于JSON Schema的方式，只能二开封装组件，DataReferencePanel.tsx, UnControlledTableHeaderPanel.tsx 等自定义组件。

对于给出的“解决方案”，还希望能详细说明

**Comment by Wesilnt** [comment]
1、针对您回答的第二点：ItemLayout中的 ChartStyleSectionComponentType switch，我理解为公用配置组件分支，但是UnControlledTableHeaderPanel等明显偏向于独立需求的组件，难以给别的组件公用，这样以后类似的独立需求多了就显得ItemLayout很杂，也不符合这部分组件设计的初衷，所以在此二开封装的意愿不是很强烈。

2. 我的设想如下，在JSON Schema引入配置和自定义组件，在使用时，通过统一的CustomEffectComponentWrapper组件外包裹，向下传递图表配置的属性和方法。
如图，假如我要开发table 条件格式功能，
![image](https://user-images.githubusercontent.com/27821997/144408820-7c55025c-53fb-432f-a5c0-a414781972dd.png)

![image](https://user-images.githubusercontent.com/27821997/144408289-b77f9d59-dd6c-48e9-b0e4-71285a8448ab.png)

不知道这样能不能说清楚，谢谢

**Comment by Cuiyansong** [comment]
十分感谢您的回复。
> “针对您回答的第二点：ItemLayout中的 ChartStyleSectionComponentType switch，我理解为公用配置组件分支，但是UnControlledTableHeaderPanel等明显偏向于独立需求的组件，难以给别的组件公用，这样以后类似的独立需求多了就显得ItemLayout很杂，也不符合这部分组件设计的初衷，所以在此二开封装的意愿不是很强烈。”
我们可能理解的“设计初衷”可能有点出入。插件化的设计初衷还是方便提供“非”技术人员在**有限集**范围内制作图表，而不是**开放插件化的能力给开发人员**。Chart Config的无限级表单功能就是在一定程度上解决复杂性的问题。

对自定义表单的设计还有更多的想法和建议，欢迎留言讨论。
