### ISSUE TITLE
watcher方法支持多依赖和跨配置项依赖

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#261]
**你的功能要求与某个问题相关吗？**
在开发时候，我遇到了一个问题，比如我在样式中新增某个属性，这个属性的禁用状态依赖配置中的是否分页和自动加载。但是通过watcher无法做到

**形容一下你想要的解决方案**
watcher方法能够支持多种依赖，并且能监听到数据、样式、配置的所有属性更新

**Comment by Cuiyansong** [comment]
感谢提出建议。目前来讲，依赖确实只能是**同一层次**的**数据值**进行监听。无法跨层级更多的考量是不同层级组件之间的Graph图的循环依赖关系引起的一系列问题，同时，对于复杂的交互需求，目前还是比较建议进行二开封装自定义组件。

**Comment by Cuiyansong** [comment]
If you have more comments, please reopen the issue.
