### ISSUE TITLE
原始数据不生效

### ISSUE THREAD

**Issue by RunningXuan** [running-elephant/datart#28]
![image](https://user-images.githubusercontent.com/47099551/137576110-9112899b-6715-4ad2-bccc-cd169276d2af.png)

**Comment by scottsut** [comment]
widget 名称可以在左侧文件目录的扩展按钮点击“基本信息”进行修改

**Comment by xieliuduo** [comment]
如果是在board内 新建的chart ，显示就是这个widget的名字，
![image](https://user-images.githubusercontent.com/23504234/137593463-66c95d1a-947e-4a48-98e9-bb88bbba2d36.png)

![image](https://user-images.githubusercontent.com/23504234/137593473-4ba04959-ebd0-4637-b881-a83add363901.png)

**Comment by scottsut** [comment]
Related to #242
