### ISSUE TITLE
tree expandedKeys处理逻辑优化

### ISSUE THREAD

**Issue by edison-tianhe** [running-elephant/datart#280]
**当前效果**
![image](https://user-images.githubusercontent.com/35984031/144046545-da9eeefd-c121-49e6-bf69-8e28b86b047e.png)
如图，从库->表->字段都是异步加载。但是如果我在第一次进入页面。搜索了其中一个字符，`expandedKeys`会接收所有符合条件的`key`。

**问题**
现在有5个库，每个库大概有100张表。在进入页面之后，首先把对应5个库的表全部请求过来(现在页面大概有500个表信息)。如果我此时进行搜索某个字段，然后会有100个表信息符合要求。这个时候`expandedKeys`就会有100个。antd会默认展开其子集，也就是会发送100个ajax。
库越大，表越多，其ajax就会越多

**期望**

- `expandedKeys`生成逻辑，只获取parentKey，不拿本身的Key。这样会避免展开子集，也就不会有这么夸张的请求量

如果觉得这种解决思路可以，可以帮忙提供pr

**Comment by scottsut** [comment]
> * `expandedKeys`生成逻辑，只获取parentKey，不拿本身的Key。这样会避免展开子集，也就不会有这么夸张的请求量
> 
> 如果觉得这种解决思路可以，可以帮忙提供pr

不拿本身的 Key，或是判断 children 长度来决定是否展开，都可以，欢迎 pr 👏👏👏
