### ISSUE TITLE
Configuration.tsx(61,7)： Property 'css' does not exist on type

### ISSUE THREAD

**Issue by berg-xu** [running-elephant/datart#286]
**Describe the bug**
请教个问题，编译frontend时出现如下错误:

 Property 'css' does not exist on type 'IntrinsicAttributes & Omit<ProTableProps<T, ParamsType, "text">, "onChange"> & { value?: T[] | undefined; 

具体如下图所示：

![c157506ef943e69b68217975115b7e0](https://user-images.githubusercontent.com/45385723/144165270-e8bf2b48-11a4-46e0-8b26-96a53c03429d.png)

各个组件版本依赖按照 datart\frontend\package.json 完成版本依赖。

请问怎么解决这个问题哈

**Comment by scottsut** [comment]
项目里已经全局声明了 [styled-components/cssprop](https://github.com/running-elephant/datart/blob/master/frontend/src/react-app-env.d.ts) 依赖，按理说不会有错误提示。你可以自己按照下方 issue 里建议的方式都试试，看看哪个能解决你的问题

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31245
