### ISSUE TITLE
如何引入高德地图

### ISSUE THREAD

**Issue by Cuiyansong** [running-elephant/datart#288]
**需求**
在Datart图表编辑器中，以插件化的方式增加对高德地图的使用。

**方案**
借助EChart的Amap Extension使用高德图表API，来制作插件化图表。然后将制作好的图表，以特性的文件形式放置于生产环境的某目录下使用。同时，支持Dev环境便捷开发，增产增效。

**功能**
- [x] 插件化支持纯函数的简单JavaScript插件图表（无export关键字的Function函数文件）
- [x] 插件化支持IIFE方式经过打包后的插件图表（No Module Name in IIFE）
- [x] Dev开发环境自动化支持，无需手动配置新增图表路径
- [ ] 插件打包优化
- [ ] 支持ESM，SystemJS加载方式

**Comment by Cuiyansong** [comment]
## 1. 插件化图表的相关概念和介绍

## 2. 从非官网的示例图表库中下载示例
[插件图表样例库-非官方](https://github.com/Cuiyansong/datart-extension-charts)

## 3. 在Datart中使用示例图表
- Development环境： 可直接将文件xxxx.iife.js拷贝到前端`public/custom-chart-plugins`文件夹下，重新启动`yarn start`程序即可，在Dev环境启动后，前端会自动扫描文件夹下所有文件，并在用户**登陆**后加载图表。
- Production环境：可直接将文件拷贝到服务端目录`public/custom-chart-plugins`文件夹下，重新登陆即可。
- 基于Datart二次开发用户：可参考对应的插件化的实现方案，自主封装成React组件即可，将插件化中工具函数替换掉即可。

**Comment by YQChen-SYSU** [comment]
请教一个问题，关于amap怎么使用呢？数据需要的维度类型格式都不太清楚，能否给出heatmap的demo，静态数据的热力可以实现，数据更新部分的热力不知道怎么写
