### ISSUE TITLE
普通的查看用户具有组织添加权限

### ISSUE THREAD

**Issue by RunningXuan** [running-elephant/datart#32]
![image](https://user-images.githubusercontent.com/47099551/137576965-6b4284c6-abb3-4a3f-9bd3-078a31757a4e.png)
组织管理的权限也纳入权限管理

**Comment by scottsut** [comment]
设计是这样的，允许所有租户自己创建组织，制作自己的可视化作品。所有资源以组织为单位隔离

**Comment by RunningXuan** [comment]
同一个组织内部的设置了只读，意思就是没有别的使用权限了，如果他注册新组织，则他有权制作自己的可视化作品；这样一个组织内部内能进行管理，否则都乱了

**Comment by scottsut** [comment]
> 同一个组织内部的设置了只读，意思就是没有别的使用权限了，如果他注册新组织，则他有权制作自己的可视化作品；这样一个组织内部内能进行管理，否则都乱了

这个其实是个和设计理念相关的话题，datart 的多租户设计和 davinci 一脉相承，目的就是为了让平台内的所有用户都能参与可视化作品制作，如果需要做功能和数据权限管理，单个组织下的权限控制完全可以满足企业使用。至于你说的“如果他注册新组织，则他有权制作自己的可视化作品”，我觉得企业内部管理好数据源就行，普通用户就算是创建了组织，拿不到关键数据源信息，也不会造成混乱。
