### ISSUE TITLE
布局容器   多个页面除第一个页面之外，点击进去不自动加载

### ISSUE THREAD

**Issue by 1614148516** [running-elephant/datart#339]
**错误描述**
利用标签布局之后，多个页面除第一个页面之外，点击进去不自动加载的问题，预计在什么时间能修复呀，感觉这个功能严重影响对外输出报告

![image](https://user-images.githubusercontent.com/33084611/145370625-b6a32470-765b-4e70-9cc5-bb711591d8a9.png)

![c31090c87900e35b9d5df2d28bf3dcf](https://user-images.githubusercontent.com/33084611/145370399-e485d99f-0d1b-4ce7-8a61-a67d72a16fd4.png)

**Comment by xieliuduo** [comment]
请描述一下  是哪个版本

**Comment by xieliuduo** [comment]
原来的 auto  board 加载 逻辑有缺陷。 当检测到auto board 父容器容器大小为0 的时候不加载数据。要加上一段逻辑，当容器大小>0 的时候，要恢复加载数据。 所以当 tabWidget->iframe->shareAuto-Board 。tabIndex!==0 的时候 会有问题。此问题已经被解决。
