### ISSUE TITLE
数据视图支持类似Excel拖拉拽生成数据

### ISSUE THREAD

**Issue by JLucky** [running-elephant/datart#343]
**你的功能要求与某个问题相关吗？**
目前数据视图只能通过SQL生成数据，不会SQL的业务人员无法使用

**形容一下你想要的解决方案**
数据视图支持类似Excel拖拉拽功能，生成数据集，再进行可视化操作。方便不会SQL的用户使用，扩大用户群体，降低上手难度。

**描述一下你考虑过的备选方案**
无

**其他内容**
无

**Comment by scottsut** [comment]
#1476 #1482
