### ISSUE TITLE
公共变量-关联成员点击确定没能生效

### ISSUE THREAD

**Issue by francis-xjl** [running-elephant/datart#350]
**Describe the bug**
公共变量-关联成员点击确定没能生效。

**Screenshots**
<img width="1207" alt="企业微信20211213-174604@2x" src="https://user-images.githubusercontent.com/17879879/145789238-7cf89ffb-f772-48c7-ae84-11eeb08b2cf2.png">

**Comment by scottsut** [comment]
变量值需要回车添加

**Comment by francis-xjl** [comment]
ok，感觉回复，确实可以保存。
