### ISSUE TITLE
中文列名不支持，直接显示成问号

### ISSUE THREAD

**Issue by Cheney1997** [running-elephant/datart#367]
**Datart Version**
1.0.0 alpha3

**Describe the bug**
视图中写sql，列名为中文时，直接显示问号

**Screenshots**
![image](https://user-images.githubusercontent.com/39380891/146005646-04de1bd0-890c-48ec-bd24-aba03b2bb9d3.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS:  Windows 10
 - Source Database: MySQL 5.7.35
 - Browser: chrome 94

**Comment by scottsut** [comment]
参考 #22

**Comment by Cheney1997** [comment]
> 参考 #22

这是两个问题哦，datart用的数据库连接已经加上相关参数，我保存视图已可以使用中文名称

这是执行sql时，sql用中文别名，执行结果中，中文列名显示为问号

**Comment by scottsut** [comment]
数据源配置中的连接参数中是否有指定 utf8 字符集？

![image](https://user-images.githubusercontent.com/4098913/146138687-9d44462d-20b9-4aad-a560-cd7326981281.png)

**Comment by Cheney1997** [comment]
> 数据源配置中的连接参数中是否有指定 utf8 字符集？
> 
> ![image](https://user-images.githubusercontent.com/4098913/146138687-9d44462d-20b9-4aad-a560-cd7326981281.png)

原本加在了下面的参数配置中，现在修改到连接信息中用问号拼接才生效， 加下面不起作用
![image](https://user-images.githubusercontent.com/39380891/146139707-7141af36-4849-489c-9103-ceb023ea9c4c.png)

此配置方式是与davinci中一致的，davinci中参数统一配置在了下面，支持中文

**Comment by scottsut** [comment]
好的，mysql 确实需要加到 url 中才能生效

**Comment by scottsut** [comment]
datart 数据源的 `properties` 有明确指出是连接池参数，所以数据库连接参数需要在 `url` 中拼写
