### ISSUE TITLE
筛选器设置成默认无效

### ISSUE THREAD

**Issue by Cheney1997** [running-elephant/datart#368]
**Datart Version**
1.0.0 alpha.3

**Describe the bug**
筛选器新建自定义后，选中其中一个设置为默认，保存，无效，接口显示400报错

**Screenshots**
界面选择
![image](https://user-images.githubusercontent.com/39380891/146010645-59b2750b-2ed3-45ca-a399-db43dbada473.png)

**接口**
/api/v1/data-provider/execute

**接口报错日志**
{"data":null,"errCode":0,"exception":{"@type":"datart.core.base.exception.NotFoundException","cause":null,"errCode":0,"localizedMessage":"{0}不存在 不存在 ","message":"{0}不存在 不存在 ","stackTrace":[{"className":"sun.reflect.NativeConstructorAccessorImpl","fileName":null,"lineNumber":-2,"methodName":"newInstance0","nativeMethod":true},{"className":"sun.reflect.NativeConstructorAccessorImpl","fileName":null,"lineNumber":-1,"methodName":"newInstance","nativeMethod":false},{"className":"sun.reflect.DelegatingConstructorAccessorImpl","fileName":null,"lineNumber":-1,"methodName":"newInstance","nativeMethod":false},{"className":"java.lang.reflect.Constructor","fileName":null,"lineNumber":-1,"methodName":"newInstance","nativeMethod":false},{"className":"datart.core.base.exception.Exceptions","fileName":"Exceptions.java","lineNumber":52,"methodName":"tr","nativeMethod":false},{"className":"datart.core.base.exception.Exceptions","fileName":"Exceptions.java","lineNumber":36,"methodName":"notFound","nativeMethod":false},{"className":"datart.server.service.BaseCRUDService","fileName":"BaseCRUDService.java","lineNumber":195,"methodName":"notFoundException","nativeMethod":false},{"className":"datart.server.service.BaseCRUDService","fileName":"BaseCRUDService.java","lineNumber":53,"methodName":"retrieve","nativeMethod":false},{"className":"datart.server.service.BaseCRUDService$$FastClassBySpringCGLIB$$74d18de4","fileName":"<generated>","lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.cglib.proxy.MethodProxy","fileName":"MethodProxy.java","lineNumber":218,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor","fileName":"CglibAopProxy.java","lineNumber":688,"methodName":"intercept","nativeMethod":false},{"className":"datart.server.service.impl.ViewServiceImpl$$EnhancerBySpringCGLIB$$fae76a49","fileName":"<generated>","lineNumber":-1,"methodName":"retrieve","nativeMethod":false},{"className":"sun.reflect.GeneratedMethodAccessor159","fileName":null,"lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"sun.reflect.DelegatingMethodAccessorImpl","fileName":null,"lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"java.lang.reflect.Method","fileName":null,"lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.aop.support.AopUtils","fileName":"AopUtils.java","lineNumber":344,"methodName":"invokeJoinpointUsingReflection","nativeMethod":false},{"className":"org.springframework.aop.framework.JdkDynamicAopProxy","fileName":"JdkDynamicAopProxy.java","lineNumber":208,"methodName":"invoke","nativeMethod":false},{"className":"com.sun.proxy.$Proxy142","fileName":null,"lineNumber":-1,"methodName":"retrieve","nativeMethod":false},{"className":"datart.server.service.BaseService","fileName":"BaseService.java","lineNumber":73,"methodName":"retrieve","nativeMethod":false},{"className":"datart.server.service.impl.DataProviderServiceImpl","fileName":"DataProviderServiceImpl.java","lineNumber":211,"methodName":"execute","nativeMethod":false},{"className":"datart.server.controller.DataProviderController","fileName":"DataProviderController.java","lineNumber":101,"methodName":"execute","nativeMethod":false},{"className":"sun.reflect.GeneratedMethodAccessor219","fileName":null,"lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"sun.reflect.DelegatingMethodAccessorImpl","fileName":null,"lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"java.lang.reflect.Method","fileName":null,"lineNumber":-1,"methodName":"invoke","nativeMethod":false},{"className":"org.springframework.web.method.support.InvocableHandlerMethod","fileName":"InvocableHandlerMethod.java","lineNumber":197,"methodName":"doInvoke","nativeMethod":false},{"className":"org.springframework.web.method.support.InvocableHandlerMethod","fileName":"InvocableHandlerMethod.java","lineNumber":141,"methodName":"invokeForRequest","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod","fileName":"ServletInvocableHandlerMethod.java","lineNumber":106,"methodName":"invokeAndHandle","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","fileName":"RequestMappingHandlerAdapter.java","lineNumber":894,"methodName":"invokeHandlerMethod","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter","fileName":"RequestMappingHandlerAdapter.java","lineNumber":808,"methodName":"handleInternal","nativeMethod":false},{"className":"org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter","fileName":"AbstractHandlerMethodAdapter.java","lineNumber":87,"methodName":"handle","nativeMethod":false},{"className":"org.springframework.web.servlet.DispatcherServlet","fileName":"DispatcherServlet.java","lineNumber":1060,"methodName":"doDispatch","nativeMethod":false},{"className":"org.springframework.web.servlet.DispatcherServlet","fileName":"DispatcherServlet.java","lineNumber":962,"methodName":"doService","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":1006,"methodName":"processRequest","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":909,"methodName":"doPost","nativeMethod":false},{"className":"javax.servlet.http.HttpServlet","fileName":"HttpServlet.java","lineNumber":652,"methodName":"service","nativeMethod":false},{"className":"org.springframework.web.servlet.FrameworkServlet","fileName":"FrameworkServlet.java","lineNumber":883,"methodName":"service","nativeMethod":false},{"className":"javax.servlet.http.HttpServlet","fileName":"HttpServlet.java","lineNumber":733,"methodName":"service","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":227,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":162,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.tomcat.websocket.server.WsFilter","fileName":"WsFilter.java","lineNumber":53,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":189,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":162,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.RequestContextFilter","fileName":"RequestContextFilter.java","lineNumber":100,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.springframework.web.filter.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":119,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":189,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":162,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.FormContentFilter","fileName":"FormContentFilter.java","lineNumber":93,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.springframework.web.filter.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":119,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":189,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":162,"methodName":"doFilter","nativeMethod":false},{"className":"org.springframework.web.filter.CharacterEncodingFilter","fileName":"CharacterEncodingFilter.java","lineNumber":201,"methodName":"doFilterInternal","nativeMethod":false},{"className":"org.springframework.web.filter.OncePerRequestFilter","fileName":"OncePerRequestFilter.java","lineNumber":119,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":189,"methodName":"internalDoFilter","nativeMethod":false},{"className":"org.apache.catalina.core.ApplicationFilterChain","fileName":"ApplicationFilterChain.java","lineNumber":162,"methodName":"doFilter","nativeMethod":false},{"className":"org.apache.catalina.core.StandardWrapperValve","fileName":"StandardWrapperValve.java","lineNumber":202,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardContextValve","fileName":"StandardContextValve.java","lineNumber":97,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.authenticator.AuthenticatorBase","fileName":"AuthenticatorBase.java","lineNumber":542,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardHostValve","fileName":"StandardHostValve.java","lineNumber":143,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.valves.ErrorReportValve","fileName":"ErrorReportValve.java","lineNumber":92,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.core.StandardEngineValve","fileName":"StandardEngineValve.java","lineNumber":78,"methodName":"invoke","nativeMethod":false},{"className":"org.apache.catalina.connector.CoyoteAdapter","fileName":"CoyoteAdapter.java","lineNumber":346,"methodName":"service","nativeMethod":false},{"className":"org.apache.coyote.http11.Http11Processor","fileName":"Http11Processor.java","lineNumber":374,"methodName":"service","nativeMethod":false},{"className":"org.apache.coyote.AbstractProcessorLight","fileName":"AbstractProcessorLight.java","lineNumber":65,"methodName":"process","nativeMethod":false},{"className":"org.apache.coyote.AbstractProtocol$ConnectionHandler","fileName":"AbstractProtocol.java","lineNumber":887,"methodName":"process","nativeMethod":false},{"className":"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor","fileName":"NioEndpoint.java","lineNumber":1684,"methodName":"doRun","nativeMethod":false},{"className":"org.apache.tomcat.util.net.SocketProcessorBase","fileName":"SocketProcessorBase.java","lineNumber":49,"methodName":"run","nativeMethod":false},{"className":"java.util.concurrent.ThreadPoolExecutor","fileName":null,"lineNumber":-1,"methodName":"runWorker","nativeMethod":false},{"className":"java.util.concurrent.ThreadPoolExecutor$Worker","fileName":null,"lineNumber":-1,"methodName":"run","nativeMethod":false},{"className":"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable","fileName":"TaskThread.java","lineNumber":61,"methodName":"run","nativeMethod":false},{"className":"java.lang.Thread","fileName":null,"lineNumber":-1,"methodName":"run","nativeMethod":false}]},"message":"{0}不存在 不存在 ","pageInfo":null,"success":false}

**Comment by scottsut** [comment]
错误信息与控制器功能无关，请求到一个不存在的数据视图会报这个错误。alpha.3 版本的控制器功能经测试没有问题

**Comment by scottsut** [comment]
如果方便的话，可以提供更明确的复现步骤

**Comment by Cheney1997** [comment]
> 错误信息与控制器功能无关，请求到一个不存在的数据视图会报这个错误。alpha.3 版本的控制器功能经测试没有问题

此处控制器我目前未关联任何视图，单纯的新建一个控制器，选择自定义，然后新建值，第一次未选择任何默认值，编辑再设置默认值，无效

以上场景，我删除所有选项值，重新新建，设置其中一个默认值后，再次编辑该控制器，无法进行默认值修改，且未回显我上次默认值

**Comment by Cheney1997** [comment]
> 错误信息与控制器功能无关，请求到一个不存在的数据视图会报这个错误。alpha.3 版本的控制器功能经测试没有问题

![image](https://user-images.githubusercontent.com/39380891/146186275-666c422f-c722-43ff-8676-bba3f407026a.png)

**Comment by xieliuduo** [comment]
建议升级到alpha.3 版本。alpha.3 版本的控制器功能经测试没有问题,dev分值也会及时修复一些问题。谢谢反馈
