### ISSUE TITLE
筛选器关联组件时，字段与变量错误

### ISSUE THREAD

**Issue by Cheney1997** [running-elephant/datart#369]
**Datart Version**
1.0.0 alpha3.0

**Describe the bug**
筛选器关联组件时，视图中为变量，关联的选择中，变量下拉选项为空，字段下拉展示的是变量

Davinci中统一显示为变量

**Screenshots**
![image](https://user-images.githubusercontent.com/39380891/146011834-60029947-9ad6-483e-9917-ffc080ff2af6.png)

**Comment by scottsut** [comment]
截图里没有看出问题，从你的 issue #367 查询结果来看，截图中下拉菜单内容是字段，并没有错误

**Comment by Cheney1997** [comment]
额， 不好意思， 描述错误， 该视图有变量参数，可是变量中未展示出来

**Comment by Cheney1997** [comment]
> 截图里没有看出问题，从你的 issue #367 查询结果来看，截图中下拉菜单内容是字段，并没有错误

今天准备重现的时候，发现已经可以加载出来了，是否此处做了缓存策略

**Comment by scottsut** [comment]
没有做变量的缓存，不过如果声明了新的变量，仪表板编辑界面需要刷新或重新进入来获取
