### ISSUE TITLE
视图中变量的自动提示有很多重复项

### ISSUE THREAD

**Issue by Cheney1997** [running-elephant/datart#372]
**Datart Version**
1.0.0 alpha.3

**Describe the bug**
视图中编写sql，用$引入变量时，自动提示中有很多重复项

当前只创建了一个视图，声明了3个不同名的变量

**Screenshots**
![image](https://user-images.githubusercontent.com/39380891/146152614-b7c342eb-b0a4-4bdb-a358-b0c45461ed47.png)

**Comment by scottsut** [comment]
Duplicate of #224
