### ISSUE TITLE
变量与部分函数连用时，解析异常

### ISSUE THREAD

**Issue by Cheney1997** [running-elephant/datart#373]
**Datart Version**
1.0.0 aalpha.3

**Describe the bug**
当变量与DATE_FORMAT连用时，执行sql异常

**Screenshots**
![image](https://user-images.githubusercontent.com/39380891/146152974-7a6e7e8e-9d47-42bd-8b53-e7335791524f.png)

**Comment by scottsut** [comment]
变量格式有误，多了一个`$`

**Comment by Cheney1997** [comment]
> 变量格式有误，多了一个`$`

$${}$为自动提示补全写法，移除后依旧报错, 下图中两个变量一个都执行不成功  ↓↓↓↓↓↓↓↓

![image](https://user-images.githubusercontent.com/39380891/146183046-91cdaf04-fa33-470c-9393-8b0dae13f3fb.png)

移除time_type变量 ↓↓↓↓↓↓↓↓

![image](https://user-images.githubusercontent.com/39380891/146183815-069441a9-550c-4a51-8c7b-bf7f2f0b9007.png)

移除capture_day变量 ↓↓↓↓↓↓↓↓

![image](https://user-images.githubusercontent.com/39380891/146183980-74a5cd10-c320-444c-b3c5-a834aa39a0c1.png)

两个均移除，执行成功 ↓↓↓↓↓↓↓↓

![image](https://user-images.githubusercontent.com/39380891/146184187-bc810d46-538b-4155-a876-963c504e5fd2.png)

**Comment by scottsut** [comment]
日期类型变量默认值解析有问题
