### ISSUE TITLE
仪表板iframe组件

### ISSUE THREAD

**Issue by wangguoqi001** [running-elephant/datart#387]
**Datart版本号**
3.0
**错误描述**
仪表板iframe组件 嵌入外部页面显示有问题，嵌入后显示为datart自己的登录页，或目录页
**如何重现**
重现错误的步骤，例如：
1. 到...页面
2. 点击...
3. 滚动到...
4. 看到错误

**期望结果**
正差显示

**截图**
![image](https://user-images.githubusercontent.com/42573120/146492743-f4a4100d-6840-45d3-821a-e2a432356aa5.png)

**Comment by xieliuduo** [comment]
目标网页要允许 被嵌入iframe 才行，网页请求头里面的这个字段 X-Frame-Options，https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options。  显然，百度禁止了被其他网站的iframe 引入。 举个例子比如 https://www.bing.com 这个网站就可以成功。   
![image](https://user-images.githubusercontent.com/23504234/146642540-c2076462-f311-4b84-8065-2f3fa7dc44f7.png)
