### ISSUE TITLE
[dev][widget]双Y轴图无法显示数值

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#389]
**Datart Version**
最新dev

**Describe the bug**
双Y轴图 数值无法显示
**To Reproduce**

**Expected behavior**
希望显示数值
**Screenshots**
![image](https://user-images.githubusercontent.com/83893570/146639321-98b2ba32-67ea-495a-96b8-33fc3ffb3498.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10]
 - Source Database: mysql5.7
 - Browser: chrom

**Comment by Cuiyansong** [comment]
没显示数值可能是原始数据中（服务端返回的数据）在202107月，这个时间点上，没有‘xxx额’数值，请查验。
