### ISSUE TITLE
外链分享

### ISSUE THREAD

**Issue by ShawnSheno** [running-elephant/datart#391]
**Datart Version**
1.0.0-alpha.3

**Describe the bug**
点击分享外链，生成链接，再次点击分享外链去查看链接时，之前生成链接不存在了

**To Reproduce**
1. 创建仪表板，放入已做好的图表，
2. 点击“发布”，再点击“分享链接”按钮，填写日期（大于当前日期），点击“生成外链”。

3. 点击“复制”外链，点击“确定”，关闭当前弹窗
4. 再次点击分享“链接按钮”，想查看之前已分享的链接
5. 这个时候，弹窗内为空

**Expected behavior**
再次点击“分享外链”，能够看到之前生成的链接

**Screenshots**
![image](https://user-images.githubusercontent.com/34580770/146673046-06b581ef-945a-42e7-8c2e-284341e76c5b.png)

![image](https://user-images.githubusercontent.com/34580770/146673055-d648f3aa-e267-4090-bfc9-d0c81620a9e1.png)

**Comment by xieliuduo** [comment]
后期会提供 分享链接的管理页面。这里要不要显示之前分享过得链接，我们要讨论一下

**Comment by scottsut** [comment]
beta.3 版本已支持分享链接管理
