### ISSUE TITLE
[dev][VIEW] SQL parsing failed

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#410]
**Datart Version**
dev

**Describe the bug**
view sql解析失败

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/83893570/146872628-07912fce-1aaa-47b6-970e-0057bef9f3b5.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: mac
 - Source Database: mysql5.7
 - Browser: chrome

**Additional context**
1. 当剔除 if表达式时，能正常查询
![image](https://user-images.githubusercontent.com/83893570/146873347-fc5619d8-cb22-4d61-a164-d75d657275eb.png)

2. 若剔除函数时，能正常查询
![image](https://user-images.githubusercontent.com/83893570/146873520-abe5961b-1055-4d91-8935-6e1eee9a5d8b.png)

猜测是‘()’ 与 if 解析异常.

**Comment by tianlu-root** [comment]
从你的第一张截图来看，SQL解析和变量替换都已经成功完成了。是在执行SQL过程中你的数据库抛出了一个异常。异常信息有提示，是在 `月份`>= toDate(.....) 这个操作时，两边的数据类型不相同而报错。检查一下这里是不是有什么问题？

**Comment by Data-bytes305** [comment]
我的过滤条件：
<#if v_start_month??>
    and `月份` >= $v_start_month$
  <#else>
    and `月份` >= $v_start_month$
  </#if>

 没用任何函数，只是引用了  v_start_month变量
![image](https://user-images.githubusercontent.com/83893570/146899433-84242a25-e0f5-48b0-a15b-2433750e043a.png).
