### ISSUE TITLE
[dev][view] SQL parsing failed

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#414]
**Datart Version**
dev

**Describe the bug**
执行错误
未找到有效的查询语句

**Expected behavior**
希望跟davinci一样也能支持这张语法

**Screenshots**
![image](https://user-images.githubusercontent.com/83893570/146900760-cb3f3f17-6947-4a27-8d61-d515dcc95c16.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: mac
 - Source Database: mysql5.7
 - Browser: chrome

**Additional context**

**Comment by tianlu-root** [comment]
这个是SQL解析语法不支持，尝试这么写试试： select  * FROM \`jdbc(t,'select 1')\`

**Comment by Data-bytes305** [comment]
还是不行的.  
![image](https://user-images.githubusercontent.com/83893570/146922712-e1d414f6-b3fd-4ed8-9be2-ab77729af464.png)
后期SQL解析语法能不能支持这种写法？ 在davinci 我们用了蛮多这种场景 跨库实时查询.

**Comment by tianlu-root** [comment]
会支持

**Comment by scottsut** [comment]
为啥关掉了？是找到其他方式支持了吗？

**Comment by Data-bytes305** [comment]
我看回复后期能支持，就立马给关闭了 . 😄
