### ISSUE TITLE
变量能否支持从URL传递

### ISSUE THREAD

**Issue by francis-xjl** [running-elephant/datart#420]
**你的功能要求与某个问题相关吗？**
变量能否支持从URL传递

**形容一下你想要的解决方案**
目前我们在评估从帆软报表平台迁移至datart的场景，发现存在需要通过URL传递至展现报表的情况，比如组织编号之类的，这样在嵌入其它系统的时候能够比较方便。

**描述一下你考虑过的备选方案**
无

**Comment by scottsut** [comment]
目前支持通过 url 传递值到仪表板的控制器，通过控制器来给其关联的字段/变量赋值

**Comment by francis-xjl** [comment]
好的，非常感谢，我研究下。
