### ISSUE TITLE
建议在编辑数据图表界面增加一个数据下载的功能

### ISSUE THREAD

**Issue by hds1999** [running-elephant/datart#437]
**你的功能要求与某个问题相关吗？**
现在的下载功能需要在图表保存好以后才能下载数据，往往OLAP的场景有一部分是需要临时查询一下数据并下载下来，并不需要保存这个图表（如果保存下来图表会产生很多无用的图表信息）。

**形容一下你想要的解决方案**
建议在编辑数据图表界面增加一个数据下载的功能，并可以控制数据下载的权限。

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
有关这个功能要求的任意其他内容或截图 
![image](https://user-images.githubusercontent.com/20547693/147216692-4786d046-a4a6-4dbd-9bf6-987f54f75952.png)

**Comment by lyp000119** [comment]
#892
