### ISSUE TITLE
[dev][compile] failed

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#440]
**Datart Version**
最新dev
**Describe the bug**
Failed to compile.

./node_modules/@ant-design/pro-table/es/components/ListToolBar/index.less

    &:hover {
      color: @primary-color-hover;
           ^
Variable @primary-color-hover is undefined
      Error in /Users/zy/Downloads/datart-dev/frontend/node_modules/@ant-design/pro-table/es/components/ListToolBar/index.less (line 46, column 13)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! datart@1.0.0 build: `cross-env GENERATE_SOURCEMAP=false craco build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the datart@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/zy/.npm/_logs/2021-12-23T11_24_27_481Z-debug.log
[ERROR] Command execution failed.
**To Reproduce**
1. cd ./datart-dev
2. mvn package
**Expected behavior**

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: mac
 - Source Database: mysql5.7
 - Browser: chrome
 --node v14.18.2
 --npm 6.14.15
**Additional context**

**Comment by francis-xjl** [comment]
我在编译线上环境也遇到了，我还以为是环境或者依赖版本的问题。希望能解决。

**Comment by scottsut** [comment]
`npm list @ant-design/pro-table` 反馈一下 pro-table 的版本

**Comment by Data-bytes305** [comment]
以前都是好好的
![image](https://user-images.githubusercontent.com/83893570/147302562-6220d478-fc1c-4b6a-901e-a4f82ea9c79b.png)

**Comment by scottsut** [comment]
> 以前都是好好的

你命令执行错了，少了个`e`

**Comment by Data-bytes305** [comment]
![image](https://user-images.githubusercontent.com/83893570/147314613-0dda814c-8133-4239-a713-616c7ca3b306.png)
