### ISSUE TITLE
通过存储过程查询时，分享链接后入参错误

### ISSUE THREAD

**Issue by xuannanxan** [running-elephant/datart#469]
**Datart版本号**
datart-server-1.0.0-alpha.3-install

**错误描述**
通过存储过程查询时，分享链接后入参错误

**如何重现**
1、数据视图  call GetAttendance($beginTime$,$endTime$);
2、创建数据图表（图表直接分享是正常的）
3、创建仪表板引用该图表
4、配置查询条件，关联$beginTime$,$endTime$
5、发布后使用正常，分享后打开 提示Incorrect number of arguments for PROCEDURE GetAttendance; expected 2, got 1

**运行环境详情：(可选，取决于错误发生的具体位置)**
OS: [centos7]
数据源: [MySQL 5.7]
浏览器: [chrome]

最后发现应该是日期查询条件关联变量 是无效的

**Comment by scottsut** [comment]
未能成功复现问题，请提供以下内容帮助定位问题：
1.  日期范围控制器配置面板截图
2.  错误发生的具体请求参数及响应内容截图

**Comment by xuannanxan** [comment]
> 未能成功复现问题，请提供以下内容帮助定位问题：
> 
> 1. 日期范围控制器配置面板截图
> 2. 错误发生的具体请求参数及响应内容截图

1、因为不能执行创建和删除临时表的sql,只好通过视图查询数据，视图传入开始时间和结束时间，这里通过设置的变量传入
![image](https://user-images.githubusercontent.com/19508046/147587053-70f57781-6eb4-487c-8e91-9ec4d537a8b0.png)
2、开始时间变量的默认值 我是想默认本月1日的，无奈报错，只好设置为前3天 date_sub(curdate(),interval 3 day)
结束时间变量的默认值为今天 CURDATE()
![image](https://user-images.githubusercontent.com/19508046/147587505-71282c48-f0fb-4f57-b30f-576ccd340b62.png)
3、在数据图表中可以正常展示
![image](https://user-images.githubusercontent.com/19508046/147588065-8bbae442-1e17-409a-83c8-1f9499bb2479.png)
4、在仪表板中加入开始时间和结束时间的选择，配置如下
![image](https://user-images.githubusercontent.com/19508046/147588197-bb12ce6c-e762-4c09-b162-5c285566715e.png)
![image](https://user-images.githubusercontent.com/19508046/147588253-cbaf1583-e093-4dab-b028-207335a044ca.png)
5、保存后无法查询到数据
提示message: "Incorrect number of arguments for PROCEDURE xxxx; expected 2, got 1"
请求信息中包含
params: {endTime: ["2021-12-28 00:00:00"], beginTime: ["2021-12-01 00:00:00"]}
beginTime: ["2021-12-01 00:00:00"]
endTime: ["2021-12-28 00:00:00"]
可能是后端处理丢了一个变量吧
![image](https://user-images.githubusercontent.com/19508046/147588383-cf1fc840-a199-48f1-bd73-8a7e2f57571f.png)
