### ISSUE TITLE
图表中左侧样式->边距,点击跳转到错误页面，且无法退回

### ISSUE THREAD

**Issue by xuewenw** [running-elephant/datart#50]
[图表样式点击【边距】，首先出现找不到组件的错误，然后直接跳转到错误页面。并且点击浏览器的退回按钮无法返回之前的页面。]
![1634526867(1)](https://user-images.githubusercontent.com/30139361/137665593-063c8673-6f4b-47a0-afdd-de6b4fb2d163.jpg)

**Comment by scottsut** [comment]
我们复现不了这个问题，请补充详细信息帮忙复现：
1. 操作系统
2. 浏览器及版本号
3. 具体操作步骤
4. 更详细的截图

**Comment by xuewenw** [comment]
操作系统：window10专业版x64，处理器：AMD5600X，浏览器版本：谷
歌 78.0.3904.108（正式版本） （32 位）
可以用之前发的这个地址：http://datart-demo.retech.cc试一下，目前看到的是下面这样的，依旧是找不到组件。如果你们本地显示正常那大概率是浏览器的问题。
![1634615098(1)](https://user-images.githubusercontent.com/30139361/137840996-afd17e3a-7b80-4ea9-958f-351deb02ee86.jpg)
