### ISSUE TITLE
故事板编辑页面正常，播放页面出错（Chrome 64）

### ISSUE THREAD

**Issue by nnzh** [running-elephant/datart#544]
**Datart版本号**
dev

**错误描述**
故事板编辑页面正常，播放页面出错

**期望结果**
可以通过分享链接，全屏播放

**运行环境详情：**
- 浏览器: [ Chrome 64]

**Comment by xieliuduo** [comment]
错误的 日志有吗 前端控制台 报错截图也行

**Comment by nnzh** [comment]
![image](https://user-images.githubusercontent.com/36835843/148155713-1cfb66ba-532c-436a-b005-d15d11f97ef9.png)
![image](https://user-images.githubusercontent.com/36835843/148155856-60297072-0add-4473-8b01-b87224fbfd7c.png)

**Comment by xieliuduo** [comment]
建议升级 浏览器版本

**Comment by nnzh** [comment]
特殊环境，需要使用奇安信浏览器，Chrome内核比较低

**Comment by Cuiyansong** [comment]
> 特殊环境，需要使用奇安信浏览器，Chrome内核比较低

可以考虑修改项目的package.json中的browserslist以兼容低版本浏览器。
