### ISSUE TITLE
能否加一个报表预览功能，分享链接后跳转不生效了？

### ISSUE THREAD

**Issue by HotMancheA** [running-elephant/datart#56]
能否加一个报表预览功能，分享链接后跳转不生效了？

**Comment by caiiansheng** [comment]
还有就是 增加一个报表预览的功能，这是把两个问题合成一个吧

**Comment by scottsut** [comment]
Duplicate of #105

**Comment by MilkWangStudio** [comment]
> > 是个bug ，分享链接出来的报表，点击无法跳转，还有就是在设计阶段可以跳转 目标报表也无法根据传入的参数 展示报表
> 
> 分享的报表是无法使用跳转功能的，跳转仅在登入系统后生效。另外传入参数无效的问题请提供更详细的信息以帮助我们排查

请问是处于什么考虑，让分享出来的报表无法跳转呢？ 我这边是将datart作为一个报表系统，需要将看板嵌入到我们自有系统里。
这样的话这个无法跳转就无法做数据钻取了。
