### ISSUE TITLE
能否添加用户注册审核功能？

### ISSUE THREAD

**Issue by mortalsWorld** [running-elephant/datart#57]
如果数据是在云上的话，被其它人知道了云上的地址，如果通过恶意的注册，不断的进行恶意的请求，会使服务器压力过大，造成服务器宕机或者进程崩溃。因此能否添加一个可选的审核权限，让管理员用户对普通用户进行注册审核，并且进行权限限制，感谢！

**Comment by mortalsWorld** [comment]
> 我们暂时没有计划在 datart 上添加审批流程，而且 datart 目前也并没有超级管理员的角色可以做审核，目前倾向用其他方式来解决这个问题

那能否根据邮箱尾缀，限制用户的注册。

**Comment by mortalsWorld** [comment]
> 这个方式不太理想。等近期紧急 bug 修复完、文档上线后，我们会讨论一下现有的社区功能要求，后续结果在这个 issue 里更新

好的，感谢解答

**Comment by scottsut** [comment]
beta.3 版本已支持在 `application-config.yml` 中配置是否允许注册
