### ISSUE TITLE
建议本项目是一个基础开发框架，而不是一个系统，

### ISSUE THREAD

**Issue by kiwimg** [running-elephant/datart#572]
建议考虑：实现可以通过后端pom依赖，前端Npm依赖作为一个基础BI开发框架，方便的各种应用系统中可以灵活的嵌入集成，
而不是datart独立部署，另外权限也交给集成的系统去控制，本项目不用独立建立权限，

这样做更容易使用和推广，区别市面的其他类似产品模式。

**Comment by scottsut** [comment]
感谢建议！datart的初衷里的确包含“方便的各种应用系统中可以灵活的嵌入集成”，但社区里也有比例不小的一部分用户是不集成其他系统直接使用的，而且如果不能独立部署的话，会极大地阻碍新用户首次了解和试用它的成本。这两个问题决定了我们依然必须把它作为一个独立产品来设计。

有其他好的建议和想法，欢迎在 issue 里讨论！

**Comment by kiwimg** [comment]
所有 应该是两个项目，一个基础开发框架 方便各种的开发项目能方便的集成，类似BI内的spring开发框效果一样，进行二次应用开发，您说的我理解，我建议是个基于这个基础开发框架做一个独立部署BI应用系统，

**Comment by scottsut** [comment]
> 所有 应该是两个项目，一个基础开发框架 方便各种的开发项目能方便的集成，类似BI内的spring开发框效果一样，进行二次应用开发，您说的我理解，我建议是个基于这个基础开发框架做一个独立部署BI应用系统，

哈哈，这是一个大胆的建议，我先思考思考

**Comment by kiwimg** [comment]
这样开发人员使用的会更多，

**Comment by chens616** [comment]
> 感谢建议！datart的初衷里的确包含“方便的各种应用系统中可以灵活的嵌入集成”，但社区里也有比例不小的一部分用户是不集成其他系统直接使用的，而且如果不能独立部署的话，会极大地阻碍新用户首次了解和试用它的成本。这两个问题决定了我们依然必须把它作为一个独立产品来设计。
> 
> 有其他好的建议和想法，欢迎在 issue 里讨论！

肯定是需要能够独立部署的，需要有自己独立的权限体系，但是需要能够方便和统一身份认证系统实现集成

**Comment by scottsut** [comment]
> 所有 应该是两个项目，一个基础开发框架 方便各种的开发项目能方便的集成，类似BI内的spring开发框效果一样，进行二次应用开发，您说的我理解，我建议是个基于这个基础开发框架做一个独立部署BI应用系统，

目前无论从哪个角度来看，都不倾向于实现太技术化的基础框架，对我们团队来说弊大于利。感谢建议，有想法依然欢迎在 issue 中讨论。
