### ISSUE TITLE
计算字段验证失败Modal会直接关闭

### ISSUE THREAD

**Issue by TMBigGroup** [running-elephant/datart#578]
场景
1.图表模块新增计算字段
2.计算字段验证报错，Modal直接关闭了

期望
验证失败不要关闭，方便进行二次修改

**Comment by Cuiyansong** [comment]
目前验证是接受了Modal的回调再验证的，可以考虑验证前置，这样需求也是合理的，方案还得再研究一下。

**Comment by TMBigGroup** [comment]
对的，验证失败了，modal也被关闭且销毁了。再次打开还需要重复输入信息，使用起来有点不太舒服。
