### ISSUE TITLE
可视组件中维度和颜色（信息）存在相同列时，Duplicate column name问题

### ISSUE THREAD

**Issue by MgicCube** [running-elephant/datart#584]
**错误描述**
当“可视组件”选中一个维度“name”后，同时将“name”拖拽到“颜色”中时，出现错误“Duplicate column name 'name'”。

**如下图**
<img width="660" alt="eooro96" src="https://user-images.githubusercontent.com/57086433/148949727-4e1f5c2b-b97e-4284-b059-d3cc8a9bc081.png">

**Comment by Cuiyansong** [comment]
可能导致问题的原因是`group: [name, name]`后端默认没有去重处理，前端可以考虑对传输数据去重。
