### ISSUE TITLE
[dev]-[view] sql parse failed

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#594]
**Datart Version**
datart-dev

**To Reproduce**
![image](https://user-images.githubusercontent.com/83893570/149123324-53a9e4f2-4db5-4a67-bb30-2ab5bd0cbfe4.png)
.
此写法在clickhouse-client, davinci都可以执行成功

**Comment by tianlu-root** [comment]
这个是在进行SQL切分时，由于多层嵌套的单引号导致引号配对失败了。这么写的意义是什么？

**Comment by tianlu-root** [comment]
这个问题是由于后端会对SQL进行切分，你这个语句中 'select ''1'' as a form dual'  这里的几个单引号有歧义，导致SQL切分失败。你可以尝试这种写法： SELECT * FROM jdbc('test','select \'1\' as a form dual')  。另外确认一下，你在 clickhouse-client 上执行时输入的SQL是 SELECT * FROM jdbc('test','select \'1\' as a form dual') 还是 SELECT * FROM jdbc('test','select ''1'' as a form dual') ？
