### ISSUE TITLE
新建数据图表，界面表意错误

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#599]
新建一张数据图表，然后点击此图表，不进行其他操作，会一直显示loading图标。是否是界面表意错误？loading代表正在请求数据等，等待渲染。
![image](https://user-images.githubusercontent.com/27821997/149304339-eb14545f-8962-4a10-bfdf-1227d6b5b440.png)

**Comment by Cuiyansong** [comment]
即将关闭Issue，当前创建图表功能已变化，如有问题请留言。
