### ISSUE TITLE
自由类型布局的仪表板，界面区域显示范围有缺陷

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#607]
**Datart Version**
1.0.0-alpha.3 release

**Describe the bug**
自由类型布局的仪表板，编辑操作时，面板区域显示逻辑有缺陷。

通过调试和代码来看，默认的面板区域宽度自适应，占据非操作区域的100%，高度按比例计算后，垂直居中显示，且没有滚动条来滚动面板视图。
这样就导致一个问题，如果面板所在区域宽度比高度大一定阈值。面板上下就超出了可视区域。这时候导入数据图表，只能将图表拉入更中心的位置，或者将面板缩小至可视区域以内。引起其他的体验问题。
在空白仪表板上效果明显。
元素查看：
![image](https://user-images.githubusercontent.com/27821997/149457836-53adf75f-922c-4e60-b9d5-6e9dc0192a6d.png)
引入图表现状：
![image](https://user-images.githubusercontent.com/27821997/149457912-aa0c85aa-12ec-4a6d-9917-7bf40bcb9e3e.png)

**Expected behavior**
期望效果：
![image](https://user-images.githubusercontent.com/27821997/149457958-745838fc-27b0-4c7d-bc11-ed9e3eff9693.png)
期望加入面板外部区域滚动或者面板区域滚动，且初次展示时，能以左上角为显示原点，而不是面板中心。

PS： @TM团队

**Comment by xieliuduo** [comment]
dev分支已解决此问题
