### ISSUE TITLE
tabs折叠时 下拉框样式丢失

### ISSUE THREAD

**Issue by TMBigGroup** [running-elephant/datart#630]
<img width="580" alt="图片" src="https://user-images.githubusercontent.com/95753485/150051759-333f9173-35d9-4705-8537-06ce807966b7.png">

**Comment by Cuiyansong** [comment]
目前本地版本是4.16.13, 此版本丢失`ant-tabs-dropdown-menu-item-remove`这个class的css样式，修复链接可以参考[这里]
(https://github.com/ant-design/ant-design/commit/39f7ec5fdb9139a0f434a122e247dc1b2d6ac491)，修复的版本是4.18.4。

短期内从资源的角度来看，目前没有升级antd的计划，可以尝试增加全局css来弥补。

**Comment by TMBigGroup** [comment]
> 目前本地版本是4.16.13, 此版本丢失`ant-tabs-dropdown-menu-item-remove`这个class的css样式，修复链接可以参考[这里](https://github.com/ant-design/ant-design/commit/39f7ec5fdb9139a0f434a122e247dc1b2d6ac491)，修复的版本是4.18.4。
> 
> 短期内从资源的角度来看，目前没有升级antd的计划，可以尝试增加全局css来弥补。

👍
