### ISSUE TITLE
[dev] 编译失败

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#633]
**Datart Version**
最新 dev mvn package失败

**Describe the bug**
(!) Plugin typescript: @rollup/plugin-typescript TS5055: Cannot write file '/Users/zy/Downloads/datart-dev/frontend/src/app/assets/javascripts/sqlReservedWords.js' because it would overwrite input file.
(!) Plugin typescript: @rollup/plugin-typescript TS5055: Cannot write file '/Users/zy/Downloads/datart-dev/frontend/src/app/components/ReactFrameComponent/index.js' because it would overwrite input file.
(!) Plugin typescript: @rollup/plugin-typescript TS5055: Cannot write file '/Users/zy/Downloads/datart-dev/frontend/src/app/pages/ChartWorkbenchPage/components/ChartOperationPanel/components/ChartDataViewPanel/components/computed-function-description-map.js' because it would overwrite input file.
(!) Plugin replace: @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
(!) Plugin node-resolve: Could not resolve import "uuid/dist/umd/uuidv4.min" in /Users/zy/Downloads/datart-dev/frontend/src/utils/utils.ts using exports defined in /Users/zy/Downloads/datart-dev/frontend/node_modules/uuid/package.json.
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
node_modules/react-quill/dist/quill.core.css (7:0)
5:  * Copyright (c) 2013, salesforce.com
6:  */
7: .ql-container {
   ^
8:   box-sizing: border-box;
9:   font-family: Helvetica, Arial, sans-serif;
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/Users/zy/Downloads/datart-dev/frontend/node_modules/rollup/dist/shared/rollup.js:160:30)
    at Module.error (/Users/zy/Downloads/datart-dev/frontend/node_modules/rollup/dist/shared/rollup.js:12408:16)
    at Module.tryParse (/Users/zy/Downloads/datart-dev/frontend/node_modules/rollup/dist/shared/rollup.js:12810:25)
    at Module.setSource (/Users/zy/Downloads/datart-dev/frontend/node_modules/rollup/dist/shared/rollup.js:12713:24)
    at ModuleLoader.addModuleSource (/Users/zy/Downloads/datart-dev/frontend/node_modules/rollup/dist/shared/rollup.js:22192:20)
 。。。。

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for datart-parent 1.0.0-beta.0:
[INFO] 
[INFO] datart-parent ...................................... SUCCESS [  0.028 s]
[INFO] datart-core ........................................ SUCCESS [  9.920 s]
[INFO] datart-security .................................... SUCCESS [  2.283 s]
[INFO] datart-data-provider ............................... SUCCESS [ 12.287 s]
[INFO] datart-file-data-provider .......................... SUCCESS [  1.281 s]
[INFO] datart-http-data-provider .......................... SUCCESS [  1.394 s]
[INFO] datart-jdbc-data-provider .......................... SUCCESS [  1.621 s]
[INFO] datart-server ...................................... FAILURE [03:31 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:00 min
[INFO] Finished at: 2022-01-19T11:59:54+08:00
[INFO] ------------------------------------------------------------------------

**Environmental details: (optional, depending on where the bug occurs)**
 - OS:  mac
 - Source Database: mysql 5.7

**Comment by xieliuduo** [comment]
dev 分支已解决 打包失败问题
