### ISSUE TITLE
表格加连接实现跳转页面问题

### ISSUE THREAD

**Issue by chens616** [running-elephant/datart#635]
1.表格可以设置例如id等隐藏列，进行连接设置时，选择关联字段可以和传递参数区分开，
就是我点击哪列和传参可以不是一个字段。
2.表格组件每个列最好可以设置跳转到不同页面
3.表格跳转的页面可以在系统中不显示在菜单项中。比如从a页面跳b页面，目前要求必须b页面也有菜单权限，可以考虑不显示b菜单，但是也能跳转到b页面。
4.跳转到新页面之后添加返回按钮，目前没有返回按钮。

**Comment by scottsut** [comment]
1. 可以考虑支持，前提是不能让配置交互复杂化；如果导致复杂化，不如让id显示出来，引导用户点击id来跳转
2. 支持多列跳转配置在Q1开发计划中
3. 暂不考虑，违背资源权限控制逻辑
4. 后续会支持跳转页以3种模式打开：新页面、当前页跳转、弹窗；现在的模式为当前页跳转，点击浏览器后退按钮即可返回，无需另外增加按钮

**Comment by scottsut** [comment]
#1452
