### ISSUE TITLE
A dashboard controller linkage bug when using Chinese as an option.

### ISSUE THREAD

**Issue by wangfann** [running-elephant/datart#649]
**Datart Version**
1.0.0.beta.0

**Describe the bug**
When I configure a data chart and use Chinese characters as filter values, the filter conditions are invalid. There is no problem using English.

![image](https://user-images.githubusercontent.com/6930421/150275988-06d0fbf3-b41b-4c71-90e2-53472c67a06b.png)

![image](https://user-images.githubusercontent.com/6930421/150276088-bb4f05b6-9984-4386-a362-160c830fcfce.png)

The following situation is ok.

![image](https://user-images.githubusercontent.com/6930421/150276387-65aecd11-d7ec-4fca-be5a-37eaed4d5e49.png)

**Comment by scottsut** [comment]
Can't see your picture. It is not a common case, you'd better provide more detail to help troubleshooting.

**Comment by wangfann** [comment]
OK,the picture has been re-uploaded yet.

**Comment by xieliuduo** [comment]
浏览器的请求参数 可以分别  截图给我们吗

**Comment by wangfann** [comment]
![image](https://user-images.githubusercontent.com/6930421/150750951-cb94442e-b20a-4b13-9c80-0d4c412dc5bf.png)

**Comment by scottsut** [comment]
What database are you using?

**Comment by wangfann** [comment]
mysql
