### ISSUE TITLE
[dev]多选下拉框键盘输入导致页面崩溃

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#659]
**Datart Version**
The version of `datart` you using.

**Describe the bug**

https://user-images.githubusercontent.com/83893570/150349048-d305f3cb-4c4e-4bb6-8bdb-4a8922825239.mp4

![image](https://user-images.githubusercontent.com/83893570/150349030-86eba22a-ed97-4006-93cf-97f2f84cd6b2.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: mac
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by xieliuduo** [comment]
可以截屏一下 控制器配置 页面的情况吗

**Comment by xieliuduo** [comment]
可以复述一下 最后崩溃前的 具体步骤吗  我们看视频 试了试 复现不了@Data-bytes305
