### ISSUE TITLE
[dev]-[可视化]-[演示]数据不自动刷新

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#675]
**Datart Version**
dev
**Describe the bug**
[dev]-[可视化]-[演示] 播放方式，数据不会自动刷新。图表开启了自动刷新

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: Mac
 - Source Database: mysql5.7
 - Browser: chrome

**Comment by xieliuduo** [comment]
截图看下 你的配置 演示故事板的  以及 相关的board的
