### ISSUE TITLE
数据图表控制器相关bug

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#694]
**Describe the bug**
如图，设置了这样的数据图表。
![image](https://user-images.githubusercontent.com/27821997/151306847-d1f25771-ffd8-45b0-a5b3-44681ac6a6f9.png)
筛选器设置如下：
![image](https://user-images.githubusercontent.com/27821997/151306924-eea3b0ec-09e0-4d3c-b01e-cc1d295cf3e4.png)

获取到分享链接后打开，查看网络面板
http://datart-demo.retech.cc/share?token=IICnzIGBgwShyr8zq2E6oIJqfdKIHdwPuWFj5HiSdNDjjwmBG4iKCEUHrHMBaqM33KLh4DWqEPJ8ty6WtXqoY8mhICq2Qg7bp0lg14Hk3dOQ7MAVf2ArFbP9tdx%2FIElET06BuTilMW7UHTbBBj01wWvl2NeZxNO6Z82G4ZxfgUiyE3xfJaPw28qzjz4Po3ouyNoFsYt4uSfJkcjaHbHt4KBtRn7vSdZkEdaxjkVWiAc%3D

![image](https://user-images.githubusercontent.com/27821997/151307250-56b8b7d7-d62b-40a3-b154-3249a5cbce76.png)
可以看到控制器的接口没有后缀share，是否为bug？

另外，如果TreeSelect默认选中的值过多，会有样式的界面显示问题。

![image](https://user-images.githubusercontent.com/27821997/151308201-cdc070f4-a603-48f4-a05b-0d70b43bb7cf.png)

TreeSelect会占满高度，且不可滚动，图表完全不可见

图表：
![image](https://user-images.githubusercontent.com/27821997/151307724-752eedc2-6d0a-4407-b77a-702f1509e443.png)

**Expected behavior**
1. 希望分享页单独调用share相关接口
2. 修复样式

**Comment by scottsut** [comment]
第二个问题可以通过自行调整控制器宽度来解决

![image](https://user-images.githubusercontent.com/4098913/151321591-9cccf688-6ed3-46dc-aa99-0482791e785d.png)

**Comment by scottsut** [comment]
#1573
