### ISSUE TITLE
关于组织和权限相关的问题

### ISSUE THREAD

**Issue by chens616** [running-elephant/datart#736]
一问题描述
![image](https://user-images.githubusercontent.com/4082129/153315043-b27bd09e-b58a-417d-a148-5267c169de48.png)
1如上图，邀请其他成员加入自己组织，需要先搜索，再邀请，此设计仅适用于邀请少量成员加入组织，如果邀请大量用户加入组织，需要搜索每个成员，邀请加入，此操作需要重复n次，比较繁琐。
2.关于用户和权限，datart作为一个专注统计分析和数据可视化的解决方案，目前具有独立的用户和权限系统，按照通常企业级系统规划，datart应该作为整个企业系统中针对数据可视化领域的一个子系统，用户不应该是孤立的仅适用于datart，不是独立的在datart中创建，用户应该来源于业务系统或者统一身份认证平台。

二解决方案
1.对于第一个问题，给出如下建议：
1）按照用户角色的不同组织的特性应该不同，具体就是具有管理员角色的用户默认具有一个更大级别的组织，其他用户注册之后，可以直接加入该组织，不需要邀请。
2）优化邀请的方式，列出所有注册用户，可以实现批量邀请。

2.对于第二个问题，建议重点考虑如下：
1）用户基础数据的同步，其他平台的用户数据如何与datart同步；
2）支持对接到统一身份认证平台，实现统一认证、统一授权、单点登录，

**Comment by Cuiyansong** [comment]
关于问题二其实是分为两部分，一部分是用户鉴权，例如SSO；另一部分是Datart角色权限倒入到出。前者问题容易做兼容处理，而后者会比较繁琐并需要设计。

**Comment by chens616** [comment]
> 关于问题二其实是分为两部分，一部分是用户鉴权，例如SSO；另一部分是Datart角色权限倒入到出。前者问题容易做兼容处理，而后者会比较繁琐并需要设计。

是的，关于问题二，主要是确认一下，问题的必要性和优先级，以我的认知，感觉如果想让datart在企业中大面积使用，解决这个问题是必由之路。

**Comment by chens616** [comment]
建议支持OAuth2、oidc、LDAP等协议

**Comment by kiwimg** [comment]
datart不用自己在建立一套独立的组织和权限，而是应该交给使用方的系统，只有能datart适配就可了，除非datart定义的是独立完整系统，不过这样和市面的BI产品没有啥区别

**Comment by scottsut** [comment]
LDAP supported in #1024 , will be available in next release.

**Comment by clementchong** [comment]
> LDAP supported in #1024 , will be available in next release.

This is good news! Thank you
