### ISSUE TITLE
各类图表内的维度内容名词没办法自定义

### ISSUE THREAD

**Issue by ethanguo2019** [running-elephant/datart#760]
各类图表内的维度内容名词没办法自定义，展示的时候经常要对几个名词进行合并，比如月份1-12月，把月份拉到维度，怎么可以设置成季度or其他；IF（月份=‘1月’or月份=‘2月’or月份=‘3月’，‘第一季度’，）

**Comment by scottsut** [comment]
可以考虑用计算字段来实现

![image](https://user-images.githubusercontent.com/4098913/153813779-6afa654d-1645-4135-bc14-266a6b10fd23.png)
