### ISSUE TITLE
媒体组件增加边框和挂饰组件

### ISSUE THREAD

**Issue by byc233518** [running-elephant/datart#816]
**你的功能要求与某个问题相关吗？**
制作大屏时经常会用到边框和一些动态挂饰点缀

**形容一下你想要的解决方案**
媒体组件中增加 边框/挂饰 组件

**描述一下你考虑过的备选方案**
使用图片组件,上传图片实现

**其他内容**
这是之前在 davinci3 上二开的效果
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/13425815/154606181-c579d001-b6f6-413d-a1ba-5c4becbc8212.png">

**Comment by scottsut** [comment]
你们之前二开也是基于图片组件来做的吧？

**Comment by xieliuduo** [comment]
最近会排期

**Comment by byc233518** [comment]
感谢
