### ISSUE TITLE
看板中的表格与下载后的表格展示不一致

### ISSUE THREAD

**Issue by zhihui-github** [running-elephant/datart#818]
**你的功能要求与某个问题相关吗？**
看板中的表格与下载的表格展示不一致

**形容一下你想要的解决方案**
1：看板中包含多个表格下载后会放到一个execle一个表格里但没有每个表格的名字带过，表格一多不知道哪个是哪个了
        建议：1:下载时带上表格的名称或看板中的每一个表格可以单独下载
2：下载后的表格列顺序错乱，复杂的报表看板中通过透视表整好了格式，下载后格式没有了
      建议：跟看板中的表格保持一致

**其他内容**
![Snipaste_2022-02-18](https://user-images.githubusercontent.com/52650676/154633325-c6023c61-a100-4860-b4ca-ae39eff58648.png)
![Snipaste_2022-02-18_15-01-03](https://user-images.githubusercontent.com/52650676/154633910-68220fc9-e73d-438a-b515-4f182d85c0c5.png)

**Comment by scottsut** [comment]
第二个问题比你想象的要麻烦，预计短时间不会支持

**Comment by snycc15** [comment]
以图片方式导出更好

**Comment by scottsut** [comment]
> 以图片方式导出更好

图片导出后续会支持

**Comment by zhihui-github** [comment]
> 第二个问题比你想象的要麻烦，预计短时间不会支持

了解，我先用iframe嵌套其他家的处理。
