### ISSUE TITLE
websocket 方式数据展示支持

### ISSUE THREAD

**Issue by byc233518** [running-elephant/datart#820]
**你的功能要求与某个问题相关吗？**
看板需要显示实时数据

**形容一下你想要的解决方案**
支持websocket 类型的数据源配置

**描述一下你考虑过的备选方案**
定时刷新

**其他内容**
参考dataV的实现
https://help.aliyun.com/document_detail/142630.html
![image](https://user-images.githubusercontent.com/13425815/154641658-20dd73dc-f97c-457e-ab8a-a3eb6bdd40fd.png)
![image](https://user-images.githubusercontent.com/13425815/154641659-3c693f81-27d1-4788-b399-9afe532f7ee9.png)

**Comment by scottsut** [comment]
暂不考虑支持，如果有适合的场景欢迎继续留言讨论
