### ISSUE TITLE
新建故事板会自动跳回仪表板和数据图表界面

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#829]
**Describe the bug**
新建故事板会自动跳回仪表板和数据图表界面

**To Reproduce**
1. 切换到演示
2. 新建故事板
3. 页面会自动跳回到目录下的仪表板和数据图表界面

**Expected behavior**
不自动切换

**Comment by xieliuduo** [comment]
![svg1](https://user-images.githubusercontent.com/23504234/155927064-9b0f00a8-04d4-4028-be3e-78196bb8ef0a.svg)
