### ISSUE TITLE
前端部署时报跨域

### ISSUE THREAD

**Issue by s1046** [running-elephant/datart#83]
为什么不增加跨域的配置呢
![image](https://user-images.githubusercontent.com/9443613/138229015-5095ff0b-2174-4791-aa50-98995deafdf5.png)

**Comment by scottsut** [comment]
`craco.config.js` 或是 `package.json` 中都可以配 proxy，具体使用方式参考 https://create-react-app.dev/ 和 https://github.com/gsoft-inc/craco
