### ISSUE TITLE
组件设置了自动刷新数据，故事板播放，不会自动刷新数据

### ISSUE THREAD

**Issue by taojing001** [running-elephant/datart#834]
拉取源码部署，commit号：a84e7269797587b134beafe0921b589b25e38fc1
版本号：1.0.0-beta.1

**Comment by xieliuduo** [comment]
@taojing001 不能复现  请按照issues模版 每一步填写完整，最好有配图

**Comment by taojing001** [comment]
麻烦了，我也没有复现该问题
