### ISSUE TITLE
missing FROM-clause entry for table "datart_vtable"

### ISSUE THREAD

**Issue by zhangsir1993** [running-elephant/datart#842]
**Datart Version**
1.0.0-beta.1

**Describe the bug**
数据源：postgresql
数据视图可以查出数据，没有问题
数据分析，拖入字段后报错 missing FROM-clause entry for table "datart_vtable"
应该是表别名的问题

**Comment by zhangsir1993** [comment]
截图：
![1645594001(1)](https://user-images.githubusercontent.com/88522070/155266076-0c5c696d-1c68-440d-bbd6-c2d54df476dd.png)

**Comment by zhangsir1993** [comment]
这个bug 有人帮忙看一下吗 @scottsut @tianlu-root

**Comment by scottsut** [comment]
> 这个bug 有人帮忙看一下吗 @scottsut @tianlu-root

你贴一下数据视图界面截图吧

**Comment by zhangsir1993** [comment]
@scottsut 麻烦看一下，同样的语句 换成mysql就没问题。
