### ISSUE TITLE
希望能支持Amazon 的 Athena数据源

### ISSUE THREAD

**Issue by SuperPoon** [running-elephant/datart#845]
希望能支持Amazon 的 Athena数据源
目前海外业务基本都是Amazon云服务

**Comment by scottsut** [comment]
不一定需要我们支持才能使用，可以按照文档扩展试试 https://running-elephant.github.io/datart-docs/docs/jdbc.html

**Comment by SuperPoon** [comment]
好的 那我们自己搞搞 多谢

**Comment by scottsut** [comment]
如果可以支持，麻烦在这个 issue 下反馈一下
