### ISSUE TITLE
用户不需要注册，我们后台直接邮件邀请即可；创建组织的权限可以配置，不希望用户都能创建组织

### ISSUE THREAD

**Issue by SuperPoon** [running-elephant/datart#848]
1. 用户不需要注册，我们后台直接邮件邀请即可
目前新用户进入，只能通过邮件邀请，没有注册的用户邀请会报错，这个新增用户流程有点繁琐；
希望 能够 1. 管理员可以直接后台添加用户，用户进入后自己更改密码
                 2.或者 直接邮件邀请，不需要用户注册即可进入组织
2. 创建组织的权限可以配置，不希望用户都能创建组织
目前新用户进入都可以创建组织，这个场景在实际使用中，很鸡肋
希望 1. 用户进入后不能创建组织
         2. 创建组织可以通过权限控制，例如超级管理员可以创建组织吗，其他不可以

**Comment by scottsut** [comment]
beta.3 版本已支持
1. 在 `application-config.yml` 中开启/关闭注册
2.在 `application-config.yml` 中配置租户管理模式，团队模式下不能创建组织，由管理员直接添加/删除用户
