### ISSUE TITLE
为数据图表中的字段设置别名出错

### ISSUE THREAD

**Issue by wmy7724** [running-elephant/datart#86]
编辑页面设置别名，显示没问题
![image](https://user-images.githubusercontent.com/38877473/138234457-d03436e1-56d1-416e-8e47-1b573b7959dc.png)
点击保存以后，别名显示出错
![image](https://user-images.githubusercontent.com/38877473/138234611-870c5040-7b18-49f9-80c6-3146cbdf9048.png)

**Comment by scottsut** [comment]
这个跟数据库字符集相关吧，看看数据库字符集是不是 utf8

**Comment by wmy7724** [comment]
> 这个跟数据库字符集相关吧，看看数据库字符集是不是 utf8

嗯，确实，可是我把数据库改成utf8以后，重启服务，还是不行，还有什么地方需要改么
