### ISSUE TITLE
计算字段自动转换大写导致查询失败

### ISSUE THREAD

**Issue by Data-bytes305** [running-elephant/datart#866]
**Datart Version**
datart-dev
**Describe the bug**
![image](https://user-images.githubusercontent.com/83893570/155643356-9aaf2a2f-a04d-4943-8333-bea452fb03a2.png)

**To Reproduce**
1. 新建计算字段 
2. 查询失败
**Expected behavior**
希望不需要自动转换大写. 因为某些数据库会区分大小写.

**Comment by tianlu-root** [comment]
#987
