### ISSUE TITLE
Excel download data columns sequence is different from table visualisation

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#883]
**Datart Version**
1.0.0beta1

**Describe the bug**
Excel download data columns sequence is different from table visualisation. All the summed columns appear first.

**To Reproduce**
1. Go to any table visualisation with dimension and aggregated data.
2. Download to excel
![mmexport1645885286708](https://user-images.githubusercontent.com/100477931/155846618-17619ef7-cc8f-49d1-a808-7db9b5796916.jpg)

**Expected behavior**
The excel content should be identical to the visualization on screen.

**Screenshots**

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: Windows Server 2019
 - Source Database: MySQL 8.0.25
 - Browser: Chrome 98

**Additional context**

**Comment by clementchong** [comment]
Could someone help clarify on the invalid change?

https://github.com/running-elephant/datart/pull/1057

**Comment by clementchong** [comment]
I was able to get the correct column order sequence in excel export after the change in 1.0.0b2. How come it is invalid change?

**Comment by scottsut** [comment]
We review your code according to the title description of PR. Actually, it works well in some scenarios with pivot sheet, but table chart have a completely different process. Anyway, we accept this PR. Thanks for the contribution!

**Comment by clementchong** [comment]
Thank you for the clarification. Sorry for unclear PR description.
