### ISSUE TITLE
Not full english interface in viz style setting panel

### ISSUE THREAD

**Issue by clementchong** [running-elephant/datart#885]
**Datart Version**
1.0.0beta1

**Describe the bug**
User interface is not full english

**To Reproduce**
1. Go to Viz
2. Click on bar chart. Add dimension and measures
3. Click on style
4. See the dropdown texts in chinese.

**Expected behavior**
Remaining chinese text should be replaced with english for a consistent user experience.

**Screenshots**
![image](https://user-images.githubusercontent.com/100477931/155880189-671a8edd-9599-4a19-a857-74ccc2bdb82e.png)

**Environmental details: (optional, depending on where the bug occurs)**
 - OS: [e.g. Windows 10] 
 - Source Database: [e.g. MySQL 8.0.26]
 - Browser: [e.g. chrome 94, safari 15]

**Additional context**

**Comment by clementchong** [comment]
datart-1.0.0-beta.1/frontend/src/app/components/FormGenerator/Customize/DataReferencePanel.tsx

**Comment by scottsut** [comment]
Welcome to help us finish i18n.

**Comment by clementchong** [comment]
I can help to replace the chinese text with the value already in English. However, I do not have expertise to make it multi-language

**Comment by clementchong** [comment]
Managed to replace the hardcoding to validate right file. Would attempt to add i18n

![image](https://user-images.githubusercontent.com/100477931/155955020-b9bdf00c-eac7-460f-920a-cdedfb4035c4.png)

**Comment by clementchong** [comment]
Not successful so far. Build error.

**Comment by clementchong** [comment]
Seems succesful for one chart now. Would try do the rest.

![image](https://user-images.githubusercontent.com/100477931/159014212-1dd13964-2f62-4459-aae9-9885abb7a3d5.png)

**Comment by clementchong** [comment]
Fixed in 1.0.0b3
