### ISSUE TITLE
图表资源样式标签中的百分比开闭功能不完整

### ISSUE THREAD

**Issue by snycc15** [running-elephant/datart#890]
**Datart版本号**
beta.1
**错误描述**
百分比开闭功能不完整,鼠标浮动仍然显示百分值
**截图如下**
![image](https://user-images.githubusercontent.com/67908124/155919350-04157b1e-cd75-499a-8143-7c67e79df08b.png)

**Comment by scottsut** [comment]
没有问题，提示信息中的维度值、数值和百分比是常驻的，你修改的是标签配置
