### ISSUE TITLE
图表样式标签百分比开关功能不完整

### ISSUE THREAD

**Issue by snycc15** [running-elephant/datart#891]
**Datart版本号**
datart.beta.1
**错误描述**
样式标签百分比开关不能控制鼠标浮动显示，关闭后，仍显示百分比值
**截图**
![image](https://user-images.githubusercontent.com/67908124/155922354-efe41fcd-9866-4fe5-a8d0-6af56cc09684.png)

**Comment by scottsut** [comment]
#890 已经回答你了，不要重复提问
