### ISSUE TITLE
加入颜色配置后，重复运行某些函数，可能导致性能问题

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#894]
**Describe the bug**
代码中有这一段遍历，一般在加入颜色配置后，secondGroupInfos数据量级将变得不可控，是否考虑将getLabelStyle，getSeriesStyle抽出此段代码，运行一次即可？
<img width="664" alt="image" src="https://user-images.githubusercontent.com/27821997/155939887-629fb5e5-f67e-4107-a33c-5fead517aa5a.png">

**Comment by Cuiyansong** [comment]
“可以优化但可能收效甚微”，建议在大数据量的情况下，使用Datart的Debuger工具测试一下。可以参考下BaiscTableChart.tsx中的使用方式。
