### ISSUE TITLE
图表坐标轴刻度文本溢出配置及图例过长时分页配置

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#898]
**Is your feature request related to a problem? Please describe.**
1.配置坐标轴刻度时，如果文本过长，坐标轴上的文字显示会全部叠在一起，无法阅读。
2.图例过多时，会占据坐标轴显示内容，造成无法阅读

**Describe the solution you'd like**
1. 图表坐标轴刻度文本溢出配置
参考[官方配置](https://echarts.apache.org/zh/option.html#xAxis.axisLabel.overflow)将文本溢出的配置暴露出来。

大致包含所有继承于Barchart和LineChart的类
<img width="295" alt="image" src="https://user-images.githubusercontent.com/27821997/155959314-a031f1b8-a428-4867-982b-7f0e96417d21.png">
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/27821997/155959355-23c5fdd9-7407-41c5-ad33-1ee25ca65580.png">
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/27821997/155959424-527acd61-9c7d-42fe-ac37-98cc55d61a87.png">
<img width="1299" alt="image" src="https://user-images.githubusercontent.com/27821997/155959465-c05bf5b8-f9ae-4908-84bc-47e6b3bb38b8.png">
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/27821997/155959494-7c070d18-9ea3-40b4-81de-b7049bf5df64.png">

3. 图例过长时分页配置

图例在图例位置为左右时可以配置图例高度，漏斗图会根据排序方式自动将图例放置于空白位置
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/27821997/155957576-d5c1d882-72b6-4619-bffe-0b041cf18f0b.png">

**Comment by scottsut** [comment]
1. 文本溢出的处理逻辑值得借鉴
2. “图例高度”功能与“边距”重合

**Comment by Wesilnt** [comment]
我是TM团队的一员，现在以上功能都已经开发完毕，第一个能接受pr么？
关于第二点——“图例高度”功能与“边距”重合。
1.如果图例长度或文本长度够长时，图例可能就占据更多的布局区域，导致主要内容显示范围缩小。
2.图例文本长度非固定，可能为了某些较长的图例文本就要设置比较大的边距来保证图例文本和标签不会覆盖掉。
3.而且我比较倾向于是边距和高度都存在，以灵活应对更多的使用场景，提供给用户更多选择。
以上

**Comment by scottsut** [comment]
> 我是TM团队的一员，现在以上功能都已经开发完毕，第一个能接受pr么？ 关于第二点——“图例高度”功能与“边距”重合。 1.如果图例长度或文本长度够长时，图例可能就占据更多的布局区域，导致主要内容显示范围缩小。 2.图例文本长度非固定，可能为了某些较长的图例文本就要设置比较大的边距来保证图例文本和标签不会覆盖掉。 3.而且我比较倾向于是边距和高度都存在，以灵活应对更多的使用场景，提供给用户更多选择。 以上

明白了，感谢说明！两个问题都欢迎 pr。
