### ISSUE TITLE
仪表盘加载时间过长

### ISSUE THREAD

**Issue by ziveen** [running-elephant/datart#924]
**你的功能要求与某个问题相关吗？**
首次进入仪表盘页面，当仪表盘中图表的数量过多时，页面加载时间过长。基本与图表的数量成正比。

**形容一下你想要的解决方案**
仪表盘加载逐步加载图标内容，不要一次加载出来，然后等待时间过长。

**描述一下你考虑过的备选方案**
清晰简洁地描述任意你考虑过的备选方案和功能

**其他内容**
![image](https://user-images.githubusercontent.com/22560152/156567202-f064b809-6e12-40f8-9454-ed3ea7aa02fc.png)
![image](https://user-images.githubusercontent.com/22560152/156567285-51b06ec7-90f3-471a-b0da-69827c7776ac.png)

**Comment by ziveen** [comment]
我刚才在官方的网上测试了这个问题，同样存在同样的的问题。明天继续追踪问题。
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/22560152/156599409-f20d912f-746d-454c-a6c0-92c7d2d45938.png">
<img width="768" alt="image" src="https://user-images.githubusercontent.com/22560152/156599448-d8536a89-16ef-467c-938c-7ee94c053357.png">

**Comment by scottsut** [comment]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/4098913/156601723-49b81650-e4ee-4a04-89c9-03053638f486.png">

我这边测试同一个仪表板，平均打开速度在 160 ms 上下，仅有 1 次耗时 3.1 秒。明天继续排查

**Comment by ziveen** [comment]
经过本地测试与requestAnimationFrame这个api有关。当widget数量增多时，时间也会很长。替换为setTimeout时，加载速度会降很多，不过流畅度不行。
![image](https://user-images.githubusercontent.com/22560152/156690091-cad67024-dc5d-4965-b8aa-de797168fcd5.png)

**Comment by scottsut** [comment]
requestAnimationFrame 是 HTML API，不会影响静态资源的加载速度；也就是说，和你第一个截图里的 7.52 秒没有任何关系

**Comment by ziveen** [comment]
通过浏览器的分析工具，可以看出是requestAnimationFrame的回调函数的问题。当图表数据过多时，可以稳定复现。
![image](https://user-images.githubusercontent.com/22560152/156987278-58e92153-2086-4c82-abc0-ba95253d12c4.png)，
![image](https://user-images.githubusercontent.com/22560152/156987336-58f8c825-c74e-486c-95a5-10488a956722.png)

**Comment by scottsut** [comment]
这条调用链确实有问题，requestAnimationFrame 本身只用了 0.18 ms，

**Comment by xieliuduo** [comment]
@ziveen  test it
