### ISSUE TITLE
货币型小数位数不生效

### ISSUE THREAD

**Issue by llf007** [running-elephant/datart#939]
**Datart版本号**
1.0.0-beta.1 release

**错误描述**
货币型 小数位数，配置不生效

**期望结果**
期望修正

**截图**

![image](https://user-images.githubusercontent.com/60683568/156958761-67657dc5-17f7-4860-9e47-223aa8c83d1f.png)

**Comment by Cuiyansong** [comment]
请提供下复现步骤

**Comment by Cuiyansong** [comment]
暂时无法复现，如有复现请留言。
