### ISSUE TITLE
自由定制页面仪表盘加载慢

### ISSUE THREAD

**Issue by francis-xjl** [running-elephant/datart#949]
加载类似的一个仪表盘，有点慢，页面加载需要好久。看chrome标记的耗时主要是花在是在Scripting阶段，分析了好久没分析出来原因，大佬帮忙看看T_T。
<img width="1210" alt="QQ20220307-202749@2x" src="https://user-images.githubusercontent.com/17879879/157036978-c970514c-ddc7-4071-8d3e-a623659b9e50.png">

看Chrome的Profile请求并处理一个URL要近6s
![QQ20220307-204211](https://user-images.githubusercontent.com/17879879/157036992-d6d33d76-d166-46d0-ab83-f595a26c6033.png)
![QQ20220307-204250](https://user-images.githubusercontent.com/17879879/157036998-a3e45344-fad2-436f-b6c0-baf8c250d712.png)

这是压缩后的profile文件，可以解压后，导入到chrome进行分析。
[Profile-20220307T204254.json.zip](https://github.com/running-elephant/datart/files/8197767/Profile-20220307T204254.json.zip)

**Comment by francis-xjl** [comment]
提的时候，我看到了#924那个issue，确定原因是一样的么？我本地按这个修复逻辑修改了下，好像并没有什么效果。

**Comment by xieliuduo** [comment]
你是分享页面的加载，还是应用内呢？如果方便的话，可以上传一个视频来看看。或者在社区群里 @ 我们

**Comment by francis-xjl** [comment]
http://datart.mgmos.com.cn/share?token=DNLqHvGotgh6jHo0mVUx%2FtT%2B8Yz0jOFsN%2BrZkA05mTmKugWV9ZmNVFdJ3t2jtfmsOtw2hgEp%2BAZsQjKVKHq5e7oJPbyrebFdKecbeNwBHnpvHLBGX4jv6rM0OTibjsY8cfEV3ti%2Be4r7zseKJlgXyTVRG%2Beg9f9SjebaSOC3MsEAmhe7DpEgcn8r2lzSq5llcdUZUWfJTBZy3LuWOHhVc5Mk0b1NPkH3BJyRCH%2B4PeM%3D  @xieliuduo 我分享给一个链接给你，可以直接打开。

**Comment by xieliuduo** [comment]
@francis-xjl  看看 pr #976 的效果呢

**Comment by francis-xjl** [comment]
大神牛逼，本地测试已经有很大的改善，非常感谢！
