### ISSUE TITLE
ClickHouse 连接测试 报错

### ISSUE THREAD

**Issue by CharlesTHN** [running-elephant/datart#970]
**Datart版本号**
datart-server-1.0.0-beta.1

**错误描述**
ClickHouse 连接测试时报错，当前驱动包为0.2.4版本。同样的配置在davinci，甚至我记得较早版本的datart都没问题

**截图**
![image](https://user-images.githubusercontent.com/19632429/157578352-e06525c3-f8d5-42ee-956f-b1920809134a.png)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: CentOS 7
- 数据源: ClickHouse 21.9.2.17
- 浏览器: chrome  99.0.4844.51

**Comment by tianlu-root** [comment]
缺依赖包，把缺失的依赖包补上

**Comment by CharlesTHN** [comment]
我加了个lz4-java-1.8.0.jar，现在可以了，感谢
