### ISSUE TITLE
STRING类型的筛选组件FilterControllPanel  一些问题

### ISSUE THREAD

**Issue by Wesilnt** [running-elephant/datart#971]
**Describe the bug**
以下bug复现在http://datart-demo.retech.cc/下，
选择test组织，微博热度明细表
<img width="772" alt="image" src="https://user-images.githubusercontent.com/27821997/157606341-2572a5a0-7e51-44d4-8280-9e060ca46767.png">

进入编辑状态后，将TITLE拖入筛选区域，并点击弹开过滤Modal。
**q1:**
直接点确定，会出现必填提示
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/27821997/157606727-c0a7f2a0-5ced-40b5-823d-4271a6104810.png">
但是从transfer中选中某个源列表中的内容移入默认列表再移出，点击确定，就不会出现必填提示
<img width="814" alt="image" src="https://user-images.githubusercontent.com/27821997/157606952-3537f318-1e8c-4019-8107-1aa26d79be21.png">

**q2:**
在q1的操作之后，tabs直接从常规切换到自定义，点击确定，会报错400，此时发现接口中filters下的sqlOperator为null，前端应该未做清除。

**q3:**
且在各tabs间切换，不填内容，均没有必填提示，但在切换了聚合方式后再切换回来，会发现必填提示又出现了。

**q4:**
在常规中往默认列表添加了数据后，切换聚合方式为计数，会发现筛选方式第一个select框的值为IN，且可以直接点击确定。在条件中选中筛选方式后再切换聚合方式也会发现类似问题。

<img width="886" alt="image" src="https://user-images.githubusercontent.com/27821997/157607812-5f7edc16-bead-4f4b-832d-aef8b640a403.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/27821997/157607839-04f877f1-0964-4698-806d-d9eaa56a03dc.png">

**q5:**
从常规切换到自定义行，点击增加行，再点击列表中的删除或者设置为默认，页面直接崩溃，且网址变为
http://datart-demo.retech.cc/organizations/44cd7f77a5444800a2bed027ef30b42e/vizs/chartEditor#!
<img width="979" alt="image" src="https://user-images.githubusercontent.com/27821997/157608247-efdb6a38-fc2c-46fb-9e3c-6c1f7b45340a.png">

**q6:**
transfer在数据量过大时（比如3000条），卡顿明显，是否改为虚拟加载？

**Additional context**
最近在做筛选相关的需求，对此处代码调试较多。当前的filter数据做状态切换与状态清除，感觉随着过滤各种条件的变多会有些吃力，且切换时候容易遗漏，需要在每个子组件中处理异常情况。是否将数据结构改为map:[聚合方式][筛选方式][state]，这样既可以保证切换时候各状态间互不影响，也可以有历史追溯。
仅是个人不成熟的想法~

**Comment by Cuiyansong** [comment]
Filter整体重新设计了数据验证方式：
已修复，Q1，Q2，Q3，Q5（⚠️默认值为“默认”添加）
⚠️注意：Q4（目前在切换聚合方式后，代码会清空过滤条件，当直接点击确定后会意外规避空值验证，再次打开过滤条件会恢复空值验证，问题的原因是组件为非受控组件导致初始化值未被清空）

待修复：
- [ ] Q4
- [ ] Q6

**Comment by Cuiyansong** [comment]
> Additional context
最近在做筛选相关的需求，对此处代码调试较多。当前的filter数据做状态切换与状态清除，感觉随着过滤各种条件的变多会有些吃力，且切换时候容易遗漏，需要在每个子组件中处理异常情况。是否将数据结构改为map:[聚合方式][筛选方式][state]，这样既可以保证切换时候各状态间互不影响，也可以有历史追溯。
仅是个人不成熟的想法~

期待Demo

**Comment by Wesilnt** [comment]
Demo方面，我是考虑历史追溯功能，比如 筛选的数据结构如下：
`
// 筛选配置Modal  数据
filterConfig:{
name:string
aggType:'NONE'|'COUNT',
filterType:'regular'|'custom'|'condition'|'normal'
hide:boolean,
agg_none:{
// 常规类型
regular:RegularType,
// 自定义类型
custom:CustomType,
// 条件类型
condition:ConditionType，
},
agg_count:{
// 计数的筛选方式
normal:NormalType
}
}
`
切换时，根据aggType和filterType来获取和更改对应数据，不会清除旧数据，保存时，只需要保留当前选择的数据模型即可。
