### ISSUE TITLE
故事板权限检查 权限拒绝 

### ISSUE THREAD

**Issue by bigidetech** [running-elephant/datart#982]
版本：master 分支
问题描述： 
使用owner用户创建多个故事板，授权非空间owner用户peter全部权限
使用用户peter登录后故事板可见，但是向故事添加page报 权限拒绝 
![具备故事板全部权限](https://user-images.githubusercontent.com/76947947/157819044-0743a7fd-45b3-4b6c-bbda-30c2f8963a7e.png)
![添加看板权限不存在](https://user-images.githubusercontent.com/76947947/157819059-8bff2de4-e43c-4392-a180-925f433116c1.png)

**Comment by Cuiyansong** [comment]
即将关闭issue，如有问题请留言。

**Comment by scottsut** [comment]
Related to #1523
