### ISSUE TITLE
添加富文本，光文字时报错

### ISSUE THREAD

**Issue by francis-xjl** [running-elephant/datart#990]
**Datart Version**
官网上http://datart-demo.retech.cc/，添加富文本时报错。

**Describe the bug**
1. 添加富文本，不选择数据，直接输入文字。
<img width="1643" alt="WX20220311-170854@2x" src="https://user-images.githubusercontent.com/17879879/157836922-47a74912-2947-4170-b203-b51a652364da.png">

2. 点击保存后报错：
<img width="1419" alt="WX20220311-170546@2x" src="https://user-images.githubusercontent.com/17879879/157836971-2cf01cd1-5191-4cef-a560-af3023a62027.png">

**Comment by scottsut** [comment]
现在图表组件必须选择一个数据视图。这个问题后续会优化
