### ISSUE TITLE
docker run 之后访问datart

### ISSUE THREAD

**Issue by Leeaoyin** [running-elephant/datart#993]
**Datart版本号**
docker run -p 8080:8080 datart/datart
（已配置挂载文件datart/config/datart.conf外部数据库）
**错误描述**
docker启动访问datart，保存仪表盘报错未知字段sub_type，而在官方给出的bin/datart.sql中folder没有此字段

**如何重现**
重现错误的步骤，例如：
1. docker run ....
2. login
3. 新建仪表盘，保存
4. 看到错误

**截图**
![image](https://user-images.githubusercontent.com/50786484/158006485-bf969c30-e8fb-4f77-8a44-3e9889f54769.png)

![image](https://user-images.githubusercontent.com/50786484/158006525-0aceedfd-6470-462c-ba15-f9d311ffe769.png)

**运行环境详情：(可选，取决于错误发生的具体位置)**
- OS: docker
- 数据源: rds8.0
- 浏览器: [例如 chrome 94, safari 15]

**其他内容**
有关这个问题的任意其他内容

**Comment by scottsut** [comment]
docker 镜像已更新
